### ISSUE TITLE
Should jobs auto add a "start event" on the client at creation?

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1068]
```
	// TODO: Should jobs auto add a "start event" on the client at creation?
```

https://github.com/filecoin-project/bacalhau/blob/901fc8d1f0c542fe3a4e9c8cbed7062fc5c90395/cmd/bacalhau/utils.go#L612

**Comment by wdbaruni** [comment]
It depends on what you plan to use the start time for, but I wouldn't recommend it as we have less control on how much client clock can be skewed
