### ISSUE TITLE
Should BACALHAU_PATH be replaced with BACALHAU_DIR

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#1071]
Do `BACALHAU_PATH` and `BACALHAU_DIR` represent different things or are they the same and should be unified?
https://github.com/filecoin-project/bacalhau/blob/main/pkg/config/config.go#L118
https://github.com/filecoin-project/bacalhau/blob/main/pkg/system/config.go#L185

**Comment by aronchick** [comment]
Sadly these links are out of date - but when I think bacalhau path, I think of where the binary is, vs in the dir case, I think of where the storage/config/whatever is. Not sure!

**Comment by lukemarsden** [comment]
I think they both point to the .bacalhau local config directory and yes they should be unified and then the single one documented
