### ISSUE TITLE
Add Request ID to all incoming requests

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#1074]
Adding a unique request id to each incoming API request, and sending it back in the response payload to help debug incidents and know which host handled a specific request.  We can start with UUID as a request id assigned on the server side, and then explore extending and enriching the request id with data that can be decoded to know more about the request without having to grep the logs, similar to [S3 extended request id](https://aws.amazon.com/premiumsupport/knowledge-center/s3-request-id-values/)

**Comment by wdbaruni** [comment]
The extended request id can hold the following info:
- timestamp
- nodeID (might be too large. Using nodeIP might be more space efficient)
- clientID (or clientIP for the same previous reason)
- ...

**Comment by lukemarsden** [comment]
doesn't opentracing give us this already?

**Comment by wdbaruni** [comment]
If opentracing already assigns a unique identifier per request, then we might just reuse that and include it in the response payload. Today we are not returning any request identifier to the client, which makes debugging failed requests very challenging
