### ISSUE TITLE
Bacalhau Orchestration Changes

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#1098]
[Bacalhau Orchestration](https://www.notion.so/pl-strflt/Bacalhau-Orchestration-8cf6f483414c4457954b5abfcc4bf509) design doc proposes significant changes to on how jobs are negotiated and orchestrated in Bacalhau to improve the reliability and scalability of the network, along with how the job state is managed. 

This top level epic tracks the tasks and sub-epics required to deliver the proposed changes

Children:
- [x] #1086
- [x] #1092
- [x] #1097 
- [ ] #1418 
- [x] #1102
- [x] #1106
- [ ] #1117

**Comment by aronchick** [comment]
Assume done
