### ISSUE TITLE
TestDevstackJobSelectionSuite/TestSelectAllJobs/all_nodes_added_files,_all_nodes_ran_job is flaky

### ISSUE THREAD

**Issue by wjam** [bacalhau-project/bacalhau#1130]
TestDevstackJobSelectionSuite/TestSelectAllJobs/all_nodes_added_files,_all_nodes_ran_job will occasionally fail because it takes too long for a job to succeed

```
14:31:02.964 | DBG computenode/shard_fsm.go:412 > [QmVLJTJt] shard: 6bedd514-1e36-48e8-8305-92b83a690532:0 at state: Running transitioning from Running -> PublishingToVerifier [NodeID:QmVLJTJt]
14:31:02.967 | DBG computenode/shard_fsm.go:412 > [QmVLJTJt] shard: 6bedd514-1e36-48e8-8305-92b83a690532:0 at state: PublishingToVerifier transitioning from PublishingToVerifier -> VerifyingResults [NodeID:QmVLJTJt]
14:32:44.914 | WRN system/functionwaiter.go:35 > max attempts reached [max:1000] [name:"wait for job"]
    suite.go:161: 
        	Error Trace:	/Users/distiller/repo/pkg/test/devstack/suite.go:161
        	            				/Users/distiller/repo/pkg/test/devstack/jobselection_test.go:65
        	            				/Users/distiller/repo/pkg/test/devstack/jobselection_test.go:99
        	            				/Users/distiller/repo/pkg/test/devstack/suite.go:91
        	Error:      	Received unexpected error:
        	            	wait for job max attempts reached: 1000
        	Test:       	TestDevstackJobSelectionSuite/TestSelectAllJobs/all_nodes_added_files,_all_nodes_ran_job
```

Examples:
https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/1930/workflows/db5cf40a-ace0-4470-81dc-bf3c51189b89/jobs/12602
https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/1929/workflows/a225492f-9ebe-4b71-8638-c9464c014a6a/jobs/12574
https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/1926/workflows/7a86faf0-486a-45d1-8818-87e7f47f3b4a/jobs/12540
https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/1925/workflows/1880ef9b-9f80-4509-a3ba-ea1d3c2cacd2/jobs/12527

**Comment by aronchick** [comment]
already fixed?

**Comment by wjam** [comment]
No longer flaky
