### ISSUE TITLE
Ensure downloader can't DoS sites

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1140]

**Comment by pyropy** [comment]
Here are my notes from a meeting with @lukemarsden and @simonwo revolving this task

- See how bacalhau behaves in network with limited number of nodes when task has high concurrency rate
- Explore downloader code and determine possible attack vectors

Simple improvements (low hanging fruit):

- Dedupe list of input URls to prevent re-downloading same file for each duplicated URL 
 
Improvements:

- Implementing rate limiting 
- Cache download input to a job, cache them to IPFS and then re-use cached files for future job runs

Other possible improvements:

- Cap number of max concurrent jobs
- Cap number of max inputs to job

**Comment by panksea06** [comment]
> * Implementing rate limiting
Could you expand on how you will be implementing this? 
I am looking at a similar problem for a Station job use case and trying to think how I can do this in a decentralized fashion with DRAND, but am not sure what the current best practices are.

**Comment by pyropy** [comment]
> > * Implementing rate limiting
> >   Could you expand on how you will be implementing this?
> >   I am looking at a similar problem for a Station job use case and trying to think how I can do this in a decentralized fashion with DRAND, but am not sure what the current best practices are.

I don't know yet, It was just an idea for how we could reduce an attack surface. For downloader I guess simplest solution would be to just limit how much actual bytes could be downloaded by one job although that could be double edged sword 🤷🏻

**Comment by aronchick** [comment]
@simonwo did you address this?

**Comment by aronchick** [comment]
@wjam are you touching this as well?

**Comment by simonwo** [comment]
We haven't addressed this yet. 

I think the job to be done is implementing caching in the requestor node, which also means that we get more reproducibility properties.

**Comment by wjam** [comment]
@aronchick The only new functionality that was added when changing away from the resty library was to add tracing. If it could DoS before, it can DoS now

**Comment by pyropy** [comment]
I haven't managed to pick this one up yet due to lack of free time. Is this still worth taking care of or there have been more improvements?
