### ISSUE TITLE
M2: Theme: Observability: Improve monitoring, traceability and logging

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#1147]
ETA: 2023Q1

children:
- [x] #1149
- [ ] #1145 
- [ ] #1146 
- [x] #582
- [ ] #1148
- [x] #1152
- [x] #1153
- [x] #1699
- [x] #1773
- [x] #1774
- [x] #1792

**Comment by enricorotundo** [comment]
Re: logging & traceability. I spoke with Grafana Cloud folks some time ago and they suggested we could use the following:

* [Intro to Loki, Grafana’s logging solution - webinar](https://grafana.com/go/webinar/intro-to-loki-like-prometheus-but-for-logs/)
* [Loki documentation](https://grafana.com/docs/loki/latest/fundamentals/overview/)
* [Additional Enterprise plugins (incl. Honeycomb for tracing)](https://grafana.com/grafana/plugins/?enterprise=1)
* [Honeycomb plugin release blog](https://grafana.com/blog/2021/08/30/introducing-the-honeycomb-plugin-for-grafana/)

I'll get back to this at some point.
