### ISSUE TITLE
Enable logging to files with rotation

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#1148]
ETA: 2022Q4

Log to files with configurable log rotation (e.g. 1h). Also I recommend have two separate log files:
- `application.log.yyyy-mm-dd-hh`: for applications log in text format
- `request.log.yyyy-mm-dd-hh`: for API incoming request and response information in json format

**Comment by simonwo** [comment]
As of #956 we are also logging events to a specific file as well. So until we do something more robust with that we should probably also include those logs in the rotation.
