### ISSUE TITLE
API and Job Spec Stability

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1173]
Get to API stability for the Job, JobSpec, etc structs so that we can turn on persistence without being unable to upgrade nodes in future, and for the yaml/json versions too - IOW, change whatever we want to change before we commit to the API

ETA: 2023Q1

**Comment by wdbaruni** [comment]
https://www.notion.so/pl-strflt/Job-Schema-521ba6cdc06b4bdb940dbb151c576882?pvs=4
