### ISSUE TITLE
5 pipeline examples

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1178]
ETA: 2023Q1

**Comment by js-ts** [comment]
I think that these might be good pipeline examples

1. SD finetuning -> inference
2. Extracting A dataset from here https://slingshot.filecoin.io/ -> using that dataset analysis/training etc.
3. s3 to IPFS extract URLs from an s3 bucket -> mount those URLs and move them to IPFS

**Comment by enricorotundo** [comment]
1 example here https://docs.bacalhau.org/integration/apache-airflow or https://github.com/bacalhau-project/bacalhau/tree/main/integration/airflow#readme
