### ISSUE TITLE
Pluggable Executors v1

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1198]
**Github Project Board:** https://github.com/orgs/bacalhau-project/projects/10

Allows users to target higher level executors (i.e. not just Docker and WASM) with an interface and validation appropriate to the executor.

## Unlocked user value:

- Use of Bacalhau by users who don’t understand Docker
    - Don’t have to containerise my script at all!
- Simplified job moderation through smaller and more easily inspectable user-supplied code 
- Market for private compute providers who have access to closed-license software

## Backlog:

- Talk to gov users and understand their requirements for a Python executor, and check this is similar for researcher/scientist
- Propose a design for how pluggable executors will work in the Job Spec, including how to retain the ability for orchestrators to inspect and transform the pluggable parts
- Propose a design for how pluggable executors will work on the CLI and in SDKs, e.g. how we would implement a pluggable executor that could have an interface like `docker run`
- Propose a design for how this works with the dashboard and/or any other web UI
- Propose a design for how executors will actually be pluggable (i.e. go plugins? webassembly plugins? just config that relies on in-built executors)
- …
- Implement enough of the things to write the Python executor

## It’s done when:

- Code: enough infra to write a Python executor, and a Python executor
- Docs: how to write an executor
- Media: demo of Python executor in action

## Leads:

- Pilot: @frrist 
- Co-pilot: @simonwo 
```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2542
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2543
```

**Comment by aronchick** [comment]
?? @lukemarsden 

Docker
WASM
+??

**Comment by aronchick** [comment]
Close @simonwo @rossjones ?

**Comment by rossjones** [comment]
Still pending demo/blog and docs review

**Comment by frrist** [comment]
I am going to close this issue. We can reopen, or open a new one when this becomes a priority. Much of the work described here has been achieved by the initial pluggable executor work and the `exec` command added by Ross.
