### ISSUE TITLE
Users should be able to select/request which GPUs they want to use

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#1204]
https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1668639791256779

--gpu 1 flag doesn't allow users to specify which GPU model they want to use, this option would allow users to specify the GPU model 
eg.
--gpu-model nvidia-tesla-v100

**Comment by enricorotundo** [comment]
Is the end goal support picking a gpu based on gpu-ram and gpu-cores maybe? Or where you thinking of specific CUDA version supported by say tesla-V100 vs an older model?

**Comment by js-ts** [comment]
> Is the end goal support picking a gpu based on gpu-ram and gpu-cores maybe? Or where you thinking of specific CUDA version supported by say tesla-V100 vs an older model?

The End Goal is just choosing the GPU model of your choice rather than getting allocated a random GPU

gpu-ram and gpu-cores aren't I think the major distinguishing factors between GPUs
there are other factors like memory bandwith
https://cloud.google.com/compute/docs/gpus#general_comparison_chart

I think we should have a gpu_type flag for specifying the specific GPU model  eg
 --gpu_type  nvidia-tesla-k80

and the   --gpu  1 flag will remain for specifying the count of GPUs
