### ISSUE TITLE
M4: Theme: Bacalhau integrates with FIL+

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1225]
ETA: 2023Q1

Children:
- [ ] https://github.com/filecoin-project/bacalhau/issues/1150
- [x] #1179
- [x] https://github.com/filecoin-project/bacalhau/issues/562

**Comment by aronchick** [comment]
@binocarlos can you move this forward into the correct milestone? (whatever you think - feels like M3 at this point?)

**Comment by wesfloyd** [comment]
Is this issue duplicative of #1228 ? If so, can we consolidate them? If not, can we clarify the difference?
