### ISSUE TITLE
M1->M2: Theme: FIL+ for CPs

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1228]
ETA: 2023Q1

Children:
- [x] #1184
- [x] #1187

**Comment by wesfloyd** [comment]
Adding partners that are dependent on this capability (incentives for Compute Providers):
[Oxford Robotics](https://docs.google.com/document/d/1M22bbd9IORR9WD7JJuaOxSlHZlhLkPPRbNwKIXQF-hg/edit#bookmark=id.s82nfnauisjl)
