### ISSUE TITLE
M3: Theme: Get End User API to 1.0

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1259]
ETA: 2023Q2

Children:
- [x] #1191

**Comment by wdbaruni** [comment]
@lukemarsden the work I am currently doing is only focused on the internal APIs between Requester and Compute nodes, and not the user facing APIs. I wouldn't mind shifting things to prioritize this, specially if it is really planned for Q2. It was confusing as the title used to say M2, but was a child of an M3 milestone.
