### ISSUE TITLE
M3: Theme: Significant DX & support for more advanced jobs

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1260]
ETA: 2023Q2

Children:
- [x] #1194
- [x] #1190
- [x] #1193
- [ ] https://github.com/filecoin-project/bacalhau/issues/494
- [ ] https://github.com/filecoin-project/bacalhau/issues/528
- [ ] https://github.com/filecoin-project/bacalhau/issues/551
- [ ] https://github.com/filecoin-project/bacalhau/issues/623
- [ ] https://github.com/filecoin-project/bacalhau/issues/616
- [x] https://github.com/filecoin-project/bacalhau/issues/620

**Comment by enricorotundo** [comment]
what's `DX` in this context? UX?

**Comment by simonwo** [comment]
"Developer experience" I would guess??

**Comment by enricorotundo** [comment]
yep makes sense :)
