### ISSUE TITLE
TestDevstackPythonWASMSuite/TestPythonWasmVolumes does not pass on arm64

### ISSUE THREAD

**Issue by wjam** [bacalhau-project/bacalhau#1268]
The python_wasm executor has a hard coded docker image in it (`quay.io/bacalhau/pyodide:e4b0eb7c1d81f320f5b43fc838b0f2a5b9003c9a`). This image is not available for arm64, so the `TestDevstackPythonWASMSuite/TestPythonWasmVolumes` test cannot pass on Linux.

**Comment by wjam** [comment]
Note: the reason that the other `TestDevstackPythonWASMSuite` tests don't fail is because they are already skipped

**Comment by rossjones** [comment]
python_wasm was removed recently, and will be replaced by a python executor.
