### ISSUE TITLE
[Example] Native Bacalhau data access capabilities in FVM smart contract

### ISSUE THREAD

**Issue by it09** [bacalhau-project/bacalhau#1429]
During the FVM hackathon, there was some frustration in not being able to access data from smart contracts. We must show how we can hook that up to an FVM smart contract.

**Comment by 70nyIT** [comment]
Just found out about this issue, and I agree with @it09 . From the eyes of a builder, I do not expect to run "write" transactions within a Bacalhau job, or at least this feature is less relevant, than to be able to read data previously written on the chain. 

Example: let's say I want to generate the hash of a file, and query a smart contract to get the "category" that hash fits into, and the result "category" tells to the code how to handle that file. This can be a real use case IMHO.
