### ISSUE TITLE
`TestComputeNodeResourceLimitsSuite` is flaky on Windows

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#1445]
For example: https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/2420/workflows/d83329cb-0199-475c-8ef7-de124de60b4e/jobs/19799/steps

In the above trace, the systems seems to be waiting for shard `5fe9d1f1-4086-47ae-b451-1c3546e9eac5:0` but other than entering the EnqueingBids state, nothing else ever seems to happen for it?

All of these ❌ are this test so it's about a 50% hit rate:
![image](https://user-images.githubusercontent.com/4951176/205003630-8fdbb1ea-f434-40c5-a68c-4868c954451f.png)

**Comment by wjam** [comment]
This appears to no longer be flaky
