### ISSUE TITLE
M2: Project Frog :frog: 

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#1486]
Implement [Project Frog](https://www.notion.so/pl-strflt/Project-Frog-FVM-Stable-Diffusion-Demo-6cb6c2f5c5614394a5468a5253b6c812)

**Comment by wdbaruni** [comment]
@simonwo should we close this?

**Comment by simonwo** [comment]
@wdbaruni Let's leave one more week – we will have delivered a demo at that point.

**Comment by lukemarsden** [comment]
it's done! And even lilypad and waterlily too 😁
