### ISSUE TITLE
Need a way to force pull images

### ISSUE THREAD

**Issue by binocarlos** [bacalhau-project/bacalhau#1623]
A user uploaded an ARM image - then re-pushed an amd64 image under the same name and was getting errors - this is described in #1622 

The error was because the ARM image was already present on nodes and there is no way of forcing a re-pull...

Obviously - the user can re-tag their image to something else but perhaps we need a way of forcing a re-pull of images to get around situations where images insist on using latest?

**Comment by wjam** [comment]
Is simply appending the image SHA sufficient? People who use containers should be doing so anyway, otherwise you'll end up with cases where different machines have different image reporting to be the same image.

**Comment by simonwo** [comment]
We now have an explicit cache and invalidation of such that solves this in a round-about way.
