### ISSUE TITLE
DevEx: move logs that are for bacalhau devs under flag --verbose-bacalhau and delete docs statement

### ISSUE THREAD

**Issue by it09** [bacalhau-project/bacalhau#1648]
https://docs.bacalhau.org/getting-started/installation/#get-results contains this note that we need to fix! :

This command prints out a number of verbose logs- these are meant for Bacalhau developers. You can safely ignore them, per [issue #614](https://github.com/filecoin-project/bacalhau/issues/614))

**Comment by enricorotundo** [comment]
Hey @it09, in the current version `v0.3.19` the `get` command is no longer verbose! Can we close this one?
```zsh
Fetching results of job 'e2b4f6f0-718f-4b93-9070-68e89516781d'...
Results for job 'e2b4f6f0-718f-4b93-9070-68e89516781d' have been written to...
/tmp/job-e2b4f6f0
```
