### ISSUE TITLE
[chore] DevEx: Move containers from examples to bacalhau registry

### ISSUE THREAD

**Issue by it09** [bacalhau-project/bacalhau#1649]
- [ ] This is in the docs https://docs.bacalhau.org/getting-started/docker-workload-onboarding and needs to be fixed! :

Only about a third of examples have their containers here. The rest are under random docker hub registries (mostly Vedants) 
- [ ] update docs after fixing it

**Comment by wjam** [comment]
There also appears to be two locations that container images are being uploaded to
* https://hub.docker.com/u/bacalhauproject
* https://github.com/orgs/bacalhau-project/packages

As there are more in GHCR (GitHub Container Registry) than Docker Hub, we should migrate them all GHCR.

**Comment by enricorotundo** [comment]
hey @js-ts any chance you have availability to do this?

**Comment by js-ts** [comment]
David didn't give me access to the ghcr or the docker hub container registry so I have no access can't upload he said someone has to do it

**Comment by enricorotundo** [comment]
@js-ts Ok no worries I'll do it 
FYI @it09

**Comment by js-ts** [comment]
Thanks @enricorotundo
