### ISSUE TITLE
Migrate filecoin-project/bacalhau to bacalhau-project/bacalhau

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#1668]
This will allow us to have a project board which spans bacalhau-project/* repos, hopefully. This will solve a workflow issue that the DevEx team has (https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1673893722680149?thread_ts=1673870115.743899&cid=C02RLM3JHUY).

I checked, and once we have bacalhau repo in the bacalhau-project org, we can link the other repos with a new project there.

**Before** it's moved:
- [ ] Regenerate/find all API keys:
    > APPLE_DEVELOPER_ID_PASSWORD_B64
BACALHAU_RELEASE_TOKEN
GHCR_PAT
GH_PAGES_TOKEN
GITHUB_PR_PAT
GOOGLE_APPLICATION_DEVELOPMENT_CREDENTIALS_B64
GOOGLE_APPLICATION_PRODUCTION_CREDENTIALS_B64
GOOGLE_APPLICATION_STAGING_CREDENTIALS_B64
GOOGLE_CLOUD_STORAGE_BACALHAU_CICD_RW
HEROKU_API_KEY
HONEYCOMB_OTEL_KEY_B64
MACOS_CERTIFICATE_B64
MACOS_CERTIFICATE_PWD_B64
PERF_BOT_SSH_PRIVATE_KEY_B64
PERF_BOT_SSH_PUBLIC_KEY_B64
PRIVATE_KEY_PASSPHRASE_B64
PRIVATE_PEM_B64
PUBLIC_PEM_B64
PYPI_TOKEN
UPDATE_METADATA_CREDENTIALS_CONTENT_B64
- [x] #2008
- [x] #2009
- [ ] #2010
- [ ] Prepare drafts with fixed links in Substack blog posts, YouTube descriptions, etc

Once it's moved, we will need to probably do at least some of:
- [ ] Rename go packages 
- [ ] Reattach CircleCI
- [ ] Merge all fixes

**Comment by simonwo** [comment]
CircleCI "should" transfer our environment variables and API keys to a new organisation. There are some reports online of this not always happening cleanly. Hence why it would good to get ahead of the game with needing to find them if we lose them.

The following API keys are no longer used and can be ignored:
> APPLE_DEVELOPER_ID_PASSWORD_B64
> GOOGLE_APPLICATION_DEVELOPMENT_CREDENTIALS_B64
> GOOGLE_APPLICATION_PRODUCTION_CREDENTIALS_B64
> GOOGLE_APPLICATION_STAGING_CREDENTIALS_B64
> MACOS_CERTIFICATE_B64
> MACOS_CERTIFICATE_PWD_B64
> PERF_BOT_SSH_PRIVATE_KEY_B64
> PERF_BOT_SSH_PUBLIC_KEY_B64

**Comment by simonwo** [comment]
We did it! And it was mostly non-horrible.
