### ISSUE TITLE
Claim extra space in production disks

### ISSUE THREAD

**Issue by enricorotundo** [bacalhau-project/bacalhau#1669]
[On 2023-01-16](https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1673955228127439?thread_ts=1673952756.219969&cid=C02RLM3JHUY) *some* vm disks (either `boot`, `data`, or both - depending on the host) were bumped from 500GB -> 1000 GB. The extra space have been claimed for some hosts but not for all.

Plus, PR https://github.com/filecoin-project/bacalhau/pull/1670 increased all disks' size to 1TB but still that extra space needs to be claimed manually.

This task is about identifying the production disks with a provisioned size of 1TB (should be all) and claiming the extra ~500GB.

**Comment by lukemarsden** [comment]
yeah the way you do this is stopping everything, unmounting the disk, running `resize2fs` and mounting it again
