### ISSUE TITLE
M2: Atomic job info events

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#1740]
ETA: 2023Q1

Today requester nodes publish job events to gossipsub one at a time, which can result in events arriving out of order in other consuming requester nodes, which results in funny states such as failing to process bid event due to job not created yet, or receiving a bid after the job was marked as completed. This can easily be reproduced by running a devstack of 10 nodes.

Even with buffering of events, this issue won't be fully eliminated, and can only be reduced if the buffering window becomes large enough. 

The recommendation is to publish atomic messages that don't depend on previous ones. To be precise:
1. Publish a message when the job is created. This is optional and can make sense to let other nodes be aware of a long job that was created
1. Publish a message when the job is completed. This message will again contain the full job spec and won't depend on the previous one, and will contain detailed events of the job execution similar to what we have today

**Comment by frrist** [comment]
> 2. Publish a message when the job is completed. This message will again contain the full job spec and won't depend on the previous one, and will contain detailed events of the job execution similar to what we have today

Assuming a Job could be represented with a CID would it make sense to alternatively publish a `JobCompleted` event that references the original Job CID rather than copying the Job structure wholesale into the `JobCompleted` event?

**Comment by wdbaruni** [comment]
It makes sense. I guess it depends on how much we want to reduce the complexity of building event consumers and how they want to build their state. Publishing a CID means we need to store the job spec on a reliable IPFS node, and have the gossipsub consumers spin up an IPFS node to get the CID info. It may not scale well, but this will only be needed if they missed `JobCreated` event for some reason.

I am assuming the reason you want to do that is to save network bandwidth by not publishing the job spec twice. We can evaluate how much that will save, specially that `JobCompleted` will also have detailed events of the job orchestration that the job spec may not be the largest piece of the message payload

**Comment by aronchick** [comment]
Still needed?
