### ISSUE TITLE
Job label selectors 

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#1742]
Similar to node label selectors that were introduced by https://github.com/filecoin-project/bacalhau/pull/1737, enable job filtering by labels using the same Kubernetes [Labels and Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/)

Jobs already have `Annotations` (aka Tags), and we already support `--exclude-tag` and `--include-tag` arguments while listing jobs. The change is to rename annotations to labels, and use a single argument that expresses the selector requirements

**Comment by rossjones** [comment]
Does this require a breaking change in replacing the current labels (that are `K`) with support for key-value `K=V` instead? This would  mimic node labels and enable the mini-query language but might break existing code depending on simple tags for jobs.

**Comment by wdbaruni** [comment]
Yes, it would totally break. Instead of making a sudden breaking change, we can support both annotations and labels for a while. Then, slowly we can start phasing out annotations and encouraging everyone to switch to labels. This way, people can adapt at their own pace and we won't cause chaos overnight.

An alternative is to query our logs and dashboards and see if anyone is actually using annotations and tags

**Comment by aronchick** [comment]
Still needed?

**Comment by wdbaruni** [comment]
Done by https://github.com/bacalhau-project/bacalhau/pull/2802
