### ISSUE TITLE
Is there any way to fix the ordering of our videos in youtube?

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1744]
https://www.youtube.com/@bacalhauproject

These start with all the oldest - can we highlight special ones or something? cc @it09 @DeveloperAlly ?

**Comment by aronchick** [comment]
Also - this - https://www.youtube.com/@bacalhauproject/playlists - doesn't include DeSci Berlin, @it09's talk, DeSci Boston, etc etc

**Comment by DeveloperAlly** [comment]
Yes- but I need admin permission to do these sort of things - I'm currently only an owner.

**Comment by aronchick** [comment]
@Laurahohmann ?

**Comment by Laurahohmann** [comment]
@aronchick @DeveloperAlly  I can add you as admin, please send me your email (As you're currently not listed at all, not even as a manager)

**Comment by DeveloperAlly** [comment]
alihaire900@gmail.com or Ally@lilypad.tech

**Comment by Laurahohmann** [comment]
Invited you as an owner. (There's only owners and managers)
