### ISSUE TITLE
Allow submitting files inline using the CLI

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#1765]
We have [inline data submission](https://github.com/filecoin-project/bacalhau/pull/1628) but there is no way to use this from the CLI, only from the job spec.

We should have a flag on the CLI (like `--inputs` or `--input-urls`) that converts a file or directory into an inline spec. Use the `InlineStorage` type and `Upload` the file or directory into a spec, then include that spec in the job inputs.

**Comment by fakela** [comment]
> We have [inline data submission](https://github.com/filecoin-project/bacalhau/pull/1628) but there is no way to use this from the CLI, only from the job spec.
> 
> We should have a flag on the CLI (like `--inputs` or `--input-urls`) that converts a file or directory into an inline spec. Use the `InlineStorage` type and `Upload` the file or directory into a spec, then include that spec in the job inputs.

@simonwo please let me know when this is created so the documentation can be updated with this info

**Comment by somya-15** [comment]
Hello, @simonwo would it be alright if I give this issue a shot? I'm new to contributing to open source so apologize if I have questions but I'd be happy to help.

**Comment by simonwo** [comment]
> Hello, @simonwo would it be alright if I give this issue a shot? I'm new to contributing to open source so apologize if I have questions but I'd be happy to help.

Hi, yes of course! Please ask any and all questions you've got, and I/we are very happy to discuss ideas about how to implement. You can also join us on [Slack channel #bacalhau](https://filecoin.io/slack). 

As a place to start, I would look at how flags for the other types of storage are implemented, and think about how you'd do it for this one: https://github.com/filecoin-project/bacalhau/blob/f668fe9e9e254371b937a5c94c4b51690ef943e1/cmd/bacalhau/flags.go#L182-L201

**Comment by KalindaC-muSpace** [comment]
Is it possible for me to have a crack at this as well? If so may you please provide some instructions?

**Comment by simonwo** [comment]
Hi @somya-15, how are you getting on with this? Is there anything we can do to help? Or if you don't really have the time for it, please let us know!

**Comment by somya-15** [comment]
Hi @simonwo, yes I am working on the feature, I have few questions regarding the implementation.
1. According to the requirements the --input flag must take a path of the file/folder on the user's system. Currently, is a path added to the job spec and the files are getting uploaded to storage spec? 
So in my case,
func parsePathStorageSpec(inputPath string) (model.StorageSpec, error) { } would be a function that takes this path and uses the inline package (storage.go file) to convert the file into InlineStorage type. 
2. I am not able to get clarity regarding the requirement "Upload the file or directory into a spec". I am aware that inline package (storage.go file) has the upload method that stores the data into the returned StorageSpec. Will that be a fit for the use case here?
Thank you for your patience while I responded. As a priority, I will work on the feature.
Thanks

**Comment by simonwo** [comment]
Sorry for slowness in replying @somya-15! Great that you're still up for working on it.

1. Yes, exactly that. Basically you are doing a more general version of what is here.
https://github.com/filecoin-project/bacalhau/blob/83d90f4eed27b633d6c1549ec09f3da06c1b13f1/cmd/bacalhau/wasm_run.go#L209-L214

2.  Yes, that's exactly it. You can just pass the directory to `Upload` of the inline storage type and that will produce the desired effect.

Let me know if you have any questions!
