### ISSUE TITLE
Failed to copy...context deadline exceeded with 2GB /inputs folder on IPFS local node

### ISSUE THREAD

**Issue by jsolly** [bacalhau-project/bacalhau#1863]
## Context 
I am attempting to run [this public docker image](https://hub.docker.com/r/jsolly/cloud_mask_detect), but it errors out after 6 mins.
![image](https://user-images.githubusercontent.com/9572232/216441978-18bf965a-e31f-44be-b64b-d8b452ed48d9.png)

The job runs a cloud-masking Python script that reads from files inside a `/inputs` folder.

## Steps to Reproduce 
```shell
$ bacalhau docker run -v QmSSx9zK9keTwJccmnB9P4Ss9t7fjcmYU1Q7H1BgMv3xdS:/project/inputs \
        jsolly/cloud_mask_detect
```

```shell
$ bacalhau describe <JOB_ID>
...
State: Error
            Status: 'failed to copy /project/inputs to volume: failed to write to
              ''/tmp/bacalhau-ipfs1053164276/QmSSx9zK9keTwJccmnB9P4Ss9t7fjcmYU1Q7H1BgMv3xdS'':
              context deadline exceeded'
            VerificationResult: {}
...
```

## Thoughts
If I was running the container locally, it would look like this:
```
$ docker run --rm -v $(pwd)/inputs:/project/inputs cloud_mask_detect
```

The CID, `QmSSx9zK9keTwJccmnB9P4Ss9t7fjcmYU1Q7H1BgMv3xdS` refers to an input folder I have added to IPFS and pinned to my local node via IPFS Desktop GUI:
![image](https://user-images.githubusercontent.com/9572232/216442508-cfc0349e-9f23-4bd4-9834-64984e99554f.png)

I have tested much smaller files with no issue, so there might be an issue with the data being fetched from my local node? If you think this is the case, do you suggest a better way to expose my `/inputs` folder to Bacalhau? I plan to put this data on Filecoin, but I am now testing things on IPFS to see if they will work.

I tried Pinata pinning service, but my upload was too large for the free plan.

I found these two existing issues with the same error:
https://github.com/filecoin-project/bacalhau/issues/526
https://github.com/filecoin-project/bacalhau/issues/1592

## Environment
```shell
$ bacalhau version
Client Version: v0.3.18
Server Version: v0.3.18
```

**Comment by lukemarsden** [comment]
thank you for writing this up! We are looking into it

**Comment by wesfloyd** [comment]
@jsolly could you share which service you used to pin the input file to IPFS?

**Comment by jsolly** [comment]
> @jsolly could you share which service you used to pin the input file to IPFS?

I am using the IPFS desktop app. I simply set the pinning there:
![image](https://user-images.githubusercontent.com/9572232/218930746-f085b6b5-eb9b-4812-b7a0-837e96ae3866.png)

It works with very small datasets (like a .txt file with the string 'Hello World!') but I was seeing timeouts if I tried to run a Bacalhau job with 2GB of data pinned this way.

I am open to adding/pinning data to IPFS another way to improve thoroughput.

**Comment by wesfloyd** [comment]
While testing the download from my laptop, I'm seeing the download pause at 19% 440MiB. Unfortunately, I'm not able to download the file.

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/260568/219094664-5f05cb12-d5f1-4054-aab0-cf8ce2d93bb9.png">

Part of these errors could be due to the bandwidth limitations of your desktop IPFS instance. Typically we work with 3rd party services that specialize in pinning ([Estuary](https://docs.estuary.tech/), Web3.storage, Pinata.cloud, etc.).

@jsolly would you mind attempting to upload the file to either of these services?

**Comment by jsolly** [comment]
I've uploaded files to web3.storage, and I will test again once [this issue](https://github.com/filecoin-project/bacalhau/issues/2033) is resolved.

**Comment by jsolly** [comment]
You can certainly try it! I would be surprised if that's the issue because I have been able to pass single files into Bacalhau jobs like this:
```shell
$ bacalhau docker run -v QmeeLUVdiSTTKQqhWqsffYDtNvvvcTfJdotkNyi1KDEJtQ:/project/inputs/hello.txt jsolly/hello_world
>    stdout: |+
            Hello, world!
```
And when running it locally it's:
```shell
$ docker run --rm -v $(pwd)/inputs/hello.txt:/project/inputs/hello.txt jsolly/hello_world
```
I am passing in a text file, hello.txt and printing the contents. No folder is being passed in as input.
https://ipfs.io/ipfs/QmeeLUVdiSTTKQqhWqsffYDtNvvvcTfJdotkNyi1KDEJtQ

You can go ahead and try that out using [hello_world docker image](https://hub.docker.com/repository/docker/jsolly/hello_world/general).

See [this folder](https://github.com/easierdata/cloud_mask_detect/tree/main/testing/repo2) for more context.
