### ISSUE TITLE
Docs Update: Add SEO to each page

### ISSUE THREAD

**Issue by it09** [bacalhau-project/bacalhau#1883]

**Comment by yenyrubiano** [comment]
@it09 I did a site audit to review SEO.
Docusaurus by default installs plugins that help with SEO. I checked the sitemap and it looks great. It is also already submitted to Google. Overall, the site is good. It just needs more content and diagrams (which I will help create).

I only added Alt Tags for images. Added some H1s to improve page visibility, and added a meta tag in its config file. Please review the pull request here: https://github.com/bacalhau-project/docs.bacalhau.org/pull/197

**Comment by fakela** [comment]
> @it09 I did a site audit to review SEO. Docusaurus by default installs plugins that help with SEO. I checked the sitemap and it looks great. It is also already submitted to Google. Overall, the site is good. It just needs more content and diagrams (which I will help create).
> 
> I only added Alt Tags for images. Added some H1s to improve page visibility, and added a meta tag in its config file. Please review the pull request here: [bacalhau-project/docs.bacalhau.org#197](https://github.com/bacalhau-project/docs.bacalhau.org/pull/197)

@yenyrubiano thanks for checking it, i submitted the sitemap to Google. Thank for the additional changes. I'll review them now
