### ISSUE TITLE
Go SDK to make it easier for Go applications to interact with Bacalhau

### ISSUE THREAD

**Issue by wjam** [bacalhau-project/bacalhau#1916]
If a user wants to write a Go application which sends jobs to Bacalhau, the only choice at the moment is to depend on the entirety of Bacalhau. This can lead situations where a change in a dependency for an _executor_ can lead to problems for a a client. An example of this is with the canary lambda which is [locked at Go 1.18](https://github.com/aws/aws-codebuild-docker-images/issues/598) but bumping the wazero dependency, which is only used by an executor, meant that the code required Go 1.19.

We should introduce an `api/` module into the code base which contains:
* `pkg/model`
* Automatically producing the relevant keys and signing of the job requests
* Some parts of `pkg/job` - a lot should either be removed as it's far too trivial or should be moved as it's only used in a single location. Model validation should move to `model`
* Support for tracing calls - users should be able to see spans for calls to Bacalhau in their traces
* Possibly `pkg/downloader` - to make it easier to download files after running  a job, although this may have to be divorced from `pkg/ipfs` to stop a large number of packages getting pulled in
* It's own `go.{mod,sum}` file, so that an external tool can depend on _just_ the SDK

Future tasks for the SDK could include:
* Testing that the SDK supports a list of supported Go versions
* Break changes to the SDK is spotted before being merged

**Comment by enricorotundo** [comment]
any chance we can auto-generate this via swagger?

**Comment by wjam** [comment]
If we created a Go SDK, we should use the SDK ourselves - eat our own dog food. The `swagger.json` file is generated from parsing the current Go files. If we move to use an SDK generated from the Swagger docs, then we'd need another way to manage the `swagger.json` file.

It should be noted that generating the `swagger.json` directly from the servers models can make it harder to spot breaking changes, as small tweaks to the Go files are automatically pushed into the Swagger definition.

There's talk about removing the need to sign job submissions, which should simplify the generation of SDKs
