### ISSUE TITLE
Report and Record which nodes were deemed to have successfully completed a verified job

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#196]
ETA: 2023Q3

Initially, the reputation system would just report & record which nodes were deemed by clients and servers to have been good actors and initially no automated actions would be taken on the reputation system: it would be made publicly available like the Filecoin reputation system at https://filrep.io/

**Comment by aronchick** [comment]
cc @wdbaruni i think you may touch this with your current work?
