### ISSUE TITLE
Automate the checking/announcement of API changes

### ISSUE THREAD

**Issue by philwinder** [bacalhau-project/bacalhau#2019]
People are starting to depend on our API. Even though we're not stable yet, we should have a way of announcing or at least identifying public API changes. For example: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1677054902073849

I think:
* [ ] Some way of automatically detecting changes
* [ ] Some way of adding this information to the release notes of a release.

Related to #1199 and #1259

**Comment by aronchick** [comment]
I think the best thing to do would be to have a test - let’s do something that forces use of jq and yq - then in the test, have a note that says if you need to change this test, it’s a breaking change, and we need to notify people
