### ISSUE TITLE
Reinstate libp2p reciver-manager metrics

### ISSUE THREAD

**Issue by philwinder** [bacalhau-project/bacalhau#2059]
I had to remove the current metrics from libp2p receiver-manager because they stopped using opencensus and moved to prometheus. But we're using open telemetry and there was no obvious way to convert their prom metrics into our otel metrics (oltp).

This is their change: https://github.com/libp2p/go-libp2p/commit/97af39a2eda2d952621d359bab304702c493848d#diff-b1c5b5f77c1ee14eae450b69d05cd9f422859da177458a02783ee93ba7f01312L29

This is the code that I commented out: https://github.com/bacalhau-project/bacalhau/blob/main/pkg/libp2p/rcmgr/defaults.go#L50

The task is to reinstate the metrics and double check they appear in the otel outputs again. Note that two bac nodes need to connect to produce these metrics and they are prefixed with `rcmgr_`. 

So to test, you need a monitoring setup (see the PR in the docs) to read the otel stream and you need two bacalhau nodes so they start communicating over libp2p.

**Comment by wjam** [comment]
After looking through the OTEL code, it appears that it doesn't support the ability to ingest Prometheus metrics without running the agent and scraping a proper Prometheus endpoint. This appears to be a ticket about enabling receiving Prometheus metrics _without_ running the endpoint but has yet to be implemented - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4973

The quickest and simplest solution is to not use the standard libp2p `StatsTraceReporter` and implement a custom `rcmgr.TraceReporter` which can talk straight to OTEL.

**Comment by philwinder** [comment]
Thanks Will. Asking the question "do we really need these metrics" in slack.
