### ISSUE TITLE
Improve signing of requests

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2114]
Currently when the client signs a request to send to the Requester API, it involves putting the user's public key and client id and signature into the payload that is sent.  This means that each http handler (currently submit and cancel) have substantial duplicated code designed to verify the signature and extract the real payload from the full payload.

We should investigate whether it is feasible/sensible/etc to include the signature and key in the Authorization header of the request and have the signature be based on path + host + payload (raw bytes).  This approach would mean that we no longer need to include the signature verification in the http handler (where even with recent changes to make it generic still requires knowledge of the request/response types). We could then write some middleware to handle requests that need signing so that the public api looked more like 

```go
func requireSignature(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Check signature and validate it against the relevant headers/payload etc
		h.ServeHTTP(w, r) // call wrapped handler
	})	
}

func (s *RequesterAPIServer) RegisterAllHandlers() error {
	handlerConfigs := []publicapi.HandlerConfig{
		{URI: "/" + APIPrefix + "list", Handler: http.HandlerFunc(s.list)},
		// Others removed 
		{URI: "/" + APIPrefix + "submit", Handler: requireSignature(http.HandlerFunc(s.submit))},
		{URI: "/" + APIPrefix + "cancel", Handler: requireSignature(http.HandlerFunc(s.cancel))},
	}
```

This would be a breaking change for consumers of the APIs.

**Comment by rossjones** [comment]
The most likely viable standard to use is still in draft (https://datatracker.ietf.org/doc/draft-ietf-httpbis-message-signatures/), but should be ratified soon.

**Comment by wdbaruni** [comment]
no longer an issue with v2 APIs
