### ISSUE TITLE
macOS resource class deprecated in CircleCI

### ISSUE THREAD

**Issue by wjam** [bacalhau-project/bacalhau#2142]
[CircleCI has announced that they have deprecated and will be removing the resource class we currently use to run for macOS tests](https://discuss.circleci.com/t/macos-resource-deprecation-update/46891).

We should migrate to one of the new resource classes, but note that the _larger_ type is an M1 and so should be building/testing as `arm64`.

**Comment by rossjones** [comment]
We recently switched OSX testing/building to ARM mac's as Circle are also retiring AMD64 macs in October.
