### ISSUE TITLE
Compute Over Encrypted Data

### ISSUE THREAD

**Issue by wesfloyd** [bacalhau-project/bacalhau#2166]
Starting this thread to track partners' requests for Compute Over Encrypted datasets.

Partners who require this feature:

- [Stryde Further](https://docs.google.com/document/d/1EL5gOBrCBAvyzqOz4RqM3rtWJrZJ52HgbenjBvBvQ3A/edit?usp=sharing) "Data encryption is a critical issue before we can get started"
- [Enterprise FIL+ Clients](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=+is%3Aissue+label%3AEfil%2B+) - all EFIL+ clients' datasets are encrypted by default.

**Comment by profitgrowinginnovator** [comment]
- 0011.ai "send encrypted data from Jupyter Lab extension to Bacalhau node and only allow assigned node to decrypt"

**Comment by profitgrowinginnovator** [comment]
User story:
A Bacalhau user should be able to either pass a secret key to the Bacalhau node which gets the compute workload assigned to use to decrypt data sources in the node or alternatively receive the [a single use] public key for this Bacalhau node and be able to decrypt the same datasources via the [single use] private key of the Bacalhau node. A script passed to the Bacalhau node can now use the decryption key to decrypt any data stored in /inputs.
