### ISSUE TITLE
Pulling Docker Container updates to client v0.3.24 (too new)

### ISSUE THREAD

**Issue by walkerlj0** [bacalhau-project/bacalhau#2168]
Using the command ` docker pull ghcr.io/bacalhau-project/bacalhau:latest` pulls a container with a 'too new' version of Bacalhau (client is newser than the server version)

```
➜  ~ docker pull ghcr.io/bacalhau-project/bacalhau:latest
latest: Pulling from bacalhau-project/bacalhau
Digest: sha256:81ab93d643d165ad45375765a420e757fc446e094e4cc144f977dd012c2137aa
Status: Image is up to date for ghcr.io/bacalhau-project/bacalhau:latest
ghcr.io/bacalhau-project/bacalhau:latest
➜  ~ docker run -it ghcr.io/bacalhau-project/bacalhau:latest version
Client Version: v0.3.24-build-testing-01
Server Version: v0.3.23
```

**Comment by lukemarsden** [comment]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/264658/225056750-f8cdfe1b-6940-431d-9e97-197a08a33ba7.png">

**Comment by lukemarsden** [comment]
tagged as `good first issue` to add the regex filter to CircleCI config to only push to `:latest` for tags of the exact form `v[number].[number].[number]`

**Comment by boneyard93501** [comment]
still seems to be an issue:

``
bacalhau installed into /usr/local/bin successfully.
Client Version: v0.3.25
Server Version: v0.3.25
```

```
bacalhau docker run ubuntu echo Hello World
version validation failed: the server version v0.3.25 is newer than client version v0.3.24-build-testing-01, please upgrade your client with the following command:
```
