### ISSUE TITLE
simplify defaults further and improve docs for private clusters

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#2176]
- [x] #2197

Currently, you have to type:
```
bacalhau serve --private-internal-ipfs --node-type compute,requester --peer none
```
and on another node, run the command the above outputs. This works. However, this should be spelled:

```
bacalhau serve
````

The current `bacalhau serve` behavior of connecting to the public bacalhau network should become
```
bacalhau serve --peer bootstrap.production.bacalhau.org
```

- [x] #2198

* `curl -sL https://get.bacalhau.org/install.sh | bash` everywhere
* Run `bacalhau serve`
* Copy and paste the command it outputs to some other nodes on your LAN
* Copy and paste the env vars it outputs to a client machine, and run `bacalhau docker run ubuntu echo hello`
* (optional: set up systemd units to make bacalhau daemons permanent)
* Boom :tada: 

- [x] #2199

- [x] #2200

**Comment by enricorotundo** [comment]
> Look into whether the ipfs daemon started by --private-internal-ipfs persists its data and survives a reboot. If it doesn't, consider making it persist its identity and state into ~/.bacalhau or something
It does not.
1. started `bacalhau serve --private-internal-ipfs ...`
2. launched a sample job, picked its output CID
3. `ipfs --api /ip4/0.0.0.0/tcp/65056 get QmSQo5XATeCzNoCko2wojb3d85RfzrXnc5nEyAoy8gPAMi` ✅ 
4. re-started bac
5. `ipfs --api /ip4/0.0.0.0/tcp/49488 get QmSQo5XATeCzNoCko2wojb3d85RfzrXnc5nEyAoy8gPAMi` ❌ (hangs)

**Comment by enricorotundo** [comment]
WIP PR: https://github.com/bacalhau-project/bacalhau/pull/2196
