### ISSUE TITLE
Insulated Jobs:  new paradigm where compute is securely moved to data, audited & approved

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#2182]
ETA: 2023-05-09

Description: Organizations waste years and millions trying to centralize data across multiple departments so they can query over it. What if you turned that paradigm on its head and implemented federated compute, where you ship the code to where the data already is, with appropriate controls in place so that orgs can allow compute over their data in a controlled way? Insulated Jobs achieves this by building an approval and audit layer on top of Bacalhau.

Children:
- [x] #1961 
- [ ] #1962 
- [x] #1963
- [x] #2288 
- [x] #2289
- [x] #2290 
- [ ] #2291 
- [x] #2292 
- [x] #2293

**Comment by simonwo** [comment]
We've reached a 1.0. Features not yet done can be done for next release.
