### ISSUE TITLE
Excellent Documentation: ensure excellent DX through accurate & compelling docs and examples

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#2189]
ETA: 2023-05-09

Description: As we rush towards a May 9 launch, our public documentation and examples all need to be up-to-date, crystal clear, tested and precise. New use cases such as Insulated Jobs need solutions architectures and runnable examples for how they can be deployed as OSS within large companies and organizations.

Children:
- [x] https://github.com/bacalhau-project/bacalhau/issues/1314

**Comment by fakela** [comment]
> ETA: 2023-05-09
> 
> Children:
> 
> * [ ]  <Please link to GitHub issues describing the actual work here!>

https://github.com/bacalhau-project/bacalhau/issues/1314 here it is

**Comment by fakela** [comment]
Do i copy

> > ETA: 2023-05-09
> > Children:
> > 
> > * [ ]   <Please link to GitHub issues describing the actual work here!>
> 
> #1314 here it is

Do i copy and paste all the links here

**Comment by lukemarsden** [comment]
Just edit the issue description to add the issues to the list please
