### ISSUE TITLE
Streaming Logs: attach to live stream for a job to observe/debug ongoing long-running job progress

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#2190]
ETA: 2023-05-09

Description: Currently if you run a Bacalhau job that takes an hour, the only way to see what it outputted after 1 minute is to wait the full hour and then look at the result in the describe output or in the results CID. This project is to extend the libp2p bprotocol to support streaming logs back from jobs as they’re running, much like kubectl logs -f allows you to on a remote Kubernetes cluster. This will dramatically improve the Developer Experience of someone running jobs on Bacalhau by giving them more immediate feedback and the ability to track the progress of long-running jobs by streaming their live stdout/err.

Children:
- [x] #448 
- [x] #2194 
- [ ] #2222

**Comment by rossjones** [comment]
This ticket is done, #2222 can be part of logs v2 and standalone.
