### ISSUE TITLE
Station Integration: enable Bacalhau compute nodes in Station to expand public network

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#2191]
ETA: 2023-05-09

Description: Station is a project to allow users to run Protocol Labs projects like IPFS and Filecoin on their own computers. This project is to also add Bacalhau to that list! This should result in an influx of compute nodes onto the public Bacalhau network. The Station team have published a spec which we will conform to in order to allow Bacalhau to be a plugin to their existing system.

Children:
- [x] #1780 
- [x] #1558 
- [x] #1779 
- [x] #1768 
- [x] #1767

**Comment by simonwo** [comment]
[Station now includes Bacalhau support](https://filecoinproject.slack.com/archives/C046BBT15FG/p1683014821351579) that is confirmed working! As ever, there are some things to iterate on going forward, but I think we can declare success on this intergration.
