### ISSUE TITLE
Proper cleanup of resources/folders during shutdown and startup

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#2202]
staging canaries were failing because one of the hosts ran out of disk space. I checked and it was a folder under `/tmp/bacalhau-results1643036303` that was taking the whole space. We need to make sure we are properly cleaning all of our resources during both shutdown, and startup in case of ungraceful shutdown

* [x] Remove results from local disk once publisher
* [x] Cleaning up of inputs as the fix is only cleaning outputs
* [ ] Cleaning up during startup to handle ungraceful shutdowns
* [ ] Ensure job failures/cancellations are cleaned up
* [ ] Cleanup after result rejection by requester node
* [ ] Cleanup when no response from requester node to approve or reject a proposal (This requires implementing timeouts in the compute nodes on how long they should wait, which we don't have today. Something similar to [Requester's Housekeeping](https://github.com/bacalhau-project/bacalhau/blob/main/pkg/requester/housekeeping.go))

**Comment by wdbaruni** [comment]
Thanks Ross for picking this up. Though there are still areas where we don't cleanup the resources properly, including:
- Job failure or cancellation
- Result rejection by requester node
- No response from requester node to approve or reject the proposal. Though this requires implementing timeouts in the compute nodes on how long they should wait, which we don't have today. Something similar to [Requester's Housekeeping](https://github.com/bacalhau-project/bacalhau/blob/main/pkg/requester/housekeeping.go)
- Cleaning up during startup to handle ungraceful shutdowns 
- Lastly cleaning up of inputs as the fix is only cleaning outputs

**Comment by rossjones** [comment]
I've added the bullet points remaining to the initial ticket descriptions as a TODO checklist, hope that's okay.
