### ISSUE TITLE
/outputs directory empty when running cloud segmentation script

### ISSUE THREAD

**Issue by jsolly** [bacalhau-project/bacalhau#2227]
## Context 
I have a [docker image](https://hub.docker.com/repository/docker/jsolly/segmentation_testbed/general) that runs a cloud segmentation python script on an input imagery mosaic.

When running locally, 5 files are generated in a folder called `/outputs`

Unfortunately, when running the job on Bacalhau, the `/outputs` directory is empty.

## Steps to Reproduce 
```shell
$ bacalhau docker run -v QmTYadG6K4LocouLu6wFzeMXNB5z8ikdpwuGqpdZNxp5qR:/project/inputs/LC08_L1TP_001028_20220615_20220627_02_T1_mosaic.tif jsolly/segmentation_testbed:latest
$ bacalhau describe <JOB_ID> # e.g. bacalhau describe 6931839e-51f6-4a62-8252-605753827be9
# Note the CID shown in the output of `bacalhau describe` for me it was:
`QmcY4WFeknSWgkurAv7rA8XnUDthfPK1vUCYVd7ecG9tpU`
```
Fetch that output either through a CLI or a gateway such as 
https://ipfs.io/ipfs/QmcY4WFeknSWgkurAv7rA8XnUDthfPK1vUCYVd7ecG9tpU/

You will see that `/outputs` is empty. I do see in the [stdout](https://ipfs.io/ipfs/QmcY4WFeknSWgkurAv7rA8XnUDthfPK1vUCYVd7ecG9tpU/stdout) that the script output the expected messages related to segmenting the image
> Satellite scene size is (xs,ys)=(7931,8041) with number of bands is 3
(8041, 7931, 3)
0.0 1.0
Segmentation is under way...
Segmentation is finished in 214.32889485359192 sec...
SLIC number of segments: 1298233
max segment is 1298233
(237585.0, 30.0, 0, 5219115.0, 0, -30.0)

If the script put out those messages, I would expect the output files to be generated.

## Expected Behavior 
I'll show the workflow for running the docker image locally. Make sure to use the full path to the file with $PWD when passing the file in with the -v command.

1 - Download the imagery mosaic, `QmTYadG6K4LocouLu6wFzeMXNB5z8ikdpwuGqpdZNxp5qR` to your local machine
2 - Run the public Docker image (same one Bacalhau is using) and pass that file in as input.
```shell
$ docker run -v $PWD/LC08_L1TP_001028_20220615_20220627_02_T1_moz.tif:/project/inputs/LC08_L1TP_001028_20220615_20220627_02_T1_mosaic.tif jsolly/segmentation_testbed
# Make sure the container is running and then go into it
$ docker exec -it <CONTAINER_ID> /bin/bash
$ ls ../outputs
LC08_L1TP_001028_20220615_20220627_02_T1_mosaic.tif_ks1_md7_r0.75_scale1_labtrue.dbf
LC08_L1TP_001028_20220615_20220627_02_T1_mosaic.tif_ks1_md7_r0.75_scale1_labtrue.prj
LC08_L1TP_001028_20220615_20220627_02_T1_mosaic.tif_ks1_md7_r0.75_scale1_labtrue.shp
LC08_L1TP_001028_20220615_20220627_02_T1_mosaic.tif_ks1_md7_r0.75_scale1_labtrue.shx
LC08_L1TP_001028_20220615_20220627_02_T1_mosaic.tif_ks1_md7_r0.75_scale1_labtrue.tif
```
## Thoughts
~The output directory is about 430MB, so there could be a size limit we are running into. Is there a hard limit to how large the output directory can be?~

I don't think that's the case. I recorded a [15 min video](https://app.screencast.com/O8zTDp2qEUGkM) about another workflow I am trying to accomplish. If you navigate to the end of the video, you can see that Bacalhau is not including a small plot in the outputs folder. In the video example, the image is only ~200kb

## Environment
* Version of API*
Client Version: v0.3.25
Server Version: v0.3.25

cc @wesfloyd @TaylorOshan

**Comment by wesfloyd** [comment]
There appears to be an issue on segmentation_testbed_2.py Line# 175 where the outputs folder is hardcoded to be in a parent directory. This could be throwing off the output writes when the job is ran on Bacalhau.

Sharing a screenshot of how the outputs directory should look upon a successful run:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/260568/227607704-0d078b6c-4dca-4dc7-8846-9df7a7dff9fc.png">

Working on repackaging the docker build and local test now.

On a related note, @jsolly you may also want to rebuild your [jsolly/segmentation_...](https://hub.docker.com/r/jsolly/segmentation_testbed/tags) docker image after last week's [changes to the Dockerfile](https://github.com/easierdata/cloud_mask_detect/blob/036053b23d588625df0aa5f9ce7e757d4a4fee9c/segmentation_testbed/Dockerfile#L10) (specifically adding mkdir /project/outputs)?

**Comment by wesfloyd** [comment]
Good news - [this latest command](bacalhau docker run -v QmTYadG6K4LocouLu6wFzeMXNB5z8ikdpwuGqpdZNxp5qR:/project/inputs/LC08_L1TP_0018_20220615_20220627_02_T1_mosaic.tif -o outputs2:/project/outputs/ --id-only wesfloyd/segmentation_testbed:latest) works!

Sharing a PR with the related changes. I think there were conflicts between the scripts output file mapping, the docker file's output mapping, and the bacalhau runtime's output file mapping OR I simply wasn't using the "-o" flag when I was running the Bacalhau command most recently and the outputs were not being captured correctly. By default, Bacalhau captures all the files written to /outputs but not /project/outputs .

**Comment by jsolly** [comment]
Nice job! I think it makes sense to just refactor the script not to use/project and simply allow it to write to the directory where Bacalhau expects it. That was what I was trying to accomplish in the first place.

Closing this one now.
