### ISSUE TITLE
Add Mounting local directories functionalities to the CLI

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#2279]
`bacalhau docker run -i file://<-path-to-the-file-> ubuntu ls`

will mount the local directory at /inputs

**Comment by rossjones** [comment]
This now works, but only if the path you want to add is part of the `--allow-listed-local-paths` flag on the compute nodes.

**Comment by rossjones** [comment]
This is about mounting client-side files inside the remote container that bacalhau creates, not about mounting remote files in remote containers.

**Comment by wdbaruni** [comment]
if this is about running jobs on local data on the client side, then we can explore adding the data as `inline-data` to the job spec, which is very limited and not scalable, or we can explore a path where the client would ask the requester for a pre-signed URL, upload the data, and then submit a job with that data
