### ISSUE TITLE
Requester node specifies ExecutionID/ComputeReference when createing an ExecutionState on Compute node(s)

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2296]
Motivation for this changes stems from the fact that the JobStore of the requester doesn't have a "complete" executionID when it creates an execution state. When the ExecutionState is created on the Requester node here:
https://github.com/bacalhau-project/bacalhau/blob/69f9e65eb157a5b2416bd0d1b3550022a5b9de7d/pkg/requester/scheduler.go#L140-L148
The ComputeReference is empty meaning the calculated ExecutionID used here:
https://github.com/bacalhau-project/bacalhau/blob/69f9e65eb157a5b2416bd0d1b3550022a5b9de7d/pkg/jobstore/inmemory/inmemory.go#L277 isn't a complete execution ID.

Once a bid is responded to, we must reference an ExecutionState by constructing another "incomplete" executionID to update its state:
https://github.com/bacalhau-project/bacalhau/blob/69f9e65eb157a5b2416bd0d1b3550022a5b9de7d/pkg/requester/scheduler.go#L373-L391
Internally to the JobStore we mutate the ExecutionState to include a ComputeReference:
https://github.com/bacalhau-project/bacalhau/blob/69f9e65eb157a5b2416bd0d1b3550022a5b9de7d/pkg/jobstore/inmemory/inmemory.go#L338
So that subsequent `UpdateExecution` calls can reference the ExecutionState using a "full" executionID: one that includes the `ComputeReference` in the output.

This flow makes it hard to reason about the various states an `ExecutionState` can be in since the ID we use to reference an Execution depends on what stage a request is in between a requester and compute node.

I'd like to simply this by ensuring we have a "complete" executionID at the time an execution is created in the JobStore of a Requester node. We can achieve this by having the Requester node dictate the ExecutionID of an Execution when it sends a bid to a compute node. The compute node may use its own internally generated ID to track the execution locally, but should use the executionID created by the Requester node when communicating with it over the bprotocol.

**Comment by aronchick** [comment]
still needed?

**Comment by wdbaruni** [comment]
I believe this is already done
