### ISSUE TITLE
CLI improvements for production network

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#230]
* [x] Sort the list and sub-lists in `bacalhau list` so most recent jobs are showed last
* [x] Show at most 10 jobs, with a flag to show all
* [x] Allow user to list a specific job
   * [x] Update https://docs.bacalhau.org/getting-started/installation to use the "list specific job" CLI feature rather than the ugly `grep` hack it has right now (in two places)
* [x] Only show the last N jobs
* [ ] Only show jobs you submitted (?)

**Comment by aronchick** [comment]
shouldn't most recent jobs be at the top? regardless i have the flags done

**Comment by aronchick** [comment]
I think i'm done - except the last one (we don't have the concept of user)

**Comment by aronchick** [comment]
FWIW, did a PR - https://github.com/filecoin-project/bacalhau/pull/234.

I'm NEARLY sure there's some leaking issue that's causing the tests to fail. They fail non-deterministically. The stuff seems to work against live data though.

**Comment by Bubblyworld** [comment]
The leakage issue is fixed, sorry about that. IPFS daemons are properly cleaned up now 🙌 and cleanup routines can be registered on the `CleanupManager` that's passed around to nodes now.
