### ISSUE TITLE
Do you have any kind of tooling around how to manage those hashes in the network

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2316]
We need an internal data catalog
https://www.youtube.com/live/AO8oJUijINU?feature=share&t=371

**Comment by davidgasquez** [comment]
I think something similar to https://github.com/bacalhau-project/bacalhau/issues/2318#issuecomment-1504849965 could work.

The hashes are there, a Bacalhau job could crawl it every day/hour (GH Action/Cron/..) and publish it back to IPFS and somewhere else like GitHub. Not fully decentralized but it allows progressive decentralization when needed!

PS: Would be awesome to visualize the Bacalhau DAG over time, if that's not yet a thing.

**Comment by wdbaruni** [comment]
@aronchick what is this about?

**Comment by wdbaruni** [comment]
closing in favour of this unified https://github.com/bacalhau-project/bacalhau/issues/4187
