### ISSUE TITLE
Can I build a catalog of all data already available in the network? Or a list of shares available? (e.g. could I query a network to get all mounts available and use them as a scheduling target?)

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2318]

**Comment by davidgasquez** [comment]
I've been using a silly bash command to list my own inputs/outputs. Can be adapted to all jobs like this:

### List all Inputs
```bash
bacalhau list --all -n 100 --output json | jq '.[].Job.Spec.inputs[]'
```

### List the output CIDs
```bash
bacalhau list --all -n 100 --output json | jq '.[].State.Executions[].PublishedResults.CID' -r | sort -u
```

For my use case (keeping track of the versions of a dataset), I was thinking to make it a Bacalhau job, put it back to IPFS as a CSV and add a pointer in GitHub to the last one.
