### ISSUE TITLE
Can I run against public datasets?

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2319]
We need a website for the public bacalhau network that lists existing big and useful datasets already available
Also example workloads that run against it
OpenDataCommunity working on this

https://www.youtube.com/live/AO8oJUijINU?feature=share&t=448

**Comment by davidgasquez** [comment]
Yes! :100:

Not sure if OpenDataCommunity is working on this front right now @aronchick. I have some ideas and proposed them though.

[I've been exploring doing something like this](https://github.com/davidgasquez/packaging-open-data/blob/main/docs/FAQ.md#how-would-you-make-datasets-immutable) and I think there are potential solutions that work and have some positive externalities. 

The TL;DR is that Bacalhau could adopt an already [stablished and minimal standard](https://specs.frictionlessdata.io/) for datasets and, as a community, wrap and surface the existing datasets. 

The tooling is mostly there, and with things like Amplify, it might be close to fully automated. At the end, is just putting a bunch of CIDs into a JSON/YAML with some extra metadata. The existing tooling will know how to read that and transform it to anything (`package.to_pandas()`). These files can [live anywhere (GitHub, IPFS) and can be agregated into catalogs if needed](https://github.com/davidgasquez/packaging-open-data/blob/main/notebooks/quickstart.ipynb).

In an ideal world, `bacalhau` could understand about these packages and accept datapackages URIs as inputs so all the multiple CIDs/S3 files/... are hidden.
