### ISSUE TITLE
Need a Linear Regression on DuckDB example

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2332]
https://github.com/dwreeves/dbt_linreg

**Comment by davidgasquez** [comment]
In case it helps, you can run [Linear Regression on DuckDB with Datadex](https://github.com/davidgasquez/datadex/blob/main/dbt/models/energy_linreg_model.sql) (dbt + DuckDB)! 

![1681308437](https://user-images.githubusercontent.com/1682202/231484160-076a45ec-254e-4791-8e61-d14d9c46149a.png)

The catch for now is that the current sources I'm reading in Datadex [are remote sources](https://github.com/davidgasquez/datadex/blob/main/dbt/models/sources.yml). You could read from local files or even [native IPFS hashes](https://github.com/jwills/dbt-duckdb/blob/5de6b5813098e8655eeda8d98d325c00fd834207/README.md?plain=1#L78-L84) very easily though. That said, I'm thinking how to best stitch these two worlds as it'll unlock a very powerful combo!
