### ISSUE TITLE
Support percentage values in CPU/memory limit flags

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2367]
We accept command line flags to limit the resources used per job and used by all jobs. This is useful for users who want to run Bacalhau nodes on shared machines which are also providing other services.

However, these flags take absolute values only (eg 1 CPU core, 2Gb RAM). For users (like Starion) who are deploying over a wide breadth of different machines, this is problematic because on some clients 2Gb RAM might be the full amount and on others it might be a too small amount. 

What would be better was if we could supply percentage values and have Bacalhau work out the correct absolute values (it already knows how to read the available cores and RAM). Then Station could just say “use no more than 50% of RAM” and be confident that this scales to all machine types.

Make the existing CLI flags able to accept values that end in a percentage % symbol and interpret these as percentage of absolute value when calculating resource limits.

**Comment by wdbaruni** [comment]
This is suggested in https://www.notion.so/expanso/Rethinking-Configuration-435fbe87419148b4bbc5119d413786eb?pvs=4#fdc6de7c00364de1bb81b325686e6e66 and tracked by #4014
