### ISSUE TITLE
Need a proxy registry for docker registry?

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2368]
We are running into throttling issues with docker pulls - what do we think about having a proxy registry which pulls images and creates mirrors to pull from.

**Comment by simonwo** [comment]
We discussed: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1679993774529309

And concluded that the following fixes would solve the issues and be better that running a registry mirror:
- #2254 
- #2255
