### ISSUE TITLE
Hide temporary results for external verifier

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2378]
Right now, there is no security for temporary results, and it relies on the publication location being secret from the user. There are two ways to solve this: 

1. publish temporary results to a different location that is accessible only to moderator 2. encrypt the results with the moderators private key

**Comment by aronchick** [comment]
Prefer the first please!

**Comment by simonwo** [comment]
Verifiers have been removed so this is defunct.
