### ISSUE TITLE
GPU jobs are only scheduled on one node

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#2383]
GPU jobs only run on this node while other remain idle
![image](https://user-images.githubusercontent.com/79689323/232921640-a317ecb0-5d74-4e9d-967e-68e4f003dc07.png)

**Comment by simonwo** [comment]
Please can you post an example Bacalhau command.

If you run the command twice, does it wait for the first job to complete before starting the second time? Or does it schedule the second one to a different GPU node?

**Comment by js-ts** [comment]
`bacalhau docker run --gpu 1 nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`

**Comment by simonwo** [comment]
`curl https://dashboard.bacalhau.org/api/v1/nodes | jq '.[]| {version: .BacalhauVersion.gitversion, gpus: .ComputeNodeInfo.MaxCapacity.GPU}'

```json
{"version":"v0.3.25","gpus":2,"owner":null}
{"version":"v0.3.23","gpus":null,"owner":"docs-quick-start"}
{"version":"v0.3.28","gpus":1,"owner":"bacalhau"}
{"version":"v0.3.23","gpus":1,"owner":"labdao"}
{"version":"v0.3.28","gpus":null,"owner":"bacalhau"}
{"version":"v0.3.28","gpus":null,"owner":null}
{"version":"v0.3.28","gpus":null,"owner":"bacalhau"}
{"version":"v0.3.25","gpus":1,"owner":null}
{"version":"v0.3.28","gpus":null,"owner":"bacalhau"}
```

So all the other nodes with GPUs are currently on an outdated version of Bacalhau, hence are not available for scheduling...

**Comment by simonwo** [comment]
So this issue should sort itself out when people upgrade their nodes. 

@lukemarsden Did you say you knew the people who were running the mega-server with 2 GPUs? 
@wesfloyd Do you know who at LabDAO is running their Bacalhau node?

**Comment by thetechnocrat-dev** [comment]
@simonwo we upgraded our setup in a staging environment and it is working. We plan to also upgrade our production node this week. However, we are running behind our own requester node, so not sure if we will pick up public jobs automatically.

**Comment by aronchick** [comment]
We probably need a better way for folks to understand they are out of skew.

Or maybe auto-upgrade option?
