### ISSUE TITLE
Manage compute node CPU resources

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2385]
We want to exert more fine-grained control over CPU usage of jobs, and so we should set a reasonable value for the `limit-job-cpu` option on our compute nodes.  This should be enough for executions to run efficiently, but not so much that compute nodes end up blocked in the OS run queue waiting for CPU.

We might also want to choose a sensible default for `--limit-total-cpu` to ensure we leave enough for the bacalhau nodes to consume.

**Comment by wdbaruni** [comment]
This looks like specific to our demo network configuration
