### ISSUE TITLE
No unknown user errors

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2397]
We a large number of errors that make it through to the user with no clarity:

* No nodes available to schedule jobs
* IPFS interconnect issues

We need to fix these - and highlight any time things like this happen (so we can prevent it in the future).
```[tasklist]
### Tasks
- [ ] #2487
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2375
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2398
```

**Comment by frrist** [comment]
Some more context: This falls into a similar vein as https://github.com/bacalhau-project/bacalhau/issues/2398. And https://github.com/bacalhau-project/bacalhau/issues/2371 partially addresses the issues, mainly around the `bprotocol`, but more work is likely needed on the IPFS side of things.
