### ISSUE TITLE
sqlite unusable as input (in read-only input folder)

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2406]
When specifying a sqlite file as part of a docker execution's input, it is created on a read-only filesystem. This makes it problematic to use the sqlite file as sqlite requires write access to the directory where it lives (for .wal files etc).  

Attempts to open and query the sqlite file with the following fails. 

```yaml
  Entrypoint:
    - sqlite3
    - ":memory:"
    - "PRAGMA locking_mode=exclusive;PRAGMA query_only;PRAGMA journal_mode=DELETE;PRAGMA temp_store=MEMORY;"
    - ".open 'file:/inputs/bsky.db?mode=ro'"
    - "select * from follows limit 10;"
```

It seems like using sqlite as an input is something we'd want to allow/enable.

**Comment by simonwo** [comment]
Can we try with [`?immutable=1`](http://www.sqlite.org/draft/uri.html#uriimmutable)?

**Comment by rossjones** [comment]
It does indeed work, but can't be used with mode=ro at the same time. The following works.

```
sqlite3 \
    ":memory:" \
    "PRAGMA locking_mode=exclusive;PRAGMA query_only;PRAGMA journal_mode=DELETE;PRAGMA temp_store=MEMORY;" \ 
    ".open 'file:/inputs/database.db?immutable=1'"
```

**Comment by rossjones** [comment]
This is fixed by https://github.com/bacalhau-project/docs.bacalhau.org/pull/222 which explains about using the immutable param.
