### ISSUE TITLE
git repository storage provider relies on kv store

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2411]
The code at https://github.com/bacalhau-project/bacalhau/blob/main/pkg/storage/repo/storage.go#L192 uses a kv store to maintain state and reduce the number of times something is pulled from git. 

However the kv currently used is centralised and not supported, and so we should remove it's use until #2330 is complete.

**Comment by js-ts** [comment]
When I created the kv store there were no distributed kv store available, I'm okay with a distributed kv store when it's implemented
https://github.com/bacalhau-project/kv.bacalhau.org
