### ISSUE TITLE
Explore repalcement of IPFS CoreAPI client with boxo

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2412]
Some scenarios in which you may find Boxo helpful:
- You are building an application that interacts with the IPFS network
- You are building an IPFS implementation
- You want to reuse some components of IPFS such as its Kademlia DHT, Bitswap, data encoding, etc.
- You want to experiment with IPFS

see: https://github.com/ipfs/boxo

**Comment by simonwo** [comment]
Another option is https://iroh.computer/
