### ISSUE TITLE
allowing networking to setup local host access in private cluster node

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#2433]
For accessing local SQLite, Local Spark Cluster, etc. 
we need to have access to localhost inside the container

**Comment by js-ts** [comment]
Tried Didn't work

I tried with  --job-selection-accept-networked

![image](https://user-images.githubusercontent.com/79689323/235723885-f8775589-31eb-4fa6-9c03-ccce51d158db.png)

**Comment by simonwo** [comment]
The errors you're getting look to be about what is running in the job, you need to specify `curl` as the entrypoint as well as the parameters (we have a bug atm where the default entrypoint is erased – @olgibbons is fixing it). 

You also need to specify networking for the job specifically.

So please try and let me know what you get?:
```
bacalhau docker run --network=full curlimages/curl curl http://localhost:8080/
```

**Comment by js-ts** [comment]
That Works!
