### ISSUE TITLE
Add Requestor node envs in the jobspec for convinience and reproducibility (private jobs)

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#2441]
To Connect to private requestor node the user has to paste these variables in every terminal they want to submit a job
```
export BACALHAU_IPFS_SWARM_ADDRESSES=/ip4/10.128.0.24/tcp/41817/p2p/QmPHaMCiYRJ2746WDoZavv63GK3ZeFHSQDLamH4MNqYGkJ
export BACALHAU_API_HOST=35.223.100.29
export BACALHAU_API_PORT=1234
```
Copying and pasting these envs should only be done once in most of the cases they get lost

Instead having these as optional values in the jobspec can make for better reproducibility and no need to copy them every time you want to submit a job to the private cluster

**Comment by js-ts** [comment]
Yes just setting a single env is better

**Comment by simonwo** [comment]
There is already a `DEVSTACK_ENV_FILE` env var which if set is picked up by the CLI and used to set the above API vars, and it's created by the devstack when running. So could we just rename it to `BACALHAU_ENV_FILE` and then use it for non-devstack purposes as well?
