### ISSUE TITLE
Old-style Publisher fields cause the job to be rejected

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2447]
If you use `bacalhau create` to submit a job spec which uses the old-style `Publisher: <type>` syntax, the job is rejected despite the fact this is meant to be backwards-compatible.

This is because although we have a job transform to migrate the `Publisher` field to a `PublisherSpec`, it only runs _after_ the job validation which now checks that `PublisherSpec` is present and sane. So effectively, there is not backwards compatibility here.

**Comment by aronchick** [comment]
Still needed?
