### ISSUE TITLE
Unable to run Submit job example

### ISSUE THREAD

**Issue by deepakbhatia** [bacalhau-project/bacalhau#2469]
```
pip install bacalhau-sdk
```

```
These imports not found
from bacalhau_apiclient.models.job_sharding_config import JobShardingConfig
from bacalhau_apiclient.models.job_execution_plan import JobExecutionPlan
```

**Comment by rossjones** [comment]
@deepakbhatia I've got a PR in to fix this, but in the mean time if you try the example at https://github.com/bacalhau-project/bacalhau/blob/3982f0b1667b386ac838b4a599dd15f7320fa4fa/python/examples/submit_job.py then this should get you a bit further along.

**Comment by rossjones** [comment]
Thanks for taking the time to give it a try @deepakbhatia and for reporting the issue.
