### ISSUE TITLE
Content addressible functions (jobs) - caching is cool

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#247]
ETA: 2023Q1

If we start making the job id the hash of the job spec, we'll get caching for free (although we'll need to test that getting cached results works well with the CLI flow, and we might want a way to request a retry, maybe by bumping some field in the job spec), and the system will also feel more IPFS-y.

**Comment by Bubblyworld** [comment]
@lukemarsden makes sense to me, but for non-deterministic jobs we probably don't want to cache, right? Since different executions might have different results.

Or I guess to rephrase: where does the caching happen?

**Comment by lukemarsden** [comment]
hmm yeah, we don't know a priori whether a job is deterministic or not - maybe for jobs where determinism isn't enforced by the runtime, we want to give the user the option to reuse a previous result, or re-run it by bumping a salt in the job spec or something, a bit like how `go test` will reuse previous results but you can set `-count=1` (not obvious UX!) to get it to explicitly rerun

**Comment by Bubblyworld** [comment]
Mmm, maybe caching should be opt-in for stuff that isn't explicitly deterministic? I can see this being a source of pain for users, the `go test -count=1` thing has tripped me up a number of times in my life (run a randomised test a few times, think it's okay, actually it was just caching the first result).

**Comment by lukemarsden** [comment]
Yeah sure

**Comment by aronchick** [comment]
cc @frrst
