### ISSUE TITLE
Look at removing pkg/model/V1alpha1 and pkg/model/V1beta

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2476]
These two packages are only really used by:

* the dashboard's import CLI to convert between different versions of JobEvents when importing logs
* the `ops/metrics` CLI for the same purpose.

`v1beta1` is also used as the model reference in `pkg/localdb`, and quite widely in the dashboard as the model reference there.

Other than this they don't serve much purpose, and we should consider removing them to avoid confusion with pre 1.0 models

**Comment by simonwo** [comment]
Done by @frrist in #2535
