### ISSUE TITLE
Update swagger commit to not use a personal access token

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2480]
Currently there are commits that happen to `main` that are using a personal access token, and it would be a good idea to either remove the need for that (e.g. move to github actions for that one item) or to use a 'machine user' account instead.

Example commit https://github.com/bacalhau-project/bacalhau/commit/eda7c76b4cd8ab228e51c8dc177f583a127bb851

**Comment by aronchick** [comment]
Yes!

**Comment by wdbaruni** [comment]
@aronchick is this still an issue?
