### ISSUE TITLE
Better control over listening addresses

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2486]
In various places we iterate network interfaces (or rather their addresses) to build up a list of options.  We then choose one of the values and listen on that interface.  Sometimes this is the right thing to do (although the selection is arbitrary) and sometimes it isn't (where we should use all of the addresses e.g. swarm).  For both of these options we probably need better control over which addresses to include and which to exclude.

We currently have #2484 as a workaround to the wrong interface being chosen and allowing us to specify our preferred address.

For fuller control we might want...

### Single address required

- Specify the single address explicitly or,
- One will be chosen from 0.0.0.0:0 

### Multiple address enabled (multiaddresses)

- Bind to 0.0.0.0:0, and optionally 
- Specify addresses to be included/excluded

NB: Verify the comment at https://github.com/bacalhau-project/bacalhau/blob/main/pkg/devstack/devstack.go#L164-L167 about why we only use a single address.

**Comment by wdbaruni** [comment]
I believe this is mostly solved by https://github.com/bacalhau-project/bacalhau/pull/3394
