### ISSUE TITLE
release docs alongside bacalhau

### ISSUE THREAD

**Issue by binocarlos** [bacalhau-project/bacalhau#252]
ETA: 2023Q1

There can be the situation where developers write documentation (yay - good job :star:) but for a feature that is not yet released.

This can mean a public user is attempting to do things that are not yet possible with the released code.

Docs are independantly published to https://docs.bacalhau.org/ from the [docs repo](https://github.com/bacalhau-project/docs.bacalhau.org) whereas bacalhau releases are done from this repo.

We need a way of only publishing the docs website when a new release of bacalhau is made.

**Comment by simonwo** [comment]
This is now in spitting distance since #3070 got done.

**Comment by aronchick** [comment]
well done!
