### ISSUE TITLE
Improved error on poor network

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2521]
Run: `bacalhau docker run --concurrency 5 ubuntu echo hello world` on a network with only 4 nodes.

Expected: `Failed to submit job: not enough nodes to run job. requested: 5, available: 4 (and additional information about how to debug? e.g. how to get a list of nodes, etc?`

Actual: All of help printed + grammar not great (e.g. not capitalized or formatted particularly well. 

Move to "strings" for future localization?

**Comment by simonwo** [comment]
Resolved by #3008.
