### ISSUE TITLE
Have a way to set the target with a command

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2522]
Today you have to get the output of a bacalhau serve in order to set environment variables - e.g. outputting /run/bacalhau.run

It'd be great to allow you to set your CLI target with a command, by pointing it AT a target even possibly.

E.g. 

`bacalhau set-target 100.10.38.182`

This would:
- test to see if you could connect (and give you clear errors if things time out/etc)
- set your cli to the new updated target
- test to see if you have permissions to log in

Maybe we steal something like from .kubeconfig?

**Comment by simonwo** [comment]
This should be quite straightforward now we have `bacalhau config set`. We just need to replace the output in bacalhau serve.

**Comment by wdbaruni** [comment]
This requires the compute nodes to be callable by the requester node, which is what we are trying to avoid to simplify our network setup by making the compute nodes more of clients, and only the requester node to act as a server that must be accessible with a reachable ip.

As we are slowly improving our node boostrapping, I don't think this will be necessary and we should deprecate bacalhau.run and env variables outputs to stdout

**Comment by wdbaruni** [comment]
Ignore my previous comment. I think the ask is to have the compute node or a client call something like `bacalhau set-target 100.10.38.182` where the ip is of the requester node, which should be accessible.

I think we have simplified out bootstrapping where you only need the orchestrator node's ip for both `bacalhau serve --node-type compute --orchestrators=<ip>` and `bacalhau job run --api-host <ip>`

In addition to that, we are adding #4012 for client command configurations where can easily switch between networks. 

Closing this issue, but please re-open if the current state and upcoming changes are still not enough
