### ISSUE TITLE
Easier bootstrapping

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2524]
What if we allowed nodes to default (during Bacalhau serve) to either:

a) use a central service (provided by Bacalhau) as a rally point/bootstrapper
b) point at another node and download all connectivity information?
c) something else?

Wrote up some thoughts here - https://luck-muscle-f89.notion.site/Easier-Bootstrapping-c0152f2b74094bc79455f92765ad138c

**Comment by aronchick** [comment]
Not sure how much is left here - @frrist @wdbaruni ?

**Comment by frrist** [comment]
The changes in https://github.com/bacalhau-project/bacalhau/pull/2897 more or less completed option b) and have made bootstrapping easier as a PeerID is no longer required when connecting to a requester node, compute node operators can simply reference it IP address. I expect the changes Walid is landing via NATs to further simplify the process of creating a network.

Further work related to creating a network is encompassed in:
https://github.com/bacalhau-project/expanso-planning/issues/227
