### ISSUE TITLE
do our best to give more sensible error messages around docker registry

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#2526]
Example:
```
- Status: 'Could not inspect image "bacalhauproject/duckdb-log-processor:v0.17"
  - could be due to repo/image not existing, or registry needing authorization:
```

Image didn't exist (my fault) - we should try to make this friendly.

**Comment by simonwo** [comment]
Can you say more about how you'd expect this to be more friendly? It says in the error message "could be due to image not existing" which was indeed the cause?
