### ISSUE TITLE
Update Dashbaord to latest model implementation

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2536]
### Background
As outlined in [#2535](https://github.com/bacalhau-project/bacalhau/issues/2535), the Dashboard still relies on the v1beta model specification.

### Action
Update the dashboard type system to the latest version of the model specification

**Comment by simonwo** [comment]
What is the plan for the existing data in the dashboard database that is currently in the legacy specifications?

**Comment by frrist** [comment]
There is undoubtedly value in keeping it. We could export it to CSV and persist it somewhere (estuary, s3, r2, w/e) for historical reference. But the effort to keep the dashboard working as it does today (its queries and ingestion) with the legacy data and new formats we are moving towards will burden development as the spec continues to evolve.

How does this sound:
1. Export all existing data to CSV, and pin it on a storage backend.
2. Hibernate the dashboard, and possibly truncate it's database (would save $$$)
3. If we want to query the historical data use bacalhau + duckdb.
4. Later, awaken the dashboard, and at that point decide if we want to import historical data.

**Comment by frrist** [comment]
To mediate the loss of metrics we'll face from dashboard hibernation we can move almost all of its (metric related) functionality to Grafana. This will require implementing some new metrics in the Requester node, but that's something we intended to do anyways - so a win-win in my book.
