### ISSUE TITLE
Decouple Docker and Wasm CLI areguments from job specification

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2540]
### Background
The Docker and WASM CLI arguments are tightly coupled to the job specification. This coupling makes changing the Job specification cumbersome as the CLI must be updated, even if said changes are mechanical in nature. Furthermore, the Client (CLI) aims to build a job spec that it then forwards to a Requester node, which then mutates the spec depending on various conditions. We should instead opt to build job specs on the Requester nodes based on the arguments it receives from the client. 

### Action
- The CLI around creating Docker and WASM jobs is a mess. Work completing this issue should aim to streamline the common flags shared by executors (like publisher, verifier, networkconfig, labels, etc.).

For more details on the thrust of this change refer to https://www.notion.so/Separate-Protocols-from-APIs-2b8552ea1fe6428b832d111494b59f37 and https://www.notion.so/pl-strflt/API-Design-a024dbbb17354643aaa08a5eb665bcfa.

**Comment by simonwo** [comment]
Why is creating Docker- and WASM- specific APIs a good idea when we are trying to move to more genericism in our executors?

**Comment by frrist** [comment]
You're right, I have removed that from the acceptance criteria and have aimed to just clean up the CLI instead.
