### ISSUE TITLE
`--label` on `bacalhau serve` is not the same in job creation cmds

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2557]
We use label on serve to mean set labels for the node. We use label on create to mean set labels for the job. We use selector on create to mean target this job to just these node labels.

This is potentially confusing to users – perhaps selector should also be used for node labels and label only for job labels?

**Comment by aronchick** [comment]
+1!

**Comment by wdbaruni** [comment]
@frrist what are your thoughts on this one?
