### ISSUE TITLE
Configurable compute timeouts

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2561]
Having a maximum timeout makes sense on a public network where non-paying users should not be able to hog capacity. For private clusters, the behaviour should be configurable – users may wish to run jobs that span many days.

At the moment we enforce a default compute timeout of 60 minutes:
https://github.com/bacalhau-project/bacalhau/blob/516a1570aa40376ae822474c184f58cdf7fb45d6/pkg/node/config_defaults.go#L20
Any job that is submitted that exceeds this timeout is [rejected by compute nodes at the bidding stage](https://github.com/bacalhau-project/bacalhau/blob/516a1570aa40376ae822474c184f58cdf7fb45d6/pkg/bidstrategy/semantic/timeout_strategy.go#L43).

Requester nodes have separate config that control timeouts:
https://github.com/bacalhau-project/bacalhau/blob/516a1570aa40376ae822474c184f58cdf7fb45d6/pkg/node/config_defaults.go#L27-L28
If a job is submitted with a timeout less than or equal to the `MinJobExecutionTimeout` (or without a Timeout field at all), the job's timeout is set to the `DefaultJobExecutionTimeout`.

We also by default set the timeout on a job to a seperate 30 minutes:
https://github.com/bacalhau-project/bacalhau/blob/516a1570aa40376ae822474c184f58cdf7fb45d6/cmd/bacalhau/utils.go#L44

We should:
* by default, set the timeout to "infinite" or thereabouts – we should only apply limits if operators tell us to
* allow compute and requester node operators to set the maximum timeout they will accept
* configure the public Bacalhau network to still have a 60 minute timeout

## Setting an "infinite" timeout

We will need to:
* Remove the default timeout on the CLI  – jobs by default should use the maximum timeout. We can probably just set the `DefaultTimeout` in the CLI to zero.
* Set the default `MaxJobExecutionTimeout` and `DefaultJobExecutionTimeout` to the maximum value of a `time.Duration` parameter (e.g. `math.MaxInt64`) – this is not technically infinite but covers many centuries, so is fine.
* Leave the `MinJobExecutionTimeout` at zero – so that jobs without a timeout specified will always use the max. 

## Set timeouts

Add a flag to the `devstack` and `serve` commands that will allow the timeout to be set. The same flag should be used to set both the compute node's `MaxJobExecutionTimeout` and requester node's `DefaultJobExecutionTimeout`. 

We already have a configuration parameter for timeouts, so you only need to ensure they are set:
https://github.com/bacalhau-project/bacalhau/blob/516a1570aa40376ae822474c184f58cdf7fb45d6/cmd/bacalhau/serve.go#L183

If the flags are not used, the default values set above should be used.

## Configure public Bacalhau

Ensure the public Bacalhau network still sets a timeout of 60 mins. Ensure the `bacalhau serve` command as used by the Bacalhau public nodes includes your new flag with the correct value.

https://github.com/bacalhau-project/bacalhau/blob/516a1570aa40376ae822474c184f58cdf7fb45d6/ops/terraform/remote_files/scripts/start-bacalhau.sh#L58-L68

**Comment by NiklasTR** [comment]
Thanks a lot @simonwo 

Here is the summary of action that I understood from the spec above: 
- [ ] set the value for DefaultJobExecutionTimeout and MaxJobExecutionTimeout to be the same near-infinite value
- [ ] remove DefaultTimeout in utils.go
- [ ] add the 60min timeout flag to the public-network terraform 

what are your proposed next steps? 
From the LabDAO side we can proceed, introduce changes and add a PR if it works for you

**Comment by simonwo** [comment]
> what are your proposed next steps? From the LabDAO side we can proceed, introduce changes and add a PR if it works for you

Would be very happy to receive a PR!!! I think your summary is spot on. If an engineer on your side wants to take a look and come back with questions, I can provide any more pointers?

**Comment by aronchick** [comment]
This is terrific - let's make sure to improve the error too :)
