### ISSUE TITLE
Create map of execution states -> restart action

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2631]
When a compute node restarts with persistent state, it needs to process that persistent state so that work is not lost.  Depending on the type of job, and the current state of that job (and the age of the last recorded state) we should take some action.  Before we do that, we should document those actions so that we know things like... 

```
State: ExecutionStateAcceptedBid
Age: >1 day
JobType: Continuous
Action: Restart 
```

**Comment by rossjones** [comment]
The start of the list is at https://github.com/bacalhau-project/bacalhau/blob/main/docs/compute_node_database.md but we need clarify on:

* The exact list of job types
* How they are identified (is it in the spec, do we have to work it out? etc)

**Comment by rossjones** [comment]
Although we're going to determine this based on job type, perhaps we could/should internally map those job types to a `RestartPolicy` that can be determined by the requester node, and interpreted by the compute node - which will mean that adding more job types would not require a redeployment of the compute node fleet.

**Comment by aronchick** [comment]
Still needed?

**Comment by rossjones** [comment]
No, don't think this is necessary now
