### ISSUE TITLE
Job archival and deletion for jobstore

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2657]
Once the persistent jobstore is complete, we will have persistent job info and job states, and history but this will persist forever. Or until we run out of disk space. Whichever happens sooner.

We should provide an archival policy that states how long jobs are maintained in the jobstore once they are in a terminal state, before they are removed and perhaps archived in a different store. We should also implement that policy.  We might also take the opportunity to reap jobs that are in a broken state for too long (e.g. waiting in non-terminal states for days. ExecutionStateAskForBid for example).

**Comment by aronchick** [comment]
Great point. Might also be worth having a (larger) feature that exports this information to an external store (flat file, redshift, whatever).

**Comment by wdbaruni** [comment]
Tracked by https://github.com/bacalhau-project/bacalhau/issues/4174
