### ISSUE TITLE
Revisit execution store restarts when job types are available

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2658]
When we have a clear mechanism for identifying job types, we need to revisit the compute execution store so that we can take appropriate action when restarting the compute node.  We also need to get agreement on the policies we use to define those actions.  

They should encompass, as a mimimum:

* Do nothing
* Cancel job (and inform requester and clear store)
* Restart job (and inform requester)

**Comment by aronchick** [comment]
Stale?

**Comment by rossjones** [comment]
This was completed in #2796
