### ISSUE TITLE
Make --local feature work for Other and Custom Executors

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#2751]
For users who want to test stuff locally on their private data and try out different custom executors without the need to start devstack

**Comment by wdbaruni** [comment]
What is `--local`? Is this still valid?

**Comment by js-ts** [comment]
It doesn't work

**Comment by wdbaruni** [comment]
the flag is still there but doesn't work? the flag is removed, and the dead code is still available? or everything has been removed? Can you be more clear?

**Comment by js-ts** [comment]
Need to fond and remove the dead local code
