### ISSUE TITLE
list command enhancements

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2763]
After using the list command for some shell scripting, there are a few features that would have made the experience more effective and these should not be too difficult to add.

```[tasklist]
### Tasks
- [ ] #2679
- [ ] Filter within a date range (e.g. only jobs between this date and today, or only jobs in December).
- [ ] Make `--all` return all and not also require `--number` to retrieve more than 10
```

**Comment by wdbaruni** [comment]
`--all` is confusing as it means for all namespaces instead of just the client's namespace. We now support pagination where users can define the limit and next token. 

btw, the new `bacalhau job list` doesn't have `--all` flag

**Comment by wdbaruni** [comment]
related to #2679
