### ISSUE TITLE
Running a bacalhau job with the `--local` flag could be used as not intended.

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2769]
Users on `main` who run `bacalhau docker run --local ubuntu:latest echo hello world` (ditto for `wasm`) will get an error about their version mismatching the network, and the job will never run. Users on `v1.0.3` will (sort of) be able to execute the job, but won't be able to inspect it, and will see numerous errors about the job not being found after execution - which I suspect is due to querying the network for the job rather than the devstack, which is shutdown immediately following the commands execution.

Is the `--local` option something we need to continue supporting? If so, what should the expected behavior be? Should the devstack remain running after the job completes so the job issuer can inspect the result? Might it be better for users who want to run jobs locally to simply start a devstack and issue jobs to it instead?

**Comment by aronchick** [comment]
It's not supposed to be run with devstack (really) - it's supposed to allow running locally on your machine, so you can debug. I'm open to lots of thoughts here!

**Comment by wdbaruni** [comment]
`--local` is no longer supported
