### ISSUE TITLE
Limit update checks to once per day

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2894]
In #2893 we made more commands check for updates. Strictly not all of these checks are necessary as the code is unlikely to have changed regularly. Instead we should limit the amount we check for updates to (perhaps) once per day. 

Suggestion: every time we perform an update check, write a config property into `config.yaml` that will be the `NextUpdateCheck` date and time. If the current time is behind this value, don't do any checking. If the current time is ahead of this value, do and update check and then move the time forward by 24 hours.

**Comment by wdbaruni** [comment]
I like this, though maybe not in `config.yaml` as thats is the config file the user should provide and we shouldn't use it to track state

**Comment by simonwo** [comment]
Yeah ok. It's also not very easy to write an individual key in the config file! So will just track state in some file in the repo.
