### ISSUE TITLE
fast track installation fails

### ISSUE THREAD

**Issue by phiflei** [bacalhau-project/bacalhau#2927]
Simply running curl -sL https://get.bacalhau.org/install.sh | bash, to install bacalhau on a Macbook Pro M2 2022, I get the following error:

...
Your system is darwin_arm64
No BACALHAU detected. Installing fresh BACALHAU CLI...
Getting the latest BACALHAU CLI...
Installing v1.1.1 BACALHAU CLI...
Downloading https://github.com/bacalhau-project/bacalhau/releases/download/v1.1.1/bacalhau_v1.1.1_darwin_arm64.tar.gz ...
Downloading sig file https://github.com/bacalhau-project/bacalhau/releases/download/v1.1.1/bacalhau_v1.1.1_darwin_arm64.tar.gz.signature.sha256 ...
Verified OK
Extracting tarball ...
NOT verifying Bin
Password:
Failed to install bacalhau

Any ideas on how to fix this? Thanks.

**Comment by aronchick** [comment]
Is it possible you mistyped the password?
