### ISSUE TITLE
JobSelectionPolicy is un-used for the requester node

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2929]
Both the Compute and Requester Node support a JobSelectionPolicy. At present, the Requester node accepts a policy in its configuration but fails to apply/use it anywhere. The task here is to re-enable support for the JobSelectionPolicy in the Requester Node. This issue was discovered while investigating https://github.com/bacalhau-project/bacalhau/issues/2898 will will follow the fix there.

**Comment by frrist** [comment]
This issue was discovered while investigating [#2898](https://github.com/bacalhau-project/bacalhau/issues/2898) will will follow the fix there.

**Comment by frrist** [comment]
The removal of the JobSelectionPolicy from the requester was made while upgrading to the evaluation broker via: https://github.com/bacalhau-project/bacalhau/pull/2681/files#diff-db482b8c1643fdf50b3648bd443784dfa31ceac24f6c6994f421c42f73d419eaL132-L137 

I believe we'll need to incorporate the previous logic of the JobSelectionPolicy into the Evaluation Brokers `NodeRanker` to preserve existing behavior.

**Comment by aronchick** [comment]
Stale?

**Comment by simonwo** [comment]
I think it's still an issue and we should still look to restore this feature. Stopping jobs that don't meet policy should be done as early as we can, i.e. in the Requester.

**Comment by wdbaruni** [comment]
we can close this as we are moving more towards config files instead of cli flags to configure nodes #4014
