### ISSUE TITLE
Improve GPU Support

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#293]
Related subtasks:
* [ ] https://github.com/filecoin-project/bacalhau/issues/403 and https://github.com/filecoin-project/bacalhau/issues/404
* [ ] https://github.com/filecoin-project/bacalhau/issues/1665
* [ ] https://github.com/filecoin-project/bacalhau/issues/899
* [ ] https://github.com/filecoin-project/bacalhau/issues/861
* [x] https://github.com/filecoin-project/bacalhau/issues/1270
* [ ] https://github.com/filecoin-project/bacalhau/issues/919
* [x] https://github.com/filecoin-project/bacalhau/issues/582
* [ ] https://github.com/filecoin-project/bacalhau/issues/1667

ETA: 2023Q2 **<-- needs updating**

**Comment by aronchick** [comment]
Lower priority. Need to get everything working first
