### ISSUE TITLE
Show liveness in 'node list' command

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2935]
I have a cluster of 4 nodes, 2 in EU and 2 in US.
I recently suffered a split brain.
When I ran jobs with `--target=all` only the 2 nodes in the EU were sent work.
`bacalhau node list` showed all 4 nodes. 

It would be useful when investigating this situation, to determine when a particular node last contacted the requester. 
If dead nodes are expected to stay in the node list, it would also be good if they were somehow shown as dead/unresponsive.

**Comment by wdbaruni** [comment]
We now have `connected` and `disconnected` states
https://github.com/bacalhau-project/bacalhau/pull/3709
