### ISSUE TITLE
API for managing config

### ISSUE THREAD

**Issue by alabdao** [bacalhau-project/bacalhau#2941]
It would be great to have an endpoint where we can update configs such as adding/updating peer, ipfs info, etc.
This would be useful for environments where peers are not known at startup and can be added later by interacting with the API.
Similar to what IPFS provides, for example, [add swarm peers](https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-swarm-peering-add).

**Comment by frrist** [comment]
#3012 didn't add support for a command like `ipfs swarm peers` to reopening.

**Comment by wdbaruni** [comment]
As we are moving away from embedded ipfs node, the work in #3012 should be enough to close this issue
