### ISSUE TITLE
Requester can't rediscover compute nodes after restart

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#2945]
After a restart, the requester node loses the compute nodes it has discovered through gossiping. The compute nodes do heartbeat by gossiping every 30 seconds, and the requester should re-discover the nodes. It seems a problem with how we are setting up the libp2p gossiping network 

https://bacalhauproject.slack.com/archives/C052BAZJVEU/p1698003358561839

**Comment by frrist** [comment]
@wdbaruni I am closing this since we are moving to NATS

**Comment by wdbaruni** [comment]
First we need to verify this is a libp2p issue and we don’t have a similar
problem with NATS
