### ISSUE TITLE
Issues with IPFS routing

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2948]
We have observed some unfortunate behaviour with a private IPFS cluster that means results are not downloadable. The issue appears to be that nodes that are in the same swarm as each other don't appear to discover content on each other.

An example setup:

- Two separate machines – one running Bacalhau in requester mode, one in compute mode, both with kubo IPFS nodes
- The IPFS nodes have each other listed in their peering config
- Run a Bacalhau job which will generate some result in the compute node
- Run Bacalhau get with the IPFS swarm addr of the requester node

Expected: results are downloaded successfully as requester IPFS node is able to get the data from the compute IPFS node
Observed: download times out as requester is seemingly unable to find the data
Observed: problem disappears if `ipfs pin` is used to explicitly and permanently cache the data on the node 

- And/or, Run Bacalhau get with the IPFS swarm addr of the compute node

Expected: results are downloaded successfully
Observed: download times out even though this should be directly where the data is stored (??)

Hints: IPFS node bootstrap config might be an issue, by default it points at public nodes. May be worth leaving it empty or setting it to the same as the peering list.

Context:
- https://bacalhauproject.slack.com/archives/C055U60AJKE/p1697211889274979

**Comment by wdbaruni** [comment]
embedded ipfs node has been deprecated in favour of connecting to your own node
https://github.com/bacalhau-project/bacalhau/pull/4061
