### ISSUE TITLE
Default job resources are being set to low docker

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2949]
Issuing docker jobs with a high memory requirement often results in the job failing with exit code 137, which means either: the container received a `docker stop` and the app is not gracefully handling SIGTERM or the container has run out of memory (OOM). I am fairly confident its the latter case as adjusting the resource requirements structure in the config addressed the issue. I'll need to do a bit of further investigation to determine the root case.

**Comment by rossjones** [comment]
We've been able to replicate this today, where setting `--memory` to even 500Mb will let the job complete, otherwise it will fail with the error.  We've also identified slow jobs running much faster when specifying `--cpu=1` (on single core nodes however), so it's possible the default is too low.
