### ISSUE TITLE
Change flag name from `--allow-listed-local-paths` to `--allowed-listed-local-paths`

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2961]
Motivation: https://www.notion.so/Using-Bacalhau-To-Deliver-Edge-Based-Machine-Learning-Inference-34568b42cbfa46e283704cc956f36952?d=c531c04a891749ca9a884139ecc0bcf2&pvs=4#8ce1dfc9405642c88d012d170c9d96fe

Once this work is completed, we'll need to update any blog post using this flag, as well as documentation for it in the docs site.

**Comment by frrist** [comment]
@aronchick is this the preferred naming you'd like to use?

**Comment by aronchick** [comment]
no, it should be "allow" not "allowed"
