### ISSUE TITLE
terraform managed ip addresses

### ISSUE THREAD

**Issue by binocarlos** [bacalhau-project/bacalhau#297]
ETA: 2023Q3

Presently - if we switch out the ip addresses of a terraform cluster, DNS has to be manually updated with the new ip addresses.

We should have some kind of load balancer (managed also by terraform)

if the cluster of machines get new ip addresses, any DNS out in the wild will still resolve to the new ips via the load balancer.

**Comment by aronchick** [comment]
Obviously not p0, but very convenient
