### ISSUE TITLE
python SDK documentation is broken along with need of standardisation

### ISSUE THREAD

**Issue by dhruvmalik007** [bacalhau-project/bacalhau#2987]
Context: 
The page for showing example tutorial of [bacalau-sdk](https://docs.bacalhau.org/sdk/) is not working . Also I wanted to also get your viewpoints on the following suggestions

- Should there also be release notes of the bacalau-sdk (both of interacting with client and node sdk) so as to know the deprecated changes.
-  Whether its a better strategy to define it within the unique SDK or to maintain the separate SDK's for [client](https://github.com/bacalhau-project/bacalhau/blob/main/clients/python/bacalhau_apiclient/api/) as well as [node](https://github.com/bacalhau-project/bacalhau/blob/main/python/bacalhau_sdk/api.py). I found indeed many of the higher level classes are imported directly but still there is lack of cohesive coupling as many classes like Jobspec , listJobs etc are available uniquely to the bacalau.api_client but not in SDK.

thanks

**Comment by MichaelHoepler** [comment]
https://docs.bacalhau.org/integrations/python-sdk
