### ISSUE TITLE
Bacalhau installer  failing

### ISSUE THREAD

**Issue by Nasfame** [bacalhau-project/bacalhau#3029]
```
curl -sL https://get.bacalhau.org/install.sh | bash
```

<img width="996" alt="image" src="https://github.com/bacalhau-project/bacalhau/assets/24226219/ecbe57cc-80c6-4b9e-a581-028ac303a77f">

**Comment by simonwo** [comment]
https://github.com/bacalhau-project/get.bacalhau.org/pull/25

**Comment by Nasfame** [comment]
Cool
