### ISSUE TITLE
Issues with in-process private IPFS set up and getting results

### ISSUE THREAD

**Issue by chrisalys** [bacalhau-project/bacalhau#3050]
I'm setting up a simple test network.

1 VM with a requester node
1 VM with a compute node
1 VM for submission, using bacalhau docker run ...

They're are all connected with wireguard.

The medium term plan here is to run 'n' compute nodes and a single requester node to offer clients access to our machines via submitting jobs using bacalhau as our default CLI.

The idea is that the client just sees the requester node; the wireguard is just for internode chat.

Set Up:
Ubuntu 22.04.3 LTS
Bacalhau (1.1.6)
It's over wireguard

Starting requester node with
`bacalhau serve --node-type requester --private-internal-ipfs --peer none`

It suggests this for compute connections:
```
bacalhau serve --node-type=compute --private-internal-ipfs --peer=/ip4/10.147.2.7/tcp/1235/p2p/QmRAX41gpDNm9WTAWNkNtPn4bUKSgNRhDKpnBLSDS316Sd --ipfs-swarm-addrs=/ip4/127.0.0.1/tcp/42253/p2p/QmfJ1e8LVbuw3nrhzcg87CgUoCTof6344yeByKsxqqeXva
```
Few things here:
1) Is it correct to add -**-private-internal-ipfs**, should this be **--private-internal-ipfs=false**?

2) The host has been concluded to be 3 different things:
```
export BACALHAU_NODE_IPFS_SWARMADDRESSES=/ip4/127.0.0.1/tcp/36847/p2p/QmTyV4jo1uppD4PT3rS44sBu5uNGwZLKvyovwcqJb2EVHN
export BACALHAU_NODE_CLIENTAPI_HOST=0.0.0.0
export BACALHAU_NODE_CLIENTAPI_PORT=1234
export BACALHAU_NODE_LIBP2P_PEERCONNECT=/ip4/10.147.2.7/tcp/1235/p2p/QmRAX41gpDNm9WTAWNkNtPn4bUKSgNRhDKpnBLSDS316Sd
```

So one issue is that the ipfs swarm address is at 127.0.0.1

Which it is...
```
bacalhau  29137            root    7u  IPv4 898901      0t0  TCP *:1235 (LISTEN)
bacalhau  29137            root    9u  IPv6 898903      0t0  TCP *:1235 (LISTEN)
bacalhau  29137            root   16u  IPv4 898914      0t0  TCP 127.0.0.1:42253 (LISTEN)
bacalhau  29137            root   19u  IPv4 907589      0t0  TCP 127.0.0.1:41143 (LISTEN)
bacalhau  29137            root   28u  IPv6 829299      0t0  TCP *:1234 (LISTEN)
```

But of course that fails on the compute node, as it can't reach it.

I can make it not fail to start with an ssh tunnel (which I also have to do on the client)

BUT... 

**bacalhau get** fails / hangs. I'm assuming that this is failing to connect to the compute node from the requester node, or the submission node not discovering the compute node? Unsure what the path is here...

So the questions are:
1) Can I get the in process IPFS to listen on 0.0.0.0, rather than 127.0.0.1, and if so will this help me?

2) As a matter of interest, when I perform a bacalhau get, does the submitting client connect to the requester and the results pass from compute node, through the requester back to submission node via IPFS, or it bacalhau handling the submitter to requester hop?

**Comment by simonwo** [comment]
Hi @chrisalys.

1. `--private-internal-ipfs=true` will ask Bacalhau to run an internal IPFS node that does not connect to public bootstrap peers or any swarm peers by default. Specifying `ipfs-swarm-addrs` should cause the node to connect to only those peers specified. Specifying `--private-internal-ipfs=false` will cause it to run an internal node that _does_ connect to public peers, and so potentially any content generated on the node will be accessible from the public IPFS network. Additionally specifying `--ipfs-connect` will cause Bacalhau to not run any internal IPFS node at all, and just will connect to the pre-configured node that is already running via the HTTP API.
2. `bacalhau get` does not do any relaying via the requester – all of the content is fetched directly from the storage source. In the IPFS case, `bacalhau get` spins up an internal node and attempts to download the content from the configured swarm. So if you just install Bacalhau, set the API host, and then run a job, it will attempt to download from the public IPFS network and the Bacalhau demo swarm. If you are running a private swarm, you need to provide at least the swarm address to `bacalhau get` (and the swarm key, if using). See https://docs.bacalhau.org/running-node/storage-providers#ipfs-1.

We know that the flow in 2 kind of sucks, at are discussing a replacement over at #2752 which we'd like to hear feedback on!
