### ISSUE TITLE
fix all the data races

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#306]
ETA: 2023Q1

run `make devstack-race`
run `cd benchmark_hack; API_PORT_0=XXX ./explode.sh` against it
fix all the data races :-)

**Comment by Bubblyworld** [comment]
Another thing we could keep in mind regarding races: we do a lot of exposing public fields in our structs at the moment (`ComputeNode` being a particularly glaring example, everything is exported). Might be a better idea to keep things private as much as possible and rely on getters. It's a pain but it makes it much easier to keep stuff thread-safe (we can just stick all the sync code in the getters, and then we'll never forget).

**Comment by aronchick** [comment]
done?

**Comment by lukemarsden** [comment]
No, probably belongs in #659

**Comment by simonwo** [comment]
Not clear that we have any data races anymore. Where we do, we'll deal with them in individual tickets. This ticket is a zombie that will never die otherwise, I SHALL EXCISE THEE!
