### ISSUE TITLE
zsh: no matches found error when running install script.

### ISSUE THREAD

**Issue by ccjjarvis** [bacalhau-project/bacalhau#3094]
When running "curl https://get.bacalhau.org/install.sh?dl=610790c3-94b3-4ca6-9862-8b9d7ccb5fe1 | bash" on an Apple Macbook Air M2 I get the error "zsh: no matches found: https://get.bacalhau.org/install.sh?dl=610790c3-94b3-4ca6-9862-8b9d7ccb5fe1". I verified I can successfully connect to https://get.bacalhau.org/install.sh?dl=610790c3-94b3-4ca6-9862-8b9d7ccb5fe1 but am unable to successfully run the script.

**Comment by simonwo** [comment]
Yeah, this is a problem with zsh and quoting. We should probably update our documentation and update message to includes quotes around the URL, e.g:

```bash
curl 'https://get.bacalhau.org/install.sh?dl=610790c3-94b3-4ca6-9862-8b9d7ccb5fe1' | bash
```

**Comment by simonwo** [comment]
Should be fixed by https://github.com/bacalhau-project/get.bacalhau.org/pull/26. Can you try again?

**Comment by ccjjarvis** [comment]
Thanks for your help Simon, that solved it and I was able to install
successfully. It prompted me for my password which threw me for a minute
but completed after entering it.

**Comment by simonwo** [comment]
Great, thanks!
