### ISSUE TITLE
Why do we have both "model" and "models" and "apiModels"? This makes it hard to work with the code base

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3179]

**Comment by wdbaruni** [comment]
Yes very confusing. `model` are the legacy job specs will be deprecated and removed as part of this epic that is planned for this quarter https://github.com/bacalhau-project/expanso-planning/issues/529

`models` are the v2 job specs, while `apiModels` are the HTTP request and response types
