### ISSUE TITLE
Why do we have both "agent" and "client"? This makes it hard to work with the code base

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3180]

**Comment by wdbaruni** [comment]
Slack discussion https://bacalhauproject.slack.com/archives/C055U60AJKE/p1704400762056409

**Comment by wdbaruni** [comment]
Unfortunately lost the slack discussion, but agent refers to the bacalhau process that is running as a compute or a requester node. Client most likely refers to the cli calling requester APIs, but I've lost the context of your question from slack
