### ISSUE TITLE
BUG: All failed jobs are being restarted

### ISSUE THREAD

**Issue by alaric-rd** [bacalhau-project/bacalhau#3211]
@olgibbons and I have both found, since coming back from Christmas, that a failing job gets immediately retried. In his case, this means that his out-of-memory error message is never showed to the user but the job just seems to hang. In my case, it means that the exponential backoff code I just wrote for the job retry logic isn't happening because the new retry happens... somewhere else, and seemingly immediately.

My observation is that `createMissingExecs` in `pkg/orchestrator/scheduler/batch_service_job.go`, which used to return an error when nodes wouldn't accept the job due to resource allocations, is no longer returning an error in that case, but instead managing to place the job. Therefore, my retry code in my branch is no longer triggering.

The hypothesis that the problems Al and i are seeing are the same has yet to be tested, but it's suspicious that they have cropped up at the same time and seem to be similar in nature. I'm currently testing my way back through all the merges-from-main into my branch to see if I can figure out when it started happening.

**Comment by rossjones** [comment]
I've been able to replicate this on the `update_docker_executor_for_OOM` branch.  

I run devstack, and then execute `./bin/darwin/arm64/bacalhau docker run ubuntu tail /dev/zero` and it fails, but then retries and continues to do so forever.

When I run `bacalhau describe [JOBID]` I see all the executions failing but the job progress is still InProgress.

```
- ComputeReference: e-911c24d4-c086-4658-bd45-76980d8a432c
    CreateTime: "2024-01-10T14:59:55.873367Z"
    DesiredState: 2
    JobID: 2bccf347-eee7-4c57-8c7e-1a45688ec2be
    NodeId: QmdLcbeFi6xEZC3GfzTAAvBdJjReDJXiqksAR1KYKEJPnA
    PublishedResults: {}
    State: Failed
    Status: 'execution error: memory limit exceeded. execution failed'
    UpdateTime: "2024-01-10T14:59:58.344354Z"
    Version: 6
  - ComputeReference: e-911f07ed-0e9f-43ea-97fa-03754407e36b
    CreateTime: "2024-01-10T14:59:52.885959Z"
    DesiredState: 2
    JobID: 2bccf347-eee7-4c57-8c7e-1a45688ec2be
    NodeId: QmQVziCr88FNoxpHx467skzp8HcLSybbqekrqZuRA2fV9Q
    PublishedResults: {}
    State: Failed
    Status: 'execution error: memory limit exceeded. execution failed'
    UpdateTime: "2024-01-10T14:59:55.858067Z"
    Version: 6
  - ComputeReference: e-c20503ef-3580-490f-a39b-d72c14052fdc
    CreateTime: "2024-01-10T14:59:58.362537Z"
    DesiredState: 2
    JobID: 2bccf347-eee7-4c57-8c7e-1a45688ec2be
    NodeId: QmQVziCr88FNoxpHx467skzp8HcLSybbqekrqZuRA2fV9Q
    PublishedResults: {}
    State: Failed
    Status: 'execution error: memory limit exceeded. execution failed'
    UpdateTime: "2024-01-10T15:00:00.961569Z"
    Version: 6
  - ComputeReference: e-cf8183da-23ce-4f8a-959d-d62f05d76baf
    CreateTime: "2024-01-10T15:00:03.807177Z"
    DesiredState: 2
    JobID: 2bccf347-eee7-4c57-8c7e-1a45688ec2be
    NodeId: QmdLcbeFi6xEZC3GfzTAAvBdJjReDJXiqksAR1KYKEJPnA
    PublishedResults: {}
    State: Failed
    Status: 'execution error: memory limit exceeded. execution failed'
    UpdateTime: "2024-01-10T15:00:06.173217Z"
    Version: 6
  - ComputeReference: e-d5030644-3ffd-440f-9f87-a18ca982bb20
    CreateTime: "2024-01-10T15:00:00.979565Z"
    DesiredState: 2
    JobID: 2bccf347-eee7-4c57-8c7e-1a45688ec2be
    NodeId: QmTmjRMf9D4riszGXBjUyJ15rqFkf5wnPYCg7CVKcjDGdD
    PublishedResults: {}
    State: Failed
    Status: 'execution error: memory limit exceeded. execution failed'
    UpdateTime: "2024-01-10T15:00:03.79186Z"
    Version: 6
```
