### ISSUE TITLE
Redundant HTTP Headers in apimodels Request/Response structs.

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#3217]
Using the below code as an example:
https://github.com/bacalhau-project/bacalhau/blob/eb5f0149d2d438474956909b0e2417e5a018768b/pkg/publicapi/endpoint/orchestrator/job.go#L17-L37
unmarshals a request into:
https://github.com/bacalhau-project/bacalhau/blob/25c396cda88c186e1236cb9b8e62ac9214735244/pkg/publicapi/apimodels/job.go#L12-L15
with embedded structure:
https://github.com/bacalhau-project/bacalhau/blob/25c396cda88c186e1236cb9b8e62ac9214735244/pkg/publicapi/apimodels/base_requests.go#L36-L40
further embedded:
https://github.com/bacalhau-project/bacalhau/blob/25c396cda88c186e1236cb9b8e62ac9214735244/pkg/publicapi/apimodels/base_requests.go#L8-L16

The `BaseRequest` contains several fields, one of which is `Headers`. `Headers` is `nil` when the request is unmarshaled (note: all fields are nil). The headers may instead be found in the echo Request context, which are populated as expected.

Conversely the `BaseResponse` struct doesn't contain any fields.

@wdbaruni what is the intended usage pattern here?

**Comment by rossjones** [comment]
My understanding is that they exist here so that extra headers can be more easily added to the actual request as it is sent.  In BaseRequest's ToHTTPRequest method it does this  

```
        r := NewHTTPRequest()
        ....
	for k, v := range o.Headers {
		r.Header.Set(k, v)
	}
```

I suspect this will come in useful when we implement authn and need to add headers to the client requests for the auth token.

**Comment by wdbaruni** [comment]
@rossjones is correct. The idea is to simplify adding headers and similar fields in the client side. I understand they can be fetched by echo's Request context, but that is on the server side. Though we should make sure we populate the BaseRequester's headers when we unmarshall the request

**Comment by frrist** [comment]
Understood. The value of adding extra headers to a request is clear. But as I understand it, the current design will mean the request body (in this example `PutJobRequest.BasePutRequest.BaseRequest`) also contains headers, which is contrary to standard HTTP protocol practices. i.e.
**Client**:
```go
	resp, err := client.Jobs().Put(&apimodels.PutJobRequest{
		BasePutRequest: apimodels.BasePutRequest{
			BaseRequest: apimodels.BaseRequest{
				Headers: map[string]string{
					"foo": "bar",
				},
			},
		},
		Job: nil,
	})
``` 
**Server**:
```go
func (e *Endpoint) putJob(c echo.Context) error {
	ctx := c.Request().Context()
	var args apimodels.PutJobRequest
	if err := c.Bind(&args); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}
	// FIXME: args.Headers is a subset of c.Request.Headers
```
We are sending some headers twice, once in the HTTP request header field (standard practice), and a second time in the HTTP request body (abnormal, should just contain the data payload). It would be more efficient to just send them once I think, yeah? I also find this design a bit confusing to work with as a developer as there are now two place to look for headers, one of which may be an incomplete set.
  
It's worth noting The Client provided an option for adding headers to its requests:
https://github.com/bacalhau-project/bacalhau/blob/a8597852689db6fca7856845d0d33de934d8c63d/cmd/util/api.go#L24-L37

When I added headers to client requests for version info I did so via the above option.

**Comment by frrist** [comment]
Here's a demonstration of the issue: https://github.com/bacalhau-project/bacalhau/pull/3319

**Comment by wdbaruni** [comment]
No we don't send HTTP headers in the request body as they are omitted when marshalling the object

https://github.com/bacalhau-project/bacalhau/blob/75e82d0436e2f9caa63725723e2844680a212bb3/pkg/publicapi/apimodels/base_requests.go#L9-L13

They are only included in the http header as Ross mentioned. As for passing headers to the client instead of the request, that is useful when you want to define headers for all requests, such as auth tokens, but not for additional headers per request. 

I am not sure where the confusion is. `BaseRequest` and the other request types are the types you work with when constructing your request, and it will then translate itself to raw http requests, including setting headers and params if needed. This is a very common practice so you don't need to work with lower level constructs. Here is an example from AWS SDK https://docs.aws.amazon.com/sdk-for-go/api/aws/request/#WithSetRequestHeaders

**Comment by frrist** [comment]
Please review the PR I have filed, specifically:

To reproduce
1. `bacalhau serve --node-type=compute,requester`
2. `bacalhau --api-host=0.0.0.0 job run <some-job-file.yaml>`
3. Observe the encoded body in client terminal, e.g.
```
Encoded HTTP Body:  {"Namespace":"TheNamespace","Headers":{"foo":"bar"},"IdempotencyToken":"","Job":{"ID":"","Name":"A Simple Docker Job","Namespace":"default","Type":"batch","Priority":0,"Count":1,"Constraints":[],"Meta":{},"Labels":{},"Tasks":[{"Name":"My main task","Engine":{"Type":"docker","Params":{"Entrypoint":["/bin/bash"],"Image":"ubuntu:latest","Parameters":["cat /inputs/foo_data.txt \u003e /outputs/foo_data.txt"]}},"Publisher":{"Type":""},"InputSources":[{"Source":{"Type":"urlDownload","Params":{"url":"https://gist.githubusercontent.com/enricorotundo/990f0ad01a50d08dfb580e4ad404870e/raw/aa6934257351a0da93f1e740c72f27128590cebc/foo_data.txt"}},"Alias":"","Target":"/inputs"}],"Resources":{},"Network":{"Type":"None"},"Timeouts":{}}],"State":{"StateType":"Undefined"},"Version":0,"Revision":0,"CreateTime":0,"ModifyTime":0}}
```

The "Encoded HTTP Body" message is a print statement I've added to the client, it prints the HTTP body before it is send over the wire. URL params and HTTP Headers are being included in the body of the HTTP message before they are sent.

**Comment by rossjones** [comment]
Doesn't https://github.com/bacalhau-project/bacalhau/blob/75e82d0436e2f9caa63725723e2844680a212bb3/pkg/publicapi/apimodels/base_requests.go#L9-L13 need to include json:"-" as well as query:"-".

**Comment by wdbaruni** [comment]
yeah looks like thats the issue

**Comment by frrist** [comment]
Rather than embed these fields in our API Model structures, would it be worth considering an alternative of defining explicit payload structures to separate concerns regarding payload, params, and headers? In this way the payload structure explicitly contains only the HTTP payload, rather than the payload and other ancillary fields related to the request.

My motivation for such a change is a cleaner, more intuitive API model that makes it easier for other developers to understand and use. For example, imagine:
- How the documentation reads:  `BasePutRequest` and `BaseRequest` are not a part of the required payload despite being present in it's structure, for example: https://pkg.go.dev/github.com/bacalhau-project/bacalhau@v1.2.0/pkg/publicapi/apimodels#PutJobRequest 
- The swagger docs generate for these types will look similar without careful handling of tags.
