### ISSUE TITLE
DX Improvement: Bacalhau submit could work with non-uploaded file?

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#323]
ETA: 2023Q2

Repurposing this bug as general local developer improvement

Imagine that the CLI saw a small file (<1GB?) locally and uploaded it inline? During the submit? Not sure about this because it might change the format of the command after it's been executed or be slow. How hard is it to generate a CID against a file and see if it's already uploaded?

**Comment by js-ts** [comment]
we can use ipfs add -r --only-hash <file-name> it calculates the CID of the file without uploading it ipfs, and then we do ipfs ls to check the contents of the file or some other way to verify the file is already there or something like that

**Comment by Bubblyworld** [comment]
Yeah, another option is the `go-cid` library, which is now upgraded to latest (thanks for chasing people on that!). Going to need to do similar stuff for job spec/result caching which I'll get done tomorrow: #246 #247

**Comment by Bubblyworld** [comment]
I think we should probably avoid shelling out to `ipfs` if possible for users.
