### ISSUE TITLE
Sporadic issues shutting down devstack cleanly

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#3255]
Sometimes when closing devstack (with ctrl-c) it freezes after displaying "Shutting down devstack".  Sometimes, if this is done before the compute nodes are up and running work continues, showing `pkg/routing/node_info_publisher.go:106 > failed to publish node info error="context canceled"` before freezing. 

Often end up having to run `kill -9 $(jobs -p)` after ctrl-z to recover the terminal.

**Comment by wdbaruni** [comment]
didn't see this happen for some time, but keeping it open for a little longer

**Comment by rossjones** [comment]
I implemented https://github.com/bacalhau-project/bacalhau/pull/3434 to attempt to resolve this (and related issues), so it may actually be okay now.
