### ISSUE TITLE
run CI on draft PRs

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3279]

**Comment by frrist** [comment]
Fwiw I like being able to leave something in draft until I get it passing tests, then requesting review. But I don't do that all that frequently.

**Comment by aronchick** [comment]
it's now just "don't run on WIP"

**Comment by frrist** [comment]
Does WIP need to be in the title or as a label?

**Comment by wdbaruni** [comment]
@aronchick can you clarify the current behaviour and what WIP means?

**Comment by wdbaruni** [comment]
I dont think this is the case as tests don't run on draft PRs. Changing the title of the issue to revert things

**Comment by frrist** [comment]
CI currently runs on draft PR: e.g https://github.com/bacalhau-project/bacalhau/pull/4147
The label `WIP` doesn't exist.
