### ISSUE TITLE
The version command never fails

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#3308]
When running `bacalhau version` it should always print the client version.
It currently also attempts to get the server version, but if it is unable to do so does not explain why.
This surfaced when testing with TLS and when the version command failed with a TLS error, the error was silently swallowed.

Whilst it is fine that we allow the command to run without access to the network, 
we might consider any other error (e.g. there is a network but no TLS specified)
as an error and inform the user as such.

**Comment by frrist** [comment]
imo `bacalhau version` should follow similar practices to: `go version`, `git version`, `docker version` etc. We can use the `agent version` command to get the version of the server.

**Comment by rossjones** [comment]
> We can use the `agent version` command to get the version of the server.

Presumably after this change it means changing the update code to explicitly check the agent version.

**Comment by wdbaruni** [comment]
@frrist did we do any change here? I agree that version should mainly be about the client. We can include server version as a  best effort where we eat failures and have a small timeout window.

**Comment by frrist** [comment]
I haven't made any changes here, but since we agree that version should mainly be about the client I can pick this work up and implement the change.

**Comment by wdbaruni** [comment]
Go for it

**Comment by frrist** [comment]
https://github.com/bacalhau-project/bacalhau/pull/3968#issuecomment-2097525500
