### ISSUE TITLE
make bootstraping from an existing server easier

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3327]
```
bacalhau serve --bootstrap-server=192.168.1.5 --bootstrap-token=a98oegua9o8euga9oe8gua9e8ugaoe98 (if on)
```

**Comment by aronchick** [comment]
querying (with permission) should output the correct connection string to join a cluster, ideally one that can be an input to bacalhau serve. E.g.

```
curl myserver.com/connection-string | bacalhau serve
```

Or:
```
curl myserver.com/connection-string > foo.txt
cat foo.txt | bacalhau serve
```

Right now - the service outputs a set of strings I need to deconstruct into a real working server and/or things i need to manually fix to use from a client - e.g.:
```
export BACALHAU_NODE_CLIENTAPI_HOST=0.0.0.0
```

**Comment by wdbaruni** [comment]
we no longer need a connection string or multiple flags to connect to a network. We only need the requester's ip address (and optionally a token), which is similar to your suggestion of only providing `--bootstrap-server=ip`, except we don't need another service for bootstrapping as the requester node is doing that
