### ISSUE TITLE
Issues and inefficiencies with Makefile and build process

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#3398]
### Problems
- [ ] Issues about unsorted args passed to comm command (PR https://github.com/bacalhau-project/bacalhau/pull/3399)
    - https://github.com/bacalhau-project/bacalhau/blob/main/Makefile#L187-L188
    - Should be:
    ```
    CMD_FILES := $(shell bash -c 'comm -23 <(git ls-files cmd | sort) <(git ls-files cmd --deleted | sort)')
    PKG_FILES := $(shell bash -c 'comm -23 <(git ls-files pkg | sort) <(git ls-files pkg --deleted | sort)')
    ```
- [ ] two generate directive https://github.com/bacalhau-project/bacalhau/blob/main/Makefile#L433 + https://github.com/bacalhau-project/bacalhau/blob/main/Makefile#L504 + https://github.com/bacalhau-project/bacalhau/blob/main/scripts/generate.sh (PR https://github.com/bacalhau-project/bacalhau/pull/3399)
- [ ] calling `make generate` to build swagger in CI: https://github.com/bacalhau-project/bacalhau/blob/main/.circleci/config.yml#L563 this does a lot more than swagger, it generates go code unrelated to API. (PR https://github.com/bacalhau-project/bacalhau/pull/3399)
- [x] webui builds everything even if nothing is different, takes 8 seconds for (omc). That's 8 seconds everytime we run make. We should only build/optimize it when it _changes_.
- [ ] go.work vs go.mod replace: https://github.com/bacalhau-project/bacalhau/pull/3389
    - We build the seemingly unused job-consumer with replace statements https://github.com/bacalhau-project/bacalhau/blob/main/apps/job-info-consumer/consumer/go.mod#L5. This isn't used. We should delete it. It carries a maintenance overhead as we must insure it builds when making code changes, extra toil
    - We build canaries by requesting the PR version from github and modifying its go.mod file: https://github.com/bacalhau-project/bacalhau/blob/main/ops/aws/canary/lambda/Makefile#L9. This means we won't catch build issue in canaries when running `make` locally as we never build them locally.
    - We have interweaved both of these dependencies into go.work: https://github.com/bacalhau-project/bacalhau/blob/main/go.work which is not file we should be committing to version control (perhaps there is a good reason in this case, unsure).
    - Finally we have weaved go.work into our CI process and use it to determine what out go version is.

**Comment by aronchick** [comment]
i'm not seeing the issue around webui building - and there doesn't appear to be a great alternative (https://stackoverflow.com/questions/33962411/webpack-compile-only-if-changed) 

we could do something around doing a regular hash of the entire directory, but it's not obvious that's a ton of savings (since, presumably you'd have to do a hash of the entire directory every time you built anyway to check to see if anything changed)

**Comment by aronchick** [comment]
btw, i fixed the "use go.mod" for versions in this commit: https://github.com/bacalhau-project/bacalhau/pull/3389/commits/0c55f007f2a085e43ba800e7d4d1777ff90622e7

**Comment by simonwo** [comment]
>webui builds everything even if nothing is different, takes 8 seconds for (omc). That's 8 seconds everytime we run make. We should only build/optimize it when it changes.

This is already meant to be how it works, it is meant to use the various package.json and package-lock.json files to detect when the build is outdated. Just adding that because likely whoever tries to fix this will not be starting from scratch.

**Comment by simonwo** [comment]
>We build the seemingly unused job-consumer with replace statements https://github.com/bacalhau-project/bacalhau/blob/main/apps/job-info-consumer/consumer/go.mod#L5. This isn't used.

It should be running somewhere against the prod network, and is meant to be collecting job history of all the jobs on the network. Is that not something we want anymore?

**Comment by simonwo** [comment]
>Finally we have weaved go.work into our CI process and use it to determine what out go version is.

We are using `.tool-versions` in various places now.

**Comment by frrist** [comment]
> This is already meant to be how it works, it is meant to use the various package.json and package-lock.json files to detect when the build is outdated. Just adding that because likely whoever tries to fix this will not be starting from scratch.

So building it every-time, even when nothing has changed is intentional? (or am I misunderstanding?) iirc it didn't used to be this way.
Are we aware of any work-arounds to constantly re-building it? Such as a make directive that only builds the 'bacalhau' binary and not the webUI?

> It should be running somewhere against the prod network, and is meant to be collecting job history of all the jobs on the network. Is that not something we want anymore?

I think we get this nearly for free via the requester nodes job store - @wdbaruni and I were discussing this earlier as it pertained to metrics. iirc we stopped running it after migrating GCP accounts.
And, for what it's worth, I don't think it currently builds. Last I check it's referencing types that no longer exist, such as `node.JobInfoTopic` - I suspect they were just moved.

-----------------

The breakages with the job-info-consumer sort of dove-tail with the last point in the OP.
> Finally we have weaved go.work into our CI process and use it to determine what out go version is.

We don't actually build everything, locally at least far as I am aware, when we run make. This can result in CI runs failing due to build errors in other packages that we could have caught locally. Or in the case of the job-info-consumer, we find out its broken later when we try and use it.
