### ISSUE TITLE
authentication writes token to even if request fails to authenticate

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#3401]
## Reproduce:

Using these policies with token `"abc"`: 
https://github.com/bacalhau-project/bacalhau/blob/main/pkg/authn/ask/ask_ns_secret.rego
https://github.com/bacalhau-project/bacalhau/blob/main/pkg/authz/policies/policy_ns_anon.rego

### Attempt to query an authenticated endpoint, enter an invalid token, request fails
```bash
~> bacalhau --api-host=0.0.0.0 --repo=/home/frrist/.bacalhau2/ job list
15:24:06.272 | INF pkg/repo/fs.go:81 > Initializing repo at '/home/frrist/.bacalhau2/' for environment 'production'
token: <input>
failed request: Unexpected response code: 403 ({
  "error": "code=403, message=",
  "message": ""
})
```
### See a token.json file exists
```bash
~> cat ~/.bacalhau2/tokens.json
{"http://0.0.0.0:1234":"<omitted>"}
```
### Subsequent requests fail
```bash
~> bacalhau --api-host=0.0.0.0 --repo=/home/frrist/.bacalhau2/ job list
failed request: Unexpected response code: 403 ({
  "error": "code=403, message=",
  "message": ""
})
```

**Comment by simonwo** [comment]
I don't think the 403 is from the auth code, it's actually just the request failing in the same way it does subsequently. 

The issue here is that the token that is generated used a wildcard namespace which actually isn't supported in any of the authz policies.
