### ISSUE TITLE
auth token written when not required. 

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#3402]
## Reproduce
Using these policies with token `"abc"`: 
https://github.com/bacalhau-project/bacalhau/blob/main/pkg/authn/ask/ask_ns_secret.rego
https://github.com/bacalhau-project/bacalhau/blob/main/pkg/authz/policies/policy_ns_anon.rego
### when asked for a token, press enter, don't type anything
```
~> bacalhau --api-host=0.0.0.0 --repo=/home/frrist/.bacalhau2/ node list
15:37:54.144 | INF pkg/repo/fs.go:81 > Initializing repo at '/home/frrist/.bacalhau2/' for environment 'production'
token: <just press enter>
 ID        TYPE       LABELS  CPU  MEMORY  DISK  GPU 
 QmchH1Ym  Requester  
 ```   
 ### observe a token is created anyways
 ```                            
~> cat ~/.bacalhau2/tokens.json
{"http://0.0.0.0:1234":"<omitted>"}
```

**Comment by simonwo** [comment]
Yes, dumbo bug, the rule that checks whether the secret is valid is never actually referenced.
