### ISSUE TITLE
DX Improvement: We need more validation on incoming jobs

### ISSUE THREAD

**Issue by binocarlos** [bacalhau-project/bacalhau#342]
ETA: 2023Q2

I just had a bit of a run around debugging a problem in production and the cause was missing job spec fields

This ended up with the docker executor failing because it was trying to do `docker pull` on an empty string

We should have much stronger validation on incoming jobs and perhaps have a method in each executor that will validate the job spec - this could happen on the server and issue the error back to the client across the wire

**Comment by simonwo** [comment]
I have today (live on stream!) encountered the same issue. So still a problem.
