### ISSUE TITLE
When tracing is enabled spans contain invalid UTF-8 string fields

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#3436]
An error message is show:
```
ERR pkg/telemetry/common.go:18 > Error occurred while handling spans error="traces export: string field contains invalid UTF-8"
```
It's not immediately obvious which span is causing this error. It may be tracing data emitted from bacalhau, or it could be coming from a library bacalhau uses (e.g. Kubo) that produces invalid traces - more investigation needed.

**Comment by simonwo** [comment]
I tracked this down as part of #2960 and determined that it was spans from inside Kubo that caused this.

**Comment by wdbaruni** [comment]
This doesn't seem to be an issue anymore. Besides, we are no longer enabling tracing of ipfs http. We should only trace our part of the code and usage of ipfs
https://github.com/bacalhau-project/bacalhau/commit/2e0c32949bba96bce07bcf50df14328ac1900463#diff-64197669ff5fcee9f0500d3498b01594723be228ba52182b2813c2ce60507ca0L53
