### ISSUE TITLE
if /usr/local/bin doesn't exist, install on intel Mac fails

### ISSUE THREAD

**Issue by mgannholm** [bacalhau-project/bacalhau#3494]
tried to install bacalhau with the curl cmd, and got "Failed to install bacalhau". There was a 120MB file at /usr/local/bin. Deleted it and tried again, same result. Deleted the file, executed `sudo mkdir /usr/local/bin` -- then the curl install works

**Comment by simonwo** [comment]
Hi @mgannholm, I've just pushed an update to the installation script to make the directory if it doesn't exist. Can you check whether that resolves the issue for you?

**Comment by mgannholm** [comment]
same undesired result executing

curl -sL https://get.bacalhau.org/install.sh | bash

did you mean for me to test it a different way?

**Comment by mgannholm** [comment]
Yes, it works! thanks
