### ISSUE TITLE
Deploy from source is failing

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3533]
I am trying to deploy to staging from source, but build is failing due to :

```
➤ YN0000: · Done in 18s 775ms
/bacalhau /
Makefile:83: "Pre-commit is not installed in .git/hooks/pre-commit. Please run 'make install-pre-commit' to install it."
find: ‘webui/build’: No such file or directory
cd webui &&  --push +all
/bin/sh: 1: --push: not found
make: *** [Makefile:171: build-webui] Error 127
^C
(failed reverse-i-search)`sudo': ^C
```

This is how we are installing bacalhau from source in our environemnts:
```
function install-bacalhau-from-source() {
  echo "Installing Bacalhau from branch ${BACALHAU_BRANCH}"
  # make sure we have the desired version of nodejs to build webui
  curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  sudo apt-get -y install --no-install-recommends jq nodejs make
  git clone --branch "${BACALHAU_BRANCH}" https://github.com/bacalhau-project/bacalhau.git
  pushd bacalhau
  pushd webui && corepack enable && yarn set version stable && yarn install && popd
  make build-bacalhau
  sudo mv ./bin/*/*/bacalhau /usr/local/bin/bacalhau
  popd
}
```

**Comment by wdbaruni** [comment]
I believe it is related to this change https://github.com/bacalhau-project/bacalhau/commit/9b3ca23f145b0eca392c0986b49b41d90ed78aa1#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

@aronchick can you confirm?

**Comment by rossjones** [comment]
Since we've a dependency on earthly now, you have to have it installed locally to build.  We could probably do with clear docs on how to do that. I got it working by going to https://earthly.dev, signing in with github and then following the first two steps at https://cloud.earthly.dev/rossjones/tutorial/cli

**Comment by aronchick** [comment]
Correct - we should add a make file check to ensure that people have earthly installed. That’s the failure here.

**Comment by aronchick** [comment]
But is this the right way to deploy? Should we be running make on the production servers? Shouldn’t we just be laying down the source code already checked in, linked, compiled, etc?

**Comment by rossjones** [comment]
We also use make as part of our day to day dev work (make devstack, make test etc), and without earthly installed things like make build won't run and break workflow for anyone that builds + tests.

**Comment by aronchick** [comment]
PR -> https://github.com/bacalhau-project/bacalhau/pull/3540

**Comment by aronchick** [comment]
@rossjones my point about "make on the server" is that because builds are non-deterministic, we could THEORETICALLY be rolling out code that's different than we built in CI. We have a pipeline and binaries, shouldn't we just use them?

**Comment by wdbaruni** [comment]
@aronchick Yeah we normally don't deploy from source, but we have to option to test and deploy changes before merging to main or cutting a release. 
https://github.com/bacalhau-project/bacalhau/blob/2406ebac52017ac44e22e2ecf8268a67a4c3d276/ops/terraform/stage.tfvars#L1-L2

**Comment by wdbaruni** [comment]
Fix is on the way
https://github.com/bacalhau-project/bacalhau/pull/3541
