### ISSUE TITLE
Make build is broken

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#3538]
```bash
% make build
cd webui &&  --push +all
/bin/sh: --push: command not found
make: *** [build-webui] Error 127
```

Seems to assume we have `$EARTHLY` set locally.

**Comment by aronchick** [comment]
You need to install Earthly. I'll write a check for it.

**Comment by aronchick** [comment]
PR -> https://github.com/bacalhau-project/bacalhau/pull/3540
