### ISSUE TITLE
Node manager periodically prints to stdout

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#3591]
https://github.com/bacalhau-project/bacalhau/blob/297f1eaded9495e65c6e025c1290a2bf29d89448/pkg/node/manager/node_manager.go#L103

This should be a log message.

https://github.com/bacalhau-project/bacalhau/blob/297f1eaded9495e65c6e025c1290a2bf29d89448/pkg/node/manager/node_manager.go#L146

Ahem.

**Comment by rossjones** [comment]
Fixed in https://github.com/bacalhau-project/bacalhau/pull/3585, somehow missed in review.
