### ISSUE TITLE
WebUI cannot access authenticated bacalhau node

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#3641]
When a bacalhau cluster is created that requires authentication the WebUI is unable to communicate with its API as the WebUI does not provide the required authentication headers.

**Comment by frrist** [comment]
Additionally we will need a way to modify the port the WebUI uses to access bacalhau. Since when bacalhau is run with TLS enabled the RPC is served on port 443 rather than the insecure default of 1234

**Comment by simonwo** [comment]
Notes on what needs to be done are here: https://docs.bacalhau.org/dev/auth_flow#authnz-in-the-web-ui
