### ISSUE TITLE
Unable to run private cluster

### ISSUE THREAD

**Issue by georgesmith9914** [bacalhau-project/bacalhau#3654]
Steps:

1. I start requester node on ubuntu:
bacalhau serve --node-type requester

It prints on console:
To connect another node to this one, run the following command in your shell:
bacalhau serve --node-type=compute --network=libp2p --peer=/ip4/10.2.0.4/tcp/1235/p2p/QmeKmFPPkBdSxGySxYDf7QZXChXucrmN6LzzXYDZMsPMg3 --private-internal-ipfs --ipfs-swarm-addrs=/ip4/127.0.0.1/tcp/41799/p2p/QmRf4vs8qjVVdjk8hKQHM8kgUG6s3tafB7ueYKUFiRh8if

2. I try to connect to requester node in another console in the same host in a different directory.
It always gives error -

ERR github.com/libp2p/go-libp2p@v0.27.8/p2p/host/routed/routed.go:153 > got wrong peer error="routing failure: provided addrs for different peer" [gotPeer:] [logger-name:routedhost] [wantedPeer:QmeKmFPPkBdSxGySxYDf7QZXChXucrmN6LzzXYDZMsPMg3]
07:53:35.165 | WRN pkg/libp2p/host.go:161 > Error connecting to peer, continuing... error="dial to self attempted" [NodeID:QmeKmFPP] [addresses:["/ip4/10.2.0.4/tcp/1235"]] [peer:QmeKmFPPkBdSxGySxYDf7QZXChXucrmN6LzzXYDZMsPMg3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x237b91a]

**Comment by rossjones** [comment]
libp2p doesn't like dialling to the same machine, hence the "dial to self attempted" error.

Options are:

* Use a hybrid node `bacalhau serve --node-type requester,compute`
* Use NATS `bacalhau serve --node-type requester --network nats`
* Ensure compute is on a different machine/VM.
