### ISSUE TITLE
Two errors with approving nodes

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3683]
First:

root@global-lb:/home/itsadashuser# bacalhau node list --help
List info of network nodes.

Usage:
  bacalhau node list [flags]

Flags:
...
      --order-by string     Order results by a field. Valid fields are: id, type, available_cpu, available_memory, available_disk, available_gpu
...

Order by "approval (or whatever the field is)" is not listed.

```
root@global-lb:/home/itsadashuser# bacalhau node list --order-by approval
failed request: Unexpected response code: 400 ({
  "error": "code=400, message=invalid order_by",
  "message": "invalid order_by"
})
root@global-lb:/home/itsadashuser#
```

Passing raw errors from the server back as a 400 error should never be done

**Comment by rossjones** [comment]
Might be worth putting the raw errors into another ticket because that's not specific to approval or node tasks, it is all of the v2 API

**Comment by wdbaruni** [comment]
tracking improving returned errors here https://github.com/bacalhau-project/bacalhau/issues/3791
