### ISSUE TITLE
Incorrect state when cancelling job

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#3698]
When calling `bacalhau cancel` on a job, the logs show the following info, but two errors to do with the state of the job.
It's almost like the job is being cancelled twice with the second entry complaining ...

```
19:13:12.103 | INF pkg/publicapi/middleware/logger.go:50 > 9128751d-7748-40a8-9c0c-c9c7ad178081] [Method:POST] [NodeID:node-0] [Referer:] [RemoteAddr:127.0.0.1] [RequestID:] [Size:702] [StatusCode:200] [URI:/api/v1/requester/cancel] [UserAgent:Go-http-client/1.1]
19:13:12.109 | INF pkg/executor/docker/handler.go:172 > killing the container [container:dc451521008e2437d6d54e8058d3dc5909d9031c6d717f188c573487535c73f8] [execution:e-50dd14d0-c873-43b7-a49a-bda5f86889ce] [job:9128751d-7748-40a8-9c0c-c9c7ad178081]
...
19:13:13.233 | INF pkg/executor/docker/handler.go:189 > removing container [container:dc451521008e2437d6d54e8058d3dc5909d9031c6d717f188c573487535c73f8] [execution:e-50dd14d0-c873-43b7-a49a-bda5f86889ce] [job:9128751d-7748-40a8-9c0c-c9c7ad178081]
19:13:13.242 | INF pkg/executor/docker/executor.go:217 > received results from execution [executionID:e-50dd14d0-c873-43b7-a49a-bda5f86889ce]
19:13:13.242 | INF pkg/compute/executor.go:195 > cleaning up execution [NodeID:node-1] [execution:e-50dd14d0-c873-43b7-a49a-bda5f86889ce] [job:9128751d-7748-40a8-9c0c-c9c7ad178081]
....
19:13:13.242 | ERR pkg/compute/executor.go:480 > Publishing execution e-50dd14d0-c873-43b7-a49a-bda5f86889ce failed error="execution e-50dd14d0-c873-43b7-a49a-bda5f86889ce is in state Cancelled but expected one of [Running]" [NodeID:node-1] [execution:e-50dd14d0-c873-43b7-a49a-bda5f86889ce] [job:9128751d-7748-40a8-9c0c-c9c7ad178081]
....
19:13:13.242 | ERR pkg/compute/executor.go:488 > Failed to update execution (e-50dd14d0-c873-43b7-a49a-bda5f86889ce) state to failed: execution e-50dd14d0-c873-43b7-a49a-bda5f86889ce is in terminal state Cancelled and cannot transition to Failed error="execution e-50dd14d0-c873-43b7-a49a-bda5f86889ce is in terminal state Cancelled and cannot transition to Failed" [NodeID:node-1] [execution:e-50dd14d0-c873-43b7-a49a-bda5f86889ce] [job:9128751d-7748-40a8-9c0c-c9c7ad178081]
```

**Comment by wdbaruni** [comment]
This is still the case with 1.4.0. To clarify, the job state is correct, but the logs on the compute nodes are the ones misleading:

This is a description of a job that has been stopped
```
→    bacalhau job describe j-e209ab04-285c-4930-b908-e8d0e2e6772a
ID            = j-e209ab04-285c-4930-b908-e8d0e2e6772a
Name          = j-e209ab04-285c-4930-b908-e8d0e2e6772a
Namespace     = default
Type          = batch
State         = Stopped
Message       = Job requested to stop before completion
Count         = 1
Created Time  = 2024-06-26 13:27:08
Modified Time = 2024-06-26 13:27:35
Version       = 0

Summary

Job History
 TIME                 REV.  STATE    TOPIC       EVENT
 2024-06-26 15:27:08  1     Pending  Submission  Job submitted
 2024-06-26 15:27:10  2     Running
 2024-06-26 15:27:35  3     Stopped  Scheduling  Job requested to stop before completion

Executions
 ID          NODE ID     STATE      DESIRED  REV.  CREATED  MODIFIED  COMMENT
 e-fdf5f485  n-6e8998ad  Cancelled  Stopped  7     37s ago  10s ago   Accepted job

Execution e-fdf5f485 History
 TIME                 REV.  STATE              TOPIC            EVENT
 2024-06-26 15:27:08  1     New
 2024-06-26 15:27:08  2     AskForBid
 2024-06-26 15:27:10  3     AskForBidAccepted  Requesting Node  Accepted job
 2024-06-26 15:27:10  4     AskForBidAccepted
 2024-06-26 15:27:10  5     BidAccepted
 2024-06-26 15:27:35  6     BidAccepted        Scheduling       Execution stop requested because job has been stopped
 2024-06-26 15:27:35  7     Cancelled
```

**Comment by udsamani** [comment]
This is happening, mainly because we wait for the job execution to complete, and eventually transition the job state to completion. However, this is problematic if we cancel the job. As a cancellation of job, would be like normal closure of execution, and eventually the [`Run`](https://github.com/bacalhau-project/bacalhau/blob/main/pkg/compute/executor.go#L294) function would try to mark the job as `Completed`, when it has already been `Cancelled`. 

This is the cause of first error log we see in compute node logs. At the same time in this [`Run`](https://github.com/bacalhau-project/bacalhau/blob/main/pkg/compute/executor.go#L305) function we try to mark the job as `Failed`, if there is some error(  the error raised when we try to transition it to complete, when it is already marked cancelled). This is the cause of second log. 

There are couple of things we can do here 

- Before marking the job as completed, we take a look that if the job is already cancelled we just exit.
- Ignore the error in case the job is already in one of the terminal state. Ideally, if job has already reached to a terminal state, we should not overwrite it. Meaning we can log it as warn but no need to raise an error for it. We can simply ignore it. 

Let me know what you folks thing @wdbaruni  @frrist  !

**Comment by wdbaruni** [comment]
> Before marking the job as completed, we take a look that if the job is already cancelled we just exit.

There will always be race conditions if you don't check and update atomically and within a transaction. You can minimize the window, but you can never prevent it. That is why with have an update condition at the execution store level that verifies the entry in boltdb is in a desired state before updating

> Ignore the error in case the job is already in one of the terminal state. Ideally, if job has already reached to a terminal state, we should not overwrite it. Meaning we can log it as warn but no need to log it as error. We can simply ignore it.

Yeah thats what the update condition is doing where we don't overwrite the state if it is terminal, and we return an error instead. What we should be doing is define more error types at the execution store level, have a specific error type such as `ErrAlreadyTerminal` or something like that, and then have the executor ignore logging the error

In addition to that, we should evaluate not calling `handleFailure` inside [Run](https://github.com/bacalhau-project/bacalhau/blob/ec2e2d69eb091605fd69da6ba9d9e2039c08eb0c/pkg/compute/executor.go#L305) method if the context was cancelled, but we need to evaluate what other cases the context can be cancelled and whether we should fail the execution in those cases or not

I think having more error types for now should be more than enough
