### ISSUE TITLE
Bacalnetes: Bacalhau cluster implemented as a long running Kubernetes cluster

### ISSUE THREAD

**Issue by wesfloyd** [bacalhau-project/bacalhau#372]
ETA: 2023Q1

Can we keep this issue open to track use cases for decentralized long running Kubernetes clusters, even if it is far out on the roadmap or part of a child project?

Examples:
[Ocean DAO C2D](https://docs.google.com/document/d/1lgSIKkjCasJG4vR4aynKmpf7hmD-NpZsMnxGPao1RkI/edit?usp=sharing)
[Dask on Kubernetes](https://docs.dask.org/en/stable/deploying-kubernetes.html) // this could also be the solution for #371 
[Spark on Kubernetes](https://spark.apache.org/docs/latest/running-on-kubernetes.html#prerequisites)

**Comment by js-ts** [comment]
@wesfloyd we can use somrthing like [KIND](https://kind.sigs.k8s.io/) Kubernets in Docker

**Comment by lukemarsden** [comment]
k8s clusters are built on [Raft consensus](https://raft.github.io/) which makes them centralized (at least, CP in the CAP theorem) however I am open to k8s clusters forming subsets of the bacalhau network as a convenient coordination mechanism for providers, if they want to. We can probably let them build that implementation themselves though.

**Comment by aronchick** [comment]
@wesfloyd can you specify what the user scenario is that they're trying to solve for here? K8s should just be an implementation detail. NOTE! Supporting existing workloads could be a reason!

**Comment by wesfloyd** [comment]
Based on our last conversations, it sounds like the OceanDAO folks can accommodate our current architecture. Otherwise I hoped to use this direction as a shortcut for DASK and Spark support, although in fairness no users have asked for this yet explicitly.

I can close this ticket until the need arises again
