### ISSUE TITLE
webui job detail broken

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#3724]
When loading some job detail on a local webui, such as `http://127.0.0.1:2021/JobDetail/f81ffa06-8e97-4ce8-8c66-f12cd3378b26` the page fails to load, and the console shows it is attempting to load `http://127.0.0.1:2021/JobDetail/assets/index-DtYsxs3q.js`.  Removing `JobDetail` from that URL loads the asset.

**Comment by simonwo** [comment]
See also #3170.
