### ISSUE TITLE
Non-existent docker image, incorrect devstack error.

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#3754]
When running a docker job with a non-existent image, we now get the correct error (see node-2 below).
Unfortunately the other two nodes (node-3 and node-1) seem to report an image platform error.  

This appears to be a devstack quirk (possibly the cache) as running 2 compute nodes and a requester gives the correct error from both compute nodes. A second run with the separate nodes does raise `rejected bid: this node does not support the available image platforms [] (supports [linux/arm64]). bid rejected` though. 

```
❯ ./bin/darwin/arm64/bacalhau docker run no-existy something
Using default tag: latest. Please specify a tag/digest for better reproducibility.
Job successfully submitted. Job ID: 96a57407-00bf-48e2-84a6-8c0b323d131e
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

        Communicating with the network  ................  done ✅  0.0s
           Creating job for submission  ................  err  ❌  2.0s

Error submitting job: not enough nodes to run job. requested: 1, available: 0. 
        Node node-1: job rejected
        Node node-2: job rejected
        Node node-3: job rejected
Job Results By Node:
• Node node-2: 
        rejected bid: Could not inspect image "no-existy" - could be due to repo/image not existing, or registry needing authorization: Error response from daemon: errors:
        denied: requested access to the resource is denied
        unauthorized: authentication required. bid rejected
• Node node-3, node-1: rejected bid: this node does not support the available image platforms [] (supports [linux/arm64]). bid rejected

To get more details about the run, execute:
        bacalhau describe 96a57407-00bf-48e2-84a6-8c0b323d131e
```

**Comment by rossjones** [comment]
It's possible this error is the docker cache caching manifests even if we failed to find one (subsequent requests retrieving an empty manifest).

**Comment by simonwo** [comment]
Ah caching is an intersting root cause. FYI #3513 is the same issue.

**Comment by rossjones** [comment]
Turns out if isn't caching, it's ignoring errors that is the cause.
