### ISSUE TITLE
Print CLI warning when calling any of the legacy CLIs

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3833]
Print a deprecation message when users call legacy CLIs, such as `bacalhau describe` and `bacalhau list`, and give them a hint to use `bacalhau job describe` and `bacalhau job list` commands instead

**Comment by frrist** [comment]
addressed in https://github.com/bacalhau-project/bacalhau/issues/3838 epic via separate issues.
