### ISSUE TITLE
Update `docker/wasm run` flags to match new APIs

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3836]
Update `bacalhau docker run` and `bacalhau wasm run` flags to match new API and models. As an example, `--concurrency` should be renamed to `--count`.

We should continue to support old flag names to avoid breaking existing jobs and examples in a single release. Though only new flag names should be printed when calling `bacalhau docker run --help`

**Comment by frrist** [comment]
covered by https://github.com/bacalhau-project/bacalhau/issues/3837 and https://github.com/bacalhau-project/bacalhau/issues/4021
