### ISSUE TITLE
Rename ListX responses to `Items`

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3839]
Instead of having ListJob, ListJobExecutions,... return an array of `Jobs`, `Executions`,... , unify this to always return `Items` array along with `NextToken`

Preferably we should do this before announcing V1 API deprecation. Also would be nice to do this while maintaining backward compatibility with existing clients. Maybe we should explore adding bacalhau version as an http header, and return `Items` only for new versions? Up for discussion

**Comment by wdbaruni** [comment]
@frrist please prioritize this as we want to get it out for 1.4

**Comment by frrist** [comment]
Sorry, but I am not sure what the ask is here. Do we want to add struct tags to the listed results? e.g.
```go
type ListJobResultsResponse struct {
	BaseListResponse
	Results []*models.SpecConfig `json:"Items"`
}

type ListJobHistoryResponse struct {
	BaseListResponse
	History []*models.JobHistory `json:"Items"`
}

type ListJobsResponse struct {
	BaseListResponse
	Jobs []*models.Job `json:"Items"`
}
```
Or are we asking for a generic? e.g.
```go
type ListResponse[T any] struct {
	BaseListResponse
	Items []T
}
```

**Comment by wdbaruni** [comment]
My initial thought is:
```
type ListJobResultsResponse struct {
	BaseListResponse
	Items []*models.SpecConfig
}

type ListJobHistoryResponse struct {
	BaseListResponse
	Items []*models.JobHistory
}

type ListJobsResponse struct {
	BaseListResponse
	Items []*models.Job
}
```

but generics may be a better idea. Keep in mind that I don't want to break backward compatibility with 1.3.x clients, as mentioned in the issue description

**Comment by frrist** [comment]
To keep backwards compatibility with existing clients I think we'll need something like:
```go
type ListJobResultsResponse struct {
	BaseListResponse
	Results []*models.SpecConfig  // Deprecated
	Items   []*models.SpecConfig
}

type ListJobHistoryResponse struct {
	BaseListResponse
	History []*models.JobHistory  // Deprecated
	Items   []*models.JobHistory 
}

type ListJobsResponse struct {
	BaseListResponse
	Jobs  []*models.Job  // Deprecated
	Items []*models.Job 
}
```
After some amount of time we'll then need to remove the deprecated fields. wdyt?

**Comment by frrist** [comment]
We need the client to include the version in the header when making these requests to determine the field to populate. So if there isn't a version we populate both
