### ISSUE TITLE
Move away from global config

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3846]
We are currently using a global  `viper` instance to setup our config, which complicates testing and results in unpredictable behaviour, such as:
1. Whenever we initialize or load a repo, the repo's configs are feed into the same global viper instance which replaces any default configuration. Meaning any repo loaded after the first one, will use the first repo's config as its own defaults
2. Calling global getters, such as `config.GetClientID()` wouldn't necessary return the ID of the client that will issue the requests. If another repo was loaded at a later point, then it will replace the global value of the client ID and the requests will be submitted using the latter one.
3. I've tried creating a repo per node in devstack, but couldn't get that to work mainly because of the uncertainty on which clientID will submit the requests , which caused this test case to fail https://github.com/bacalhau-project/bacalhau/blob/badd1ce5fd9508bd615f9a8e08bd8ce44d2eceb7/pkg/test/devstack/timeout_test.go#L112

**Comment by frrist** [comment]
via https://github.com/bacalhau-project/bacalhau/pull/3959
