### ISSUE TITLE
Clean up an error when multiple bacalhau serves are running

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3889]

**Comment by wdbaruni** [comment]
I believe this is about `bacalhau serve` failing with no clear error message when another server is running on the same host. Usually this is related to trying to use an already reserved port or file by the first server. We need to improve the error somehow, and test that  you can actually run two separate instances on the same host. Not recommended for production purposes, but for testing

**Comment by wdbaruni** [comment]
This is what we have with v1.5.0
```
Error: orchestrator port 4222 is already in use
Hint:  To resolve this, either:
1. Check if you are already running the orchestrator
2. Stop the other process using this port
3. Configure a different port using one of these methods:
   a. Use the `-c Orchestrator.Port=<new_port>` flag with your serve command
   b. Set the port in a configuration file with `bacalhau config set Orchestrator.Port=<new_port>`
```
