### ISSUE TITLE
Resource allocation policy is inconsistent between bidding strategy and executor

### ISSUE THREAD

**Issue by alaric-rd** [bacalhau-project/bacalhau#3898]
AvailableCapacityStrategy (pkg/bidstrategy/resource/capacity_available_strategy.go) bids for a job if the sum of running capacity (system capacity not currently used by running jobs) and available queue capacity (capacity not reserved by jobs in the compute node's queue) is more than the resource requirements of the job.

ExecutorBuffer (pkg/compute/executor_buffer.go) will start a job if the resources required are less than the running capacity. If not, it will check to see if the resources required are less than the available queue capacity. If so, it will queue it. Otherwise, it will fail the execution, citing insufficient resources.

This inconsistency presents a problem - if a job needs more resources than are available in the queue, but less than the sum of that and the running capacity, the job will be bid for (running+queue resources are sufficient) but then fail at execution time (neither running, nor queue, resources are sufficient).

This can be demonstrated by running a single node with 0.8 CPUs (the default) then submitting three jobs that demand 0.5 CPUs (a `sleep 10` will suffice). The first will run as there is capacity, the second will be queued as only 0.3 CPUs of running capacity remain, then the third will fail as there's now 0.3 CPUs of running capacity and 0.3 CPUs of queue capacity; 0.6 CPUs is enough to bid for the job, but not enough to execute it or enqueue it.

Possible solutions:

1) Make the bidding strategy use the same logic as the executor - there must be enough running capacity OR queue capacity to bid for the job.

2) Make the executor use the same logic as the bidding strategy - the simplest way to do this might be to change how capacity is tracked, replacing the "queue capacity" with a "total capacity" that is initialised to twice the running capacity, tracking queue AND running capacity, and making the bidding strategy and the executor both just use the total capacity to gatekeep jobs; with the running capacity just used to decide when to start a job from the queue.

3) Make the executor just trust the bidding strategy, and enqueue any job that it can't immediately run regardless of queue capacity; in effect letting the queue "borrow" capacity from currently unused running resources.

**Comment by wdbaruni** [comment]
I am no longer seeing an inconsistent behaviour. This might've been fixed as part of queueing work
