### ISSUE TITLE
Deferring jobs when there are no free compute nodes

### ISSUE THREAD

**Issue by alaric-rd** [bacalhau-project/bacalhau#3904]
-  Allow the orchestrator to retain jobs that it can't schedule immediately because resources are currently in use by known nodes, or a node has temporarily dropped out of the network
-  Reliability across orchestrator restarts, but not reliability in face of the orchestrator node being deleted
-  Allow the requester to orchestrate things that it might not ever be able to orchestrate (e.g. accept a job with GPUs even though there are currently no GPUs attached).

There is a persistent job queue in the requester already; the work required here is to:

1. Find where jobs get cancelled because of a resource shortage, and stop them getting cancelled. From what I've seen so far, compute nodes will bid on jobs they don't have capacity for, then reject them upon execution, which might mean we need to examine two cases: one where no compute node bids, and one where the execution is rejected.
2. In that case, re-queue them in a suitable manner. The easiest would probably be to put them to the back of the queue, but that might lead to the requester spinning on re-bidding for them - some kind of "Try again in 1 minute" or a separate pending-jobs queue that the scheduler examines at a rate-limited pace, or even only examines when a job completes (thereby freeing up capacity somewhere) or a new compute node joins.

**Comment by wdbaruni** [comment]
tracked in https://github.com/bacalhau-project/bacalhau/issues/3987
