### ISSUE TITLE
Tell StorageProviders where to write inputs

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#3905]
Currently each StorageProvider implementation, makes a decision in their 'New*()` function as to which local directory they will write inputs to.  They do this by finding the configured storage directory, and then creating a temporary directory named after the type of StorageProvider.  This means the structure becomes:

```
/data 
/data/bacalhau-s3/*
/data/bacalhau-ipfs/*
/data/bacalhau-local/*
```

As this decision is made in the New() method as the provider is created, there is no opportunity to tell the provider where we want it to save the data it downloads.  Ideally we would provide a directory to the StorageProvider's PrepareStorage method, so that it would be

```go 

# Current
func (sp *StorageProvider) PrepareStorage(ctx context.Context, storageSpec models.InputSource) 
(storage.StorageVolume, error) {

# Proposed 
func (sp *StorageProvider) PrepareStorage(
    ctx context.Context, 
    localDirectory string,
    storageSpec models.InputSource) 
(storage.StorageVolume, error) {
```

This would:

* Make testing easier/more-explicit
* Allow us to index stored data on the job/execution and not the provider's name
* Share data across executions in the same job 
* Remove the need for providers to generate a path from config and store it 
* Allow other components to take responsibility for cleanup, removing the need for the CleanupManager in StorageProviders

**Comment by wdbaruni** [comment]
@frrist planned to improve as part #4014
