### ISSUE TITLE
DX Improvement: Support -m flag in python WASM backend

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#392]
ETA: 2023Q2

python -m timeit '"-".join(map(str,range(100)))'

<img width="663" alt="image" src="https://user-images.githubusercontent.com/79689323/179346010-dc425126-e671-400f-b7c9-057ea5704e4e.png">

<img width="427" alt="image" src="https://user-images.githubusercontent.com/79689323/179599827-df4ceb26-230f-4a98-b0bb-e441fffe165d.png">

while porting some commands from docker to WASM, they couldn't be implemented in WASM to run CLI tools that I was using
eg 
bacalhau docker run \
-v QmTAQMGiSv9xocaB4PUCT5nSBHrf9HZrYj21BAZ5nMTY2W:/input \
-o output:/output jsace/ethereum-etl \
-- /bin/bash -c 'ethereumetl extract_csv_column --input ./input/transactions.csv --column hash --output ./output/transaction_hashes.txt'

its dockerfile
<img width="102" alt="image" src="https://user-images.githubusercontent.com/79689323/179346129-6a9e53c0-d5af-464c-a415-dba3d3037f87.png">

there is no other way to use it

I that it should support -m and we install the dependencies using a requirements.txt file also is there any way to support bash comamnds inside the WASM backend 

@lukemarsden

**Comment by aronchick** [comment]
it looks like this is the standard - https://github.com/spf13/cobra/issues/739

Is there something we should do here? e.g. give people a warning on unknown flags?

**Comment by aronchick** [comment]
part of tho problem is that this is a problem with our subtree being named "python" - they're not ACTUALLY executing python, they're naming something for us. Really not sure what to do about this.

**Comment by lukemarsden** [comment]
I think we should support `bacalhau run python -m`
