### ISSUE TITLE
Validation in API layer

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#3950]
Although we do normalize inputs, there's an oversight on the normalization of the optional publisher field if the job is posted directly to the API.

```shell
❯ curl  -H "Content-Type: application/json"  -d "@job.json" -X POST http://127.0.0.1:20000/api/v1/orchestrator/jobs
{
  "error": "code=400, message=1 error occurred:\n\t* task main validation failed: 1 error occurred:\n\t* publisher validation failed: nil spec config\n\n\n\n",
  "message": "1 error occurred:\n\t* task main validation failed: 1 error occurred:\n\t* publisher validation failed: nil spec config\n\n\n\n"
}
```

where the JSON file looks like the following (note, no publisher).

```json
{
  "Job": {
    "Name": "LogProcessorDuckDB",
    "Type": "batch",
    "Count": 1,
    "Namespace": "logging",
    "Constraints": [],
    "Tasks": [
      {
        "Name": "main",
        "Engine": {
          "Type": "docker",
          "Params": {
            "Image": "expanso/nginx-access-log-processor:1.0.0",
            "Parameters": [
              "--log-path",
              "/logs/**",
              "--start-time",
              "-1 day",
              "--query",
              "SELECT * FROM logs ORDER BY timestamp LIMIT 10",
              "-json"
            ]
          }
        },
        "Resources": {
          "CPU": "0.1",
          "Memory": "512MB"
        },
        "InputSources": [
          {
            "Target": "/logs",
            "Source": {
              "Type": "s3",
              "Params": {
                "Bucket": "bacalhau-usecases",
                "Key": "log-orchestration/part3_12/",
                "Region": "eu-west-1"
              }
            }
          }
        ]
      }
    ]
  }
}
```

**Comment by frrist** [comment]
So we don't forget. I did a bit of code spelunking with cuelang to try and address this in https://github.com/bacalhau-project/bacalhau/pull/3735. The idea was to define a schema in cue that we could use to validate job specs against. The resulting work allowed users to validate a job.yaml file against the cue schema via a command like: `cue vet -d "#Job" testdata/jobs/docker-output.yaml pkg/models/job-schema.cue` and have it return detailed errors on which fields were invalid by line number in the job spec. cuelang has a go sdk (cue is written in go) so it would be fairly straightforward to port this functionality into the bacalhau CLI or API to provide client and server side validation.
