### ISSUE TITLE
DX Improvements: give user more info in case that job is declined

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#404]
ETA: 2023Q2

Now that we have GPU support, we have a bigger worry about the user experience of submitting a job that no one has the right resources to perform. This ticket is about giving the user better feedback in that case.

The order of operations is like this:
* requestor node puts job on network
* compute nodes self-select as to whether to bid on the job or not
* requestor node decides which computes’ bids to accept

One change we could make would be to show in the UI how many compute nodes bid and how many bids were accepted, and as you say, adding reasons to give the user feedback. We could also consider adding a new message type in #2, “compute node declined to bid because […]” and surfacing that to the user, that way, if the user gets no bids for their job, they could at least see it was because “100/100 nodes had no GPUs or something”

See: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1658412853650569

**Comment by lukemarsden** [comment]
@wdbaruni you might wanna take a look at this

**Comment by wdbaruni** [comment]
Has this been covered by recent UX improvements? cc: @aronchick @binocarlos 

As for showing the reason on why a compute node declined to bid, I don't think that will scale well in terms of job state size and network bandwidth. We might introduce that when replacing GossipSub with direct calls

**Comment by simonwo** [comment]
We now do this since #3008.
