### ISSUE TITLE
Implement auto download flags and function on wasm and docker commands

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#4058]
Implement auto download flags and function for the docker and wasm CLI commands. This previously exists in the legacy printer, but ought to be moved to a separate method from the printing logic of a jobs status.
This change will follow #3837 and #4021

**Comment by wdbaruni** [comment]
@frrist did you discuss this with product? We need to bring this feature back before 1.4 if product prefers to keep this behaviour

**Comment by frrist** [comment]
@aronchick and @MichaelHoepler previously the `docker run` and `wasm run` commands had the following flags present that allowed/influenced downloading results from a job after it ran:
```
--download                                Should we download the results once the job is complete?
--download-timeout-secs duration          Timeout duration for IPFS downloads. (default 5m0s)
--output-dir string                       Directory to write the output to.
--raw                                     Download raw result CIDs instead of merging multiple CIDs into a single result
-g, --gettimeout int                      Timeout for getting the results of a job in --wait (default 10)
```
In #4020 and #4060 these flags were removed to simplify things. 

**Do we want to add these flags back in or leave them off?**

for what it's worth the command: 
`bacalhau docker run --wait --id-only -p=local ubuntu:latest echo "ehllo owrld" | xargs bacalhau job get`
achieves the same result.

**Comment by aronchick** [comment]
Drop them - but you need to deprecate.
