### ISSUE TITLE
HTTPS URLs aren't immutable

### ISSUE THREAD

**Issue by enricorotundo** [bacalhau-project/bacalhau#406]
ETA: 2023Q1

HTTPS URLs aren't content addressed, nor immutable. This makes them a potential source of nondeterminism.

A solution may be to modify HTTPS URLs (https://github.com/filecoin-project/bacalhau/issues/373) behaviour to copy files into IPFS first. This way it should bring in de-duplication too.

If data sits on IPFS we could detect changes and automatically trigger jobs.

**Comment by lukemarsden** [comment]
This is good because it adds data to IPFS

**Comment by wdbaruni** [comment]
I agree that http urls are not immutable and should mark the job as non-deterministic, but I don't understand the proposal and how it will mitigate the issue. Can you clarify what will the job spec look like?

**Comment by enricorotundo** [comment]
Related to https://github.com/bacalhau-project/bacalhau/issues/1971

**Comment by aronchick** [comment]
@wdbaruni still relevant?
