### ISSUE TITLE
API to retrive node config

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#4113]
Not obvious as to why?

repro:
```
bacalhau serve --orchestrators 192.168.1.30 & 

bacalhau config list
```

Notice node.network.orchestrators is not set.

**Comment by frrist** [comment]
The `bacalhau config list` command doesn't return the config of the agent/server it connects to, if that's what you were expecting?

**Comment by wdbaruni** [comment]
Maybe Dave is looking for something like `bacalhau agent config` that tells the configurations an agent/node is running with. I think there is value in that

**Comment by aronchick** [comment]
My expectation was that when you connect a compute node to an orchestrator with Bacalhau serve --type compute --orchestrators IP

The value of the orchestrator would be written to something that when you wrote bacalhau config list in a different process, it would show up.

If you started bacalhau yo using systemd for example, and logged into the machine, how would you know what machine this had connected to?
