### ISSUE TITLE
Document usage of Bacalhau cluster resulting from Google Cloud Deployment

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#4138]
We need to provide a section on our docs site that describes how to use a deployment of bacalhau on google cloud. The doc should include details on the following items:

- [x] How to connect to the requester node in the deployment https://docs.bacalhau.org/setting-up/marketplace-deployments/google-cloud-marketplace
  - API Address and port configuration
  - Authentication via API token
  
- [x] How to add more compute nodes to the network https://docs.bacalhau.org/setting-up/marketplace-deployments/google-cloud-marketplace
  - Orchestration address on requester
  - Compute authentication Token 
 
- [ ] How to interact with the Bacalhau node from within the VM
  - systemctl commands to start, stop, and restart the node
  - journalctl commands to view logs
  - mention the process is running as the `bacalhau` users
  - mention that the user will need to become root for iterations
  - Where the bacalhau repo is.
  - Where the bacalhau local data directory is.

**Comment by wdbaruni** [comment]
@frrist is this done?
