### ISSUE TITLE
Test `TestStreamConsumerClientGoingDown` is flaky

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4168]
Examples:
https://app.circleci.com/pipelines/github/bacalhau-project/bacalhau/13228/workflows/1a54ca69-849c-4b43-8bb5-5f0ecb22c3ec/jobs/177536/steps

https://app.circleci.com/pipelines/github/bacalhau-project/bacalhau/13228/workflows/1a54ca69-849c-4b43-8bb5-5f0ecb22c3ec/jobs/177537/tests

https://app.circleci.com/pipelines/github/bacalhau-project/bacalhau/13228/workflows/1a54ca69-849c-4b43-8bb5-5f0ecb22c3ec/jobs/177534/steps

**Comment by udsamani** [comment]
Easy to reproduce the test flakines.


![Image](https://github.com/bacalhau-project/bacalhau/assets/47295083/dc7babb3-9793-4ff8-b39d-8975f64219a0)
