### ISSUE TITLE
Include the InstallID in the Meta map of a job when submitting

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#4184]
When using the python SDK we can also attempt to find the InstallID from the `bacalhau config list` command. cc @udsamani for the python bits.

**Comment by frrist** [comment]
This issue is blocked on approval of https://github.com/bacalhau-project/bacalhau/issues/4218

**Comment by wdbaruni** [comment]
Will this be closed by https://github.com/bacalhau-project/bacalhau/pull/4238?

**Comment by frrist** [comment]
No it will be closed by a follow on to #4238 once its merged.
