### ISSUE TITLE
Bacalhau connect / delete no ability to reconnect

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#4198]
# Repro:

- start a cluster
- connect a compute node
- stop the compute node
- delete the node
- restart the node

# Expected
Node should be visible again

# Actual
Node not available

**Comment by wdbaruni** [comment]
This is an actual bug and related to how we persist the registration state in the compute node. We try to avoid having the compute node register each time during startup and skip if its local state says already registered, but this is wrong as the state can get out of sync, such as the scenario you mentioned. 

Will cover this as part of #3861 by 1.5 or early 1.6
