### ISSUE TITLE
When describing a job that doesn't exist bacalhau returns a 500 error instead of expected 404

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#4234]
### Bug Description
Run the command with a jobID that doesn't exist.
```
$ bacalhau job describe j-abcdefgh-ijkl-mnop-qrstu-vwzwzabdefg
```
observe the output:
```
06:41:13.987 | INF pkg/repo/fs.go:99 > Initializing repo at '/home/frrist/.bacalhau' for environment 'production'
Error: could not get job j-86588a34-9abf-414d-9148-94e21ddcb71b: Unexpected response code: 500 ({
  "error": "Job not found. ID: j-86588a34-9abf-414d-9148-94e21ddcb71b",
  "message": "Internal Server Error"
``` 

### Expected Behavior
This should produce a 404 error instead of 500.

### Bacalhau Versions
- **Agent Version**:  v1.4.0
- **CLI Client Version**: v1.4.0

**Comment by aronchick** [comment]
well.... TECHNICALLY the api should produce the 404 error with a message, but the UI should produce a 200 (because it was a valid exchange with the API)
