### ISSUE TITLE
Long Running Jobs

### ISSUE THREAD

**Issue by philwinder** [bacalhau-project/bacalhau#427]
ETA: 2023Q1

**Use Case**

As a user running jobs on the network, I need to run jobs that take a long time to complete. For example, 2 days.

**Tasks**

TODO

**Notes**

* The [Example workload](https://docs.google.com/document/d/1REL-C0WgbWzv_xd3DTJwpzc90stiUByTJzooFvUYV9c/edit?usp=sharing) is running on a 16GB machine and takes two days.
* There shouldn't be anything to prevent this from working now, but obviously infra changes or software updates would force recreation of the node or server that is running the job. So I guess we need some kind of drain and rolling update, to make sure we don't update whilst jobs are in flight.

**Comment by aronchick** [comment]
@lukemarsden @binocarlos does the localdb help with this?

**Comment by lukemarsden** [comment]
Once localdb supports sqlite it will, sorta, but we also need to switch our
deployment model to mutate VMs rather than swapping them out and support
resuming tracking jobs (long running containers) after a daemon restart.

**Comment by wdbaruni** [comment]
This is tricky and will depend on the framework running the job. If the job is just a pure python code running in a docker container for example, then we will lose progress whenever the compute node bounces. If on the other hand the job is a Spark or Flink application, then these frameworks support checkpointing and restoring from snapshots during deployments or failovers. We have discussed that Spark and Flink can be executor engines where the job is executed in a cluster owned by a single Compute Provider.

The other way would be to break the long running job into separate tasks in a DAG, and allow the DAG executor to resume from the last successful task during a failover
