### ISSUE TITLE
Using `--id-only` with `--follow` returns more than only the id and job output

### ISSUE THREAD

**Issue by AlexandreDoneux** [bacalhau-project/bacalhau#4292]
### Bug Description
When using `bacalhau docker run` with `--id-only` and `--follow` some indications other than the job id and job output are printed. For example with : 
```
bacalhau docker run --id-only -f ubuntu  echo hey
```

I have the following output : 
```
j-ffd4939f-e975-4bc7-9620-821230261dce
Job successfully submitted. Job ID: j-ffd4939f-e975-4bc7-9620-821230261dce
Waiting for logs... (Enter Ctrl+C to exit at any time, your job will continue running):

hey

```

### Expected Behavior
 The text other than the job id and job output shouldn't be printed. The following text should **not** be present : 
 
```
Job successfully submitted. Job ID: j-ffd4939f-e975-4bc7-9620-821230261dce
Waiting for logs... (Enter Ctrl+C to exit at any time, your job will continue running):
```

### Bacalhau Versions
- **Agent Version**: v1.4.0
- **CLI Client Version**: v1.4.0

### Host Environment

- Operating System: Ubuntu 22.04.1
- CPU Architecture: x86-64
- Any other relevant environment details: Issue occurred on a local devstack instance.

**Comment by wdbaruni** [comment]
Thanks Alex for reporting this issue. I am trying to understand the cases where `--id-only` and `--follow` should be used together. Most of the time you want to use `--id-only` when you want to pipe the job id into other commands or copy it such as:

```
bacalhau docker run --id-only ubuntu echo hello | xargs bacalhau job describe

bacalhau docker run --id-only ubuntu echo hello | pbcopy
```

I would say we should fail the command if both `--follow` and `--id-only` are provided, but I would like to know more about your desired behaviour incase I am missing something

**Comment by AlexandreDoneux** [comment]
My goal was to have info generated by the job and use it before the container shuts down. In my particular case the idea is to generate ssh keys in the container and provide them as a job feedback to be able to connect to the job container in ssh while the job is momentarily paused. 

`--id-only` allows me to more easily retrieve the job id and the feedback without additional unwanted messages.
