### ISSUE TITLE
Deploy a dedicated telemetry collector

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4319]
Set up and configure our own telemetry collection infrastructure. This should include considerations for scalability. Consider deploying on AWS using CDK as our IaC, ASG and ELB for auto-scaling up and down

**Comment by wdbaruni** [comment]
@frrist feel free to ask @udsamani for help with this one

**Comment by frrist** [comment]
@wdbaruni I believe we have deployed the collector to AWS, can you close this issue if this is complete?

**Comment by frrist** [comment]
I am going to close this, please re-open if this change hasn't landed
