### ISSUE TITLE
Orchestrators shouldn't have default publisher by default

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4390]
In v1.4.0, the default configuration for requester nodes is to have no default publisher by default as shown in https://github.com/bacalhau-project/bacalhau/blob/v1.4.x/pkg/config/configenv/production.go and in:
```
→ bacalhau config list | egrep "KEY|defaultpublisher"
 KEY                                                             VALUE
 node.requester.defaultpublisher
```

Though now we are changing the behaviour and setting `local` as the default publisher always:
https://github.com/bacalhau-project/bacalhau/blob/1ca678c752371f790e84220e6061e63d3aed5e32/pkg/config/types/default_config.go#L73-L75

**Comment by frrist** [comment]
Acceptance Criteria here is to not print the env vars.
