### ISSUE TITLE
`outputs` is not auto mounted

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4392]
Ours docs and command help say that `outputs:/outputs` is always added for `docker run` commands, but that is not the case since v1.4.0

```
→ bacalhau docker run --help | grep ResultPath
  -o, --output ResultPath       name=path of the output data volumes. 'outputs:/outputs' is always added unless '/outputs' is mapped to a different name.

```
→ bacalhau docker run --follow -p local ubuntu -- sh -c "echo hello > /outputs/hello.txt"
Job successfully submitted. Job ID: j-f92f5750-d635-4d12-88df-b11799a721df
Waiting for logs... (Enter Ctrl+C to exit at any time, your job will continue running):

sh: 1: cannot create /outputs/hello.txt: Directory nonexistent
```

**Comment by frrist** [comment]
Requires a change here: https://github.com/bacalhau-project/bacalhau/blob/main/cmd/util/flags/cliflags/task.go#L69 which will affect both wasm and docker. Or alternatively a change here https://github.com/bacalhau-project/bacalhau/blob/main/cmd/cli/docker/docker_run.go#L182 that only affects docker.

**Comment by frrist** [comment]
Change here is to update docs s.t. they don't say outputs are mounted by default.
