### ISSUE TITLE
`bacalhau serve --compute` spins an orchestrator as well

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4394]
`bacalhau serve --compute` still spins an orchestrator as well. This is because `--orchestrator` is always true. Even doing `bacalhau serve --node-types=compute` still spins an orchestrator.

The only way for it work is by calling `bacalhau-1.5.0 serve --compute --orchestrator=false`

**Comment by frrist** [comment]
The change here is to make both flags false by default and only apply the type of a flag if its changed, if none are changes its an orchestrator node.
