### ISSUE TITLE
Issue with errors and bad job ID

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#4431]
```
❯ bacalhau-1.5.0 job describe j-some-non-existend-job
Internal Server Error


```

`Internal Server Error` should be a last resort (it could be). But right now it's broken and I don't know why.

**Comment by udsamani** [comment]
I think the binary is not updated. Not able to see the same behavior. Double checking.

**Comment by udsamani** [comment]
Not an issue, as the server was running on older version.

**Comment by aronchick** [comment]
This could be true - but shouldn't we detect the protocol failure and tell them at least that?
