### ISSUE TITLE
Should notify when migrating config

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#4439]
When migrating config in v1.5.0, we should notify where things came from, and where they went to.

**Comment by wdbaruni** [comment]
Can you clarify what you mean? We print a log line saying we are migrating

**Comment by wdbaruni** [comment]
options to improve the log line:
- don't say the repo version, just say incompatible repo and migrating
- or add bacalhau version attached with repo version, and log something like "migrating from repo v1.4.0 to v1.5.0"
