### ISSUE TITLE
Too many logs during start

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#4471]
Nothing installed:

```
❯ b15 version
16:05:46.677 | INF pkg/config/config.go:211 > Config loaded from: [], and with data-dir v1.5.0/data-dir
16:05:46.678 | INF pkg/repo/fs.go:91 > Initializing repo at v1.5.0/data-dir
 CLIENT         UPDATE MESSAGE
 v1.5.0-alpha4

```

Neither log line should print - we SHOULD print something out saying what data directory we're using, and that we didn't find a repo, so we're creating one, but those should not be logs.

**Comment by wdbaruni** [comment]
The log line
```
16:05:46.677 | INF pkg/config/config.go:211 > Config loaded from: [], and with data-dir v1.5.0/data-dir
```
has been removed in #4488 and now we only log that in `bacalhau serve` and `bacalhau config list` commands. Though I am not sure I understand the desired behaviour for 
```
16:05:46.678 | INF pkg/repo/fs.go:91 > Initializing repo at v1.5.0/data-dir
```

That is a log line we print only the first time you run a newer version of bacalhau on a repo that belonged to an older version and migration is triggered. We don't log that anymore afterwards

> but those should not be logs.

Not sure I understand. Except for command outputs, everything we print should be a log line
