### ISSUE TITLE
DX Improvement: implement log streaming (--follow, much bigger project)

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#448]
ETA: 2023Q2

step 2 of  https://github.com/filecoin-project/bacalhau/issues/314

Is this very useful for now ?

**Comment by aronchick** [comment]
this is interesting - and useful! but why wouldn't this just be an overload of --local?

**Comment by lukemarsden** [comment]
i don't see how streaming logs from a running job has anything to do with --local

anyway, here's one way to implement it:
* include node addresses in the job metadata for a running job
* CLI can make a websocket connection or libp2p bitswap connection directly to one or more of the servers that are running a job
* when the connection is made initially, the backend streams the contents of `docker logs -f <containerid>` over the websocket/bitswap stream

**Comment by aronchick** [comment]
Yeah I think I put the local comment on the wrong issue. Deleting

**Comment by lukemarsden** [comment]
this is a big project, we should write a design doc for it - also, it's not particularly high priority

**Comment by wesfloyd** [comment]
Sharing an update that this feature will also be helpful for our partners LabDAO.

Goal: the request is for a way to pipe the stdout/stderr logs to a logging service or the user as the job is running. 

Benefit: to improve user feedback for longer running jobs. The attached image shows an example for a molecular docking tool that fills in a progress bar as the program runs. A little more helpful than the generic job running that bacalhau shows.
![image](https://user-images.githubusercontent.com/260568/219493706-ad76000a-59fc-4643-94b0-65c1f7de946b.png)

**Comment by rossjones** [comment]
First pass of logstreams is complete, and merged. There are a couple more tickets to improve what is there, but currently you can 

```
$ bacalhau docker run -f myimage
# or 
$ bacalhau logs <jobid>
$ bacalhau logs -f <jobid>
```
