### ISSUE TITLE
Unsupported repository version 0.

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4499]
Not sure how I was able to produce this, but I was mixing between starting devstack and normal hybrid node

```
failed to reconcile repo:
Unsupported repository version 0.
Bacalhau does not know how to read this configuration format and
you will need to upgrade to a newer version to upgrade this repository.
```

**Comment by frrist** [comment]
I suspect this will be addressed by: https://github.com/bacalhau-project/bacalhau/pull/4520 | https://github.com/bacalhau-project/bacalhau/pull/4521
