### ISSUE TITLE
Run tests on windows and validate everything is working fine

### ISSUE THREAD

**Issue by udsamani** [bacalhau-project/bacalhau#4525]

**Comment by wdbaruni** [comment]
@udsamani what is the status here?

**Comment by udsamani** [comment]
Tests Ran
 
 1. Spinning up a orchestrator node and then joining a compute node.
 
 
![Screenshot 2024-10-01 075511](https://github.com/user-attachments/assets/e21ac09e-d820-4c88-b75f-8b71dc6e8304)

**Comment by udsamani** [comment]
Job list, Job History

![Screenshot 2024-10-01 075948](https://github.com/user-attachments/assets/7764b887-39f8-460c-9963-d2e9e74d4482)
![Screenshot 2024-10-01 080104](https://github.com/user-attachments/assets/02b56778-a7c9-4d4e-a66e-5bebd3450e4a)

**Comment by udsamani** [comment]
Job Logs

![Screenshot 2024-10-01 080309](https://github.com/user-attachments/assets/9005f97d-129f-4faf-97f8-afecb3e87696)

**Comment by udsamani** [comment]
Job exceeding resource limits

![Screenshot 2024-10-01 081112](https://github.com/user-attachments/assets/6bca9446-611b-4a37-83dd-84b964e86266)
