### ISSUE TITLE
make this deterministic, return the first match alphabetically

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#453]
ETA: 2023Q2

```
	// TODO: make this deterministic, return the first match alphabetically
```

https://github.com/filecoin-project/bacalhau/blob/17961dbc6cb8f36ebac77f85d60309233dad2ee6/pkg/publicapi/client.go#L91

**Comment by wdbaruni** [comment]
We should avoid having collisions and multiple jobs sharing the same id! Also `Get` should not reuse `List` implementation. Will address this when moving localdb out of memory to a persisted storage

**Comment by wdbaruni** [comment]
Ah .. I see you already created an issue suggesting the same https://github.com/filecoin-project/bacalhau/issues/452
