### ISSUE TITLE
compute nodes not sharing their version with the orcehstrator

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4542]
for example:
```
Connection: CONNECTED
Info:
  BacalhauVersion:
    BuildDate: "0001-01-01T00:00:00Z"
    GOARCH: ""
    GOOS: ""
    GitCommit: ""
    GitVersion: ""
  ComputeNodeInfo:
    AvailableCapacity:
      CPU: 5.6
      Disk: 27094710272
      Memory: 12025908428
    EnqueuedExecutions: 0
    ExecutionEngines:
    - docker
    - wasm
    MaxCapacity:
      CPU: 5.6
      Disk: 27094710272
      Memory: 12025908428
    MaxJobRequirements:
      CPU: 5.6
      Disk: 27094710272
      Memory: 12025908428
    Publishers:
    - noop
    - s3
    - local
    QueueCapacity: {}
    RunningExecutions: 0
    StorageSources:
    - s3
    - urldownload
    - inline
  Labels:
    Architecture: arm64
    Operating-System: darwin
    name: mycompute
  NodeID: n-6bfe40a1-eeaa-49a7-8002-06da2a12bafa
  NodeType: Compute
```

**Comment by udsamani** [comment]
I am not able to reproduce this issue.

![Screenshot 2024-09-29 at 22 47 35](https://github.com/user-attachments/assets/3fa6c5b5-6f59-4992-a0d8-7e5cae8f309e)


@wdbaruni  Can you please add any steps which you followed that caused. Mainly would be on how you built it ?

**Comment by udsamani** [comment]
No worries found it. It is not a problem when you build from main branch rather an issue when you download pre-release version.

**Comment by udsamani** [comment]
![Screenshot 2024-09-29 at 23 36 59](https://github.com/user-attachments/assets/94dbdb98-7e8f-435f-beff-1079944d6db1)


Tried with 1.5.0 binary too

**Comment by wdbaruni** [comment]
here it works because you are describing the local node (orchestrator). Try joining another compute node and that won't work. It seems we have an issue with how compute nodes share their version through nats
