### ISSUE TITLE
--api-host has lower priority than -c api.host

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4547]
bacalhau serve --orchestrator -c config.yaml -c api.host=1.1.1.1 --api-host 3.3.3.3
resolves into 1.1.1.1 instead of the dedicated flag 3.3.3.3

**Comment by frrist** [comment]
This is by design: https://github.com/bacalhau-project/bacalhau/blob/main/pkg/config/config.go#L199 we test it here: https://github.com/bacalhau-project/bacalhau/blob/main/test/config_with_file_override_and_flag_and_config_flag.sh

Explicit config values take higher precedence than their corresponding flags.

**Comment by wdbaruni** [comment]
All configs can be configured using `-c key/value`, but only few have dedicated cli flags, such as `--api-host`, `data-dir`, ...

It sounds more logical that dedicated flags to have higher precedence than anything else, including `-c key/value`

**Comment by wdbaruni** [comment]
**Feedback from Sean**:
1. defaults
2. implicit config file
3. env vars
4. explicit config file
5. -c key/value
6. --api-host 

**Can be delivered for 1.5**:
1. defaults
4. explicit config file
3. env vars
5. -c key/value
6. --api-host 


```
Flags:
      --compute        When true the compute service will be enabled.
  -h, --help           help for serve
      --name string    The node's name.
                       If unset, it will be read from .bacalhau/system_metadata.yaml, or automatically generated if no name exists.
                       If set, and a name isn't present in .bacalhau/system_metadata.yaml the value is persisted, else ignored.
      --orchestrator   When true the orchestrator service will be enabled.

Global Flags:
      --api-host string   The host for the client and server to communicate on (via REST).
                          Ignored if BACALHAU_API_HOST environment variable is set. (default "0.0.0.0")
      --api-port int      The port for the client and server to communicate on (via REST).
                          Ignored if BACALHAU_API_PORT environment variable is set. (default 1234)
  -c, --config string     config file(s) or dot separated path(s) to config values
      --data-dir string   The filesystem path bacalhau inits or opens a repo in (default "/Users/walid/.bacalhau")
```
