### ISSUE TITLE
Heartbeat between Orchestrator and Compute node flapping connection state

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#4585]
### How to reproduce:
Use branch: `frrist/debug/heartbeat`
1. Start an orchestrator
2. start a compute node, connected to the orchestrator 
3. observer connection state to be normal
4. stop the orchestrator for ~2.5mins
5. observe the compute node failing to send heartbeat messages
6. start the orchestrator
7. observe after ~1.5min the connection state of the compute node flaps from connected to disconnected and back.

**Specifically notice the size of the priority queue in the orchestrator, and the sequence of the hb message being processed relative to the hb message being sent by the compute node. There is a lag.**

See logs: https://gist.github.com/frrist/e62e30ae4fd328773a0012e66dba0a5f

**Comment by frrist** [comment]
One reason for the flapping may be the behavior here:
https://github.com/bacalhau-project/bacalhau/blob/6e8858e0bba6b00a8b2007c70ce930c644c5ebfc/pkg/node/heartbeat/server.go#L138-L140

If the queue contains several heartbeat messages for the same node, some will be below the disconnect threshold, and some may be above it. This logic ensures we will find the one below it and consider the node disconnected even when valid heartbeat messages exist that would render the node connected.

**Comment by frrist** [comment]
Currently, the compute node sends a heartbeat message every 15 seconds. Further the compute node sends both legacy and current heartbeat messages. This means the compute node sends 4 heartbeat messages per minute. I have confirmed that removing the legacy heartbeat send from the compute node fixes the issue. This leads me to believe my above comment is on to something since given a set of 4 messages to check from a node there is high-ish likelihood at least one is outside the acceptable range.

**Comment by wdbaruni** [comment]
Closed by #4587
