### ISSUE TITLE
DX Improvement: Better error messages when sharding

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#462]
ETA: 2023Q2

If no atoms for sharding are found, we currently 500 the server, which is not correct (indicates system error).

Further, if docker is not running and you do a test, you get "no atoms found", which is wrong as well. 

We should:

- [ ] Fix errors to be appropriate and return information to the user (eg in `describe`)
- [ ] Not error on shards not found if/when docker isn't running on the node (that IS a system error, and, theoretically, the job should not have been accepted by the node)

**Comment by simonwo** [comment]
Sharding was binned.
