### ISSUE TITLE
HTTP URLs should support S3, GCS, Azure Blob, etc

### ISSUE THREAD

**Issue by enricorotundo** [bacalhau-project/bacalhau#473]
^

**Comment by enricorotundo** [comment]
Related to: https://github.com/filecoin-project/bacalhau/issues/494

**Comment by wdbaruni** [comment]
What do we mean by this tasks? S3 already supports reading objects through HTTP URLs. We just need to make the object public, which we have to do anyways since we don't support authenticated jobs yet. This is example of a public file I uploaded to S3:

```
bacalhau docker run --wait --input-urls https://bacalhau-test-s3-url-input.s3.eu-west-1.amazonaws.com/hello_world.txt ubuntu -- cat /inputs/hello_world.txt

```

**Comment by aronchick** [comment]
I think the feeling was to do the translation automatically maybe? not clear - happy to close/punt

**Comment by enricorotundo** [comment]
the idea was just to support URIs like `s3://<..>`, `blob://<..>`, etc.

**Comment by enricorotundo** [comment]
Related to https://github.com/bacalhau-project/bacalhau/issues/1971

**Comment by wdbaruni** [comment]
Done by https://github.com/bacalhau-project/bacalhau/pull/2264 and https://github.com/bacalhau-project/bacalhau/pull/2285
