### ISSUE TITLE
Auto-mounting CID for Local Content

### ISSUE THREAD

**Issue by wesfloyd** [bacalhau-project/bacalhau#474]
ETA: 2023Q2

Feature request: when we dropped the local flag, we hashed the local content, saw if the content was available on IPFS and if it was, auto mounted the CID. If it wasn't, we uploaded it. 

Per [this conversation](https://docs.google.com/document/d/1xxwsgz7uDEJqCqnfAsUbH7drnW5FJMEukSw5yoT6fa8/edit?disco=AAAAc_9RdFI) in the LabDAO integration grant planning doc:

> It'd be amazing if when we dropped the local flag, we hashed the local content, saw if the content was available on IPFS and if it was, auto mounted the CID. If it wasn't, we uploaded it. 
> Can you add this as a bug and tag Phil/Luke/Enrico?

**Comment by wesfloyd** [comment]
@philwinder @lukemarsden @enricorotundo for FYI

(@aronchick apologies for opening this bug a bit late!)

**Comment by aronchick** [comment]
No objection here to the functionality, but I think the auto mounting should be its own verb

**Comment by aronchick** [comment]
Man i like this one a lot :) @enricorotundo

**Comment by simonwo** [comment]
The plan for the inline storage feature was definitely to enable exactly this -- allow users to specify a local directory and have it included in the job. See https://github.com/filecoin-project/bacalhau/pull/1628

**Comment by aronchick** [comment]
@simonwo did this get finished?

**Comment by simonwo** [comment]
We never did #1765, which is still the MVP answer to this issue.

**Comment by wdbaruni** [comment]
seems finished to me
