### ISSUE TITLE
can we make our ipfs client connect to _our_ ipfs servers preferentially?

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#500]
finding CIDs on the global DHT is slooooooow
but if we talk directly to our nodes, maybe it will be quicker?

**Comment by wdbaruni** [comment]
ipfs first uses BitSwap in attempt to find CIDs in the peers the node is directly communicating with. It only falls back to DHT if non of the peers have the CID. If we are explicitly using DHT in our implementation, then we won't benefit from this optimization the default ipfs client has.
https://docs.ipfs.tech/concepts/bitswap/#discovery

Which area DHT is causing problems for us? When deciding locality of the CID before bidding, or other places?

**Comment by simonwo** [comment]
We do this now by listing swarm peers for our environments.
