### ISSUE TITLE
Client timeout with large CID with 165000 Images, size 27gb

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#526]
YOLO example which worked on 2, 100, 13675 images and now 165000 images size 27gb fails to run

COMMAND
`bacalhau docker run --wait --download --gpu 1 -v bafybeiekic3o3tuefajvlqeiyvvbq5kkr2g27qivuawpbqva7frv42radm:/datasets -o output:/usr/src/app/runs  ultralytics/yolov5:latest -- /bin/bash -c 'cp ../../../datasets/yolov5s.pt yolov5s.pt;python detect.py --weights yolov5s.pt --source ../../../datasets'`
this is the dataset https://bafybeiekic3o3tuefajvlqeiyvvbq5kkr2g27qivuawpbqva7frv42radm.ipfs.nftstorage.link/

error is
bacalhau describe f050bd33
`'Error running shard f050bd33-475f-42d5-8a69-1f5f7b25ba2d 0: runJob error f050bd33-475f-42d5-8a69-1f5f7b25ba2d: context deadline exceeded (Client.Timeout or context cancellation while reading body)'`

Example of a working command with 100 Images
`
bacalhau docker run --wait --download --gpu 1 -v bafybeifl26d2ucrdu7ydcvdln3ivzw5kwilooelu3gzmwl7ywi2gqnsu5q:/datasets -o output:/usr/src/app/runs  ultralytics/yolov5:latest -- /bin/bash -c 'cp ../../../datasets/yolov5s.pt yolov5s.pt;python detect.py --weights yolov5s.pt --source ../../../datasets'`

**Comment by aronchick** [comment]
Issue here is timeout - @wdbaruni does state machine work help here?

**Comment by wdbaruni** [comment]
No state machine won't help here other than possibly giving a better error on where the timeout is happening. @js-ts how long did the job continue running before it timed-out? Did you try with sharding?

**Comment by js-ts** [comment]
@wdbaruni Tried with sharding it gave the same error
```
time bacalhau docker run \
--wait \
  --wait-timeout-secs 20000 \
  --cpu 4 \
  --memory 8Gb \
  --sharding-base-path "/datasets" \
  --sharding-glob-pattern "*.jpg" \
  --sharding-batch-size 30000 \
-v bafybeiekic3o3tuefajvlqeiyvvbq5kkr2g27qivuawpbqva7frv42radm:/datasets  \
ultralytics/yolov5:latest \
 -- /bin/bash -c 'python detect.py --weights ../../../datasets/yolov5s.pt --source ../../../datasets  --project  ../../../outputs'

```

<img width="692" alt="image" src="https://user-images.githubusercontent.com/79689323/187017320-844df6fb-1c0a-4e7b-8c94-c151a75a05f2.png">

**Comment by aronchick** [comment]
Still a problem?

**Comment by js-ts** [comment]
yes

 bacalhau describe e990a703-59b4-46fe-a5cc-ebebd1cea51f
