### ISSUE TITLE
Block Analyzer to distinguish Filecoin+ Content

### ISSUE THREAD

**Issue by philwinder** [bacalhau-project/bacalhau#562]
ETA: 2023Q1

Need a block analyzer on Filecoin blockchain to identify whether deals (that contain CIDs) are Filecoin+ verified, then show the F+ icon on the [dashboard](https://github.com/filecoin-project/bacalhau/wiki/Bacalhau-project-report-20220902#filecoin-apis-and-dashboard) (rather than mocked as it is currently)

Needs more info from Kai about how this would work and where it needs to go.

**Comment by aronchick** [comment]
@binocarlos do you know what the status here is?
