### ISSUE TITLE
Improve bacalhau docker run --local

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#590]
ETA: 2023Q2

This is what it looks like to run a local command with Docker to simulate running in Bacalhau

```bash
docker run -e FILE_TO_PROCESS=/inputs/sample_set.csv -e OUTPUT_DIR=/outputs -v $(pwd):/inputs -v $(pwd)/outputs:/outputs bacalhauproject/dataprocessing-splitfile
```

I think, ideally, we could hide many of these, and just wrap docker run, in a way that simulated running in the cloud (so the function signature doesn't change). EG
```bash
bacalhau docker run --local -i $(pwd) -e OUTPUT_DIR=/outputs -e FILE_TO_PROCESS=/inputs/sample_set.csv bacalhauproject/dataprocessing-splitfile
```

Note, the above still doesn't feel perfect - IDEALLY we reached a point where the same thing you ran locally could just be run in the cloud the second you drop the `--local` flag.

**Comment by lukemarsden** [comment]
We see value in bacalhau docker run --local in particular around input directory paths not matching up, and testing that ahead of submitting a big job to a (future paid) network.

I agree that we should be able to drop the `--local` flag to run it on the network. So if `--local` currently allows you to mount a local folder into the job, maybe we should remove that feature!

**Comment by SvenDowideit** [comment]
I'd like to argue the case that being able to use local mounts is important and useful for both local and network jobs. In my experience, with researchers, they (imo correctly) don't see why the tool doesn't detect that the data isn't in the network filesystem, and for it to thus "make it so" in a default, safe way (ie, by default, load into a non-public file store, and process it in the safe non-public cluster).

lots of the details were punted on in Docker - but wouldn't it be excellent if Bacalhau could help users (with the quiet assistance of their organization's admins) focus entirely on their domain, and not on ours
