### ISSUE TITLE
Docs page for python wasm mode

### ISSUE THREAD

**Issue by philwinder** [bacalhau-project/bacalhau#616]
ETA: 2022Q4

We don't have a dedicated page explaining how wasm mode works. Luke mentioned some limitations like:
* requirements.txt only works with libraries that pyodide supports
* context (e.g. requirements.txt) is limited to 10MB
* Probably others.

Tasks:
* [ ] Explain what wasm mode is, why it is important, and how it works
* [ ] Present limitations/constraints
* [ ] Make a warning that this is experimental, and that most people are best of using docker mode for now

**Comment by simonwo** [comment]
This is deprecated.
