### ISSUE TITLE
need command to get peer id

### ISSUE THREAD

**Issue by binocarlos** [bacalhau-project/bacalhau#636]
Once a node has been started with `bacalhau serve` - a user might want to know what the peer id is of that node (so other nodes can then be connected to it).

We handle the auto-creation of the private key so the peer id remains consistent between restarts but there is currently no easy way to know what that peer id is.

For example - the output of the `ipfs id` command:

```bash
kai@xwing:~/projects/protocol-labs/docs.bacalhau.org$ ipfs id
{
        "ID": "12D3KooWFzgLAA88BmCKZFQYX7NUM7q5rwEZ561PeKvkpww6LT36",
        "PublicKey": "CAESIFvKd0GFvALIoC5HDqZXxMASFKpwkTY7F6xgBoswOTQp",
        "Addresses": null,
        "AgentVersion": "go-ipfs/0.12.2/",
        "ProtocolVersion": "ipfs/0.1.0",
        "Protocols": null
}
```

Bacalhau should have an equivalent `id` command that will fail if no private key has been found but will print something like the above if it is found.

This is to help compute operators who want to stand up nodes and connect other nodes to it.

**Comment by aronchick** [comment]
cc @binocarlos is this done?

**Comment by SvenDowideit** [comment]
```
sven@p1:~/src/ipfs/bacalhau$ ./bacalhau id
{
    "ID": "QmbquicBV2ThPGigatrTwTUkWAFGraqpbY6WGw2o4dAz4n"
}
``` 

?
