### ISSUE TITLE
Need to do a lot more testing here, we don't do any analysis of output files

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#637]
```
			// TODO: Need to do a lot more testing here, we don't do any analysis of output files
```

https://github.com/filecoin-project/bacalhau/blob/1b827858ad6b0772416554444e5c605a900fc9af/cmd/bacalhau/get_test.go#L111

**Comment by wjam** [comment]
TODO comment is no longer present so assumed to be done
