### ISSUE TITLE
Both of the default entrypoint and the commands in a container are blatted

### ISSUE THREAD

**Issue by philwinder** [bacalhau-project/bacalhau#656]
From a user perspective, if you define either an entrypoint or a command in a container, the defaults are overwritten with an empty value if you pass no arguments to bacalhau. This is unexpected, from a user perspective. Default container entrypoints and commands should be used.

From a code perspective, we only use an entrypoint, and overwrite that with the arguments passed to bacalhau (i.e. empty when you don't pass any). We don't use or pass the command at all.

E.g. entrypoint https://github.com/filecoin-project/bacalhau/blob/main/pkg/executor/docker/executor.go#L249

Here's a reference to the command part of the container config (which is not set): https://github.com/moby/moby/blob/master/api/types/container/config.go#L82

**Comment by wesfloyd** [comment]
Adding a note that we ran into this issue when testing for the Prelinger archive

`bacalhau docker run -v QmTYadG6K4LocouLu6wFzeMXNB5z8ikdpwuGqpdZNxp5qR:/project/inputs/LC08_L1TP_001028_20220615_20220627_02_T1_mosaic.tif -o outputs:/project/outputs/ --id-only wesfloyd/segmentation_testbed:latest`

**Comment by simonwo** [comment]
So the issue broadly is that containers can contain a default entry point and default command which will be invoked if user does not specify one. So eg running docker run ubuntu will use the default bash.However on Bacalhau we always overwrite the entry point with some value supplied on the CLI. I think this is just a CLI issue, so eg if the job spec doesn’t specify an entry point it isn’t used. So this is just about populating the job spec properly.So the job is:

1. Confirm that I am right, and that a job spec that does not specify an entry point will run the container default command. To do this, manually craft a job spec without an entry point which uses a container with a default, and check that it does the right thing
2. Work out how docker run parses it’s command line, eg how does it identify the entry point? It might just be the argument that appears before the --.
3. Add a test that not specifying the entrypoint works as expected, and the modify the CLI to make the test pass.

**Comment by simonwo** [comment]
So @olgibbons has found that:

- Docker uses ENTRYPOINT if set as the program to run in the image, and passes it the CMD as arguments.
- When you use `docker run ...` any extra arguments are interpreted as the CMD. The ENTRYPOINT is only overriden when explicitly using `--entrypoint`.
- When we use `bacalhau docker run ...` any extra arguments are interpreted as the ENTRYPOINT. The CMD is never used.

So the job to be done is:

- [ ]     Add a Parameters field to the JobSpecDocker to hold the CMD.
- [ ]     Change the Docker executor in pkg/executor/docker/ to set the CMD values in the container from the job spec, like we do for ENTRYPOINT.
- [ ]     Change the CLI to set positional arguments as the CMD and not the ENTRYPOINT.
- [ ]     Add a --entrypoint flag to the CLI to set the ENTRYPOINT.
