### ISSUE TITLE
Smarter clients about network capacity

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#691]
Just noticing. 

Start a devstack with Docker stopped - `make devstack-one`

Submit a job in a second window - `go run . docker run ubuntu "hello world"`

Notice in the server an error that docker isn't running. 

I guess this is to be expected, I wonder what we can push through to the requester node about awareness of the system scheduling capabilities. (e.g. "There are no docker nodes as part of the network, this will fail until one joins".

**Comment by wdbaruni** [comment]
related to https://github.com/filecoin-project/bacalhau/issues/464. After the fix the job will just timeout as no bids will be submitted after 2 minutes. After we switch to direct calls for job negotiation, the requester node will fail early as it will be aware of the network participants

**Comment by simonwo** [comment]
This is now fixed by executor aware scheduling:
```bash
% bac docker run ubuntu date
Using default tag: latest. Please specify a tag/digest for better reproducibility.
Job successfully submitted. Job ID: ddf9b6be-e2e5-4298-861b-b4790aadd800
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

	Communicating with the network  ................  done ✅  0.0s
	   Creating job for submission  ................  done ✅  0.0s
	   Job waiting to be scheduled  ................  done ✅  0.0s
	               Job in progress  ................  err  ❌  0.0s

Error submitting job: not enough nodes to run job. requested: 1, available: 0
Job Results By Node:
• Node QmV4fr55, QmcC1eu1, QmVVvTWN: Docker installed: false

To get more details about the run, execute:
	bacalhau describe ddf9b6be-e2e5-4298-861b-b4790aadd800
```
