### ISSUE TITLE
SETI@home / BOINC integration

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#699]

**Comment by wesfloyd** [comment]
Adding a related note on how this work can add additional value for Bacalhau.

The Saturn (Retrieval Markets) used a simulated load during their Alpha testing with their providers. Bacalhau should plan a similar steady state processing load for its "Compute Providers" during its alpha test run. 

The BOINC workloads would both help Bacalhau vet out performance testing and also provide valuable compute for humanity (via [BOINC projects](https://boinc.berkeley.edu/trac/wiki/ProjectMain)).

**Comment by wesfloyd** [comment]
Would it be possible for our BOINC integration to use @simonwo 's latest [proxy/limited Networking designs](https://www.notion.so/pl-strflt/Networking-434630300dad46668658d707e8eeabc6)?

**Comment by wjam** [comment]
Note that integration with SETI@home specifically will be difficult as the project is no longer running (https://www.seti.org/setihome-going-hibernation) although there are other BOINC-based projects available

**Comment by wesfloyd** [comment]
Agreed. Fortunately, we have lots of contacts within the BOINC project, including the creator and one of its maintainers. They can help guide us to find other [active projects](https://boinc.berkeley.edu/projects.php).
