### ISSUE TITLE
Ability to Submit Bacalhau Jobs via HTTP API

### ISSUE THREAD

**Issue by wesfloyd** [bacalhau-project/bacalhau#761]
Per recent conversations with Gitcoin Passport team - it would be valuable to submit jobs via React dApp to the Bacalhau network. Presumably this would involve a n HTTP [REST?] API request to the Bacalhau network.

Opening this as a placeholder issue for now - will followup soon with more detailed requirements.

**Comment by lukemarsden** [comment]
The Bacalhau API is already a REST API

**Comment by wesfloyd** [comment]
Is it open for external users to test currently? If so, can you share an example of how they should invoke it?

**Comment by lukemarsden** [comment]
we don't have docs for the api as yet because it's not stable, but they are welcome to give it a go!

**Comment by lukemarsden** [comment]
prod API endpoints are: https://github.com/filecoin-project/bacalhau/blob/de6a7305e8ab42b666624525f9dd6c23009c474e/pkg/system/constants.go#L28-L29

**Comment by wesfloyd** [comment]
Closing this issue per the generic dashboard endpoint documented here: https://bacalhau.substack.com/p/bacalhau-project-report-feb-3-2023#%C2%A7a-generic-endpoint
