### ISSUE TITLE
Measuring Bacalhau Task and Data Usage by User/Project/Wallet

### ISSUE THREAD

**Issue by wesfloyd** [bacalhau-project/bacalhau#773]
In order to understand where Bacalhau usage is coming from - it would be very helpful to have a mechanism built into the platform during our testnet phase that measures # of tasks and data used per task:
1. How many Bacalhau tasks did a given wallet or project execute?
2. What volume(GB/TB) of output data was used per task in IPFS/Estuary/Filecoin/etc. ?

For #1 other projects (ETH, Akash) have achieved this via token gating. Users get access to testnet tokens via a faucet that is automated, manually granted, or some combination of the two.

For #2 is there any location we could write the "volume of output data" that would be both usable (queryable) and public (IPFS native)? E.g. the [new CeramicDB](https://blog.ceramic.network/composedb-using-ceramic-as-a-graph-database/)?

**Comment by lukemarsden** [comment]
https://github.com/filecoin-project/bacalhau/issues/878 is the write part of #2
