### ISSUE TITLE
make --download the default

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#777]
then `bacalhau docker run ubuntu echo hello` will print `hello`!

**Comment by lukemarsden** [comment]
should still be possible to specify `--download=false` if you don't want to wait for and download the results

**Comment by wjam** [comment]
@lukemarsden Should this also apply to `bacalhau create`?

**Comment by lukemarsden** [comment]
No I don't think so, I think the expectation is that `bacalhau create` works more like `kubectl create`, which doesn't wait for anything, whereas `bacalhau docker run` works like `docker run` which does print stdout (well, stream stdout but close enough)

**Comment by aronchick** [comment]
In my opinion I wouldn’t do this. The point of our system is that the stuff is too big to run locally - and it’s hosted in IPFS. If we want small ways to view, huge fan of bacalhau cat or bacalhau ls

**Comment by lukemarsden** [comment]
Maybe we could make --wait also print the truncated stdout and err, then
make that the default then.

No big data downloads by default, but we still get echo hello works

**Comment by js-ts** [comment]
I agree with @aronchick, this won't work when the datasets are very big
Downloading something without the permission of the users not a good idea

**Comment by js-ts** [comment]
I don't disagree with printing stdout, I think it should be done by using ipfs cat <CID>/stdout
instead of downloading the outputs

**Comment by wdbaruni** [comment]
--wait currently prints the truncated stdout and err. Can we close this issue?
