### ISSUE TITLE
Investigate why downloads sometimes fail even with long timeouts

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#800]
First discussed in #787, downloading results of a job from IPFS fail:

- frequently when the timeout is only 10 seconds, 
- very occasionally when the timeout is 60 seconds,
- not at all when the timeout is 600 seconds. 

The average download time for a trivial job is 2-3s. So there seems to be some transient behaviour that makes downloading hang for long periods even when the job has been waited for.

We should investigate why this is and fix it to provide a better quality of experience. E.g. waiting 5 minutes for a download is clearly not great.

As an example job to use, try:

```
bacalhau docker run --download --download-timeout-secs N --inputs QmSgzNDSdkWKR8kBNLAKeaznjKUoD4NAJjgzt7248ktqxM ubuntu -- ls -l /inputs/.
```
where N is the number of seconds of timeout.

**Comment by lukemarsden** [comment]
If we are using Estuary as a default publisher, we could download directly from them. It would be quicker

**Comment by lukemarsden** [comment]
(We're not currently using Estuary because of some reliability bugs)

**Comment by aronchick** [comment]
@wjam did you fix this?

**Comment by simonwo** [comment]
I think this is part of what @philwinder and @wdbaruni is investigating.

**Comment by wjam** [comment]
@aronchick I haven't touched IPFS
