### ISSUE TITLE
command to cancel a job

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#847]
if a user starts a job that will run forever, it would be nice if they (or an admin) could cancel it

**Comment by wdbaruni** [comment]
Compute Nodes now expose `CancelShard` API that is currently used to terminate jobs after timeout window passes. We can expose this to the end users through the CLI and Requester Node to achieve the mentioned goal
https://github.com/filecoin-project/bacalhau/blob/fcf0ddd98a/pkg/computenode/computenode.go#L581
