### ISSUE TITLE
Public Audit Trail for Bacalhau Job History

### ISSUE THREAD

**Issue by wesfloyd** [bacalhau-project/bacalhau#858]
Goal:  the ability for Bacalhau job history to be written to a publicly verifiable medium. This will help us unlock workloads that rely on public compute (reproducibility) for researchers and web3 builders.

Functionality requested:
- Audit entry created for each job ran on Bacalhau network including: CIDs of inputs, outputs, and bacalhau command ran (e.g. "bacalhau docker run ubuntu hello world"), start and completion timestamps for the job.
- Audit histories for accessible publicly via IPFS or any equally public medium.

Partners that have asked for this capability for their workloads: Tableland, Ceramic, Gitcoin QF calculation

**Comment by wdbaruni** [comment]
I don't think a _public_ audit log is valid anymore, but an audit log for what is happening in your private network is absolutely valuable.  Created a new issue to track the private audit logs https://github.com/bacalhau-project/bacalhau/issues/4186
