### ISSUE TITLE
Spin up Spot/preemptible GPUs on AWS/GCP/Wherever that give us a bunch of shard targets for demos

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#861]
Basically, so we can shard stable diffusion over a bunch of nodes to demo sharding goodness without blowing our budget.

**Comment by lukemarsden** [comment]
What is our budget? How many shards do we want to run concurrently? Just want to be able to reason about any technical complexity introduced by using spot instances is worth it for the period we want to be able to demonstrate sharded GPU stable diffusion.

**Comment by lukemarsden** [comment]
Note that using spot instances is tricky becuase our workload is stateful and uses an attached volume per instance. We'd have to manage the pool of PVs along with the spot instance pool which is non-trivial.

**Comment by lukemarsden** [comment]
See also: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1665649662407629?thread_ts=1665633044.809999&cid=C02RLM3JHUY
