### ISSUE TITLE
Support for mounting git repos in the -r flag

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#872]
I think it will great to have -u flag supporting cloning/downloading .git repo from github and huggingface

So currently if you want mount a model from  https://huggingface.co/openai/clip-vit-large-patch14, you need to clone it locally and then upload it IPFS and then you can mount the CID

```
bacalhau docker run \
jsacex/stable-diffusion \
-v bafybeie3pocunkoigla4q6iyxq32tflaykx6vsspk5iwmppsnbk6bymqbu:/clip-vit-large-patch14-336
-- python demo.py --prompt "gouda being eaten by a spaceman on a horse" --output ../outputs/gouda.png --tokenizer ../clip-vit-large-patch14-336 
```

so I think it would make things lot easier for the users if they could directly mount their .git repos

```
bacalhau docker run \
jsacex/stable-diffusion \
 -u https://huggingface.co/openai/clip-vit-large-patch14-336
-- python demo.py --prompt "gouda being eaten by a spaceman on a horse" --output ../outputs/gouda.png --tokenizer ../inputs/clip-vit-large-patch14-336 
```

Suggestion from luke
> That would be cool, especially if you can refer to a specific commit, like pip can

**Comment by simonwo** [comment]
Sounds like @js-ts os working on this??

**Comment by js-ts** [comment]
yes
