### ISSUE TITLE
[Example] Large Scale Blockchain Analytics on bacalhau

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#883]
Large Scale blockchain dataset analysis is one of the most useful applications for bacalhau

Advantages of running on bacalhau
- Not having to move large blockchain datasets and do computations where the data is, if you want to do computations on blockchain data you have to move the datasets to centralized compute and storage providers
- open source unlike managed services
- use your own analytical tools or containers

Dataset
https://slingshot.filecoin.io/explore/public-blockchain-datasets

Use -u flag to get data from etherscan or any other APIs
https://api.etherscan.io/api?module=account&action=txlist&address=0xde0b295669a9fd93d5f28d9ec85e40f4cb697bae&startblock=0&endblock=99999999&page=1&offset=10&sort=asc&apikey=YourApiKeyToken

If there are any public datasets for a particular public blockchain (Ethereum smart contract dataset) on IPFS or Filecoin please comment 

Containers
build for a particular use case or blockchain

**Comment by XandraMcC** [comment]
I can take a look at this
