### ISSUE TITLE
monorepo

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#887]
* [ ] move docs repo into bacalhau repo
* [ ] move the examples repo into the bacalhau repo
* [ ] move the examples test runs into CircleCI, they should run in parallel

**Comment by lukemarsden** [comment]
see also #1133

**Comment by lukemarsden** [comment]
Moving the docs repo is urgent as it's affecting the DevRel team's productivity

**Comment by philwinder** [comment]
I will work on moving the docs.

**Comment by philwinder** [comment]
Re slack discussion: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1673870115743899

We should migrate the main repo first. That needs doing and solves DevRel's issues.
