### ISSUE TITLE
Bacalhau get fails on thin clients

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#890]
Retrieving results from Bacalhau is not a lightweight operation for thin clients to handle as it requires the client to join an IPFS network to start the download. This issue caused `submitAndGet` canary test case to sometimes fail and hang with no progress for a full minute even though they are downloading a 10 bytes file and usually succeed in less than 5 seconds.

The mitigation for now was to increase the canary lambda function capacity from 256mb to 1024mb

**Comment by lukemarsden** [comment]
Download straight from estuary and fall back to ipfs? Ref #878

**Comment by wdbaruni** [comment]
@frrist mentioned using [ipfs-lite](https://github.com/hsanjuan/ipfs-lite) before, and that can be an answer to the problem

**Comment by wdbaruni** [comment]
Not sure how estuary would work with data that wasn't uploaded through their client, and we can't upload all results using estuary as it is an overkill to persist all results in both ipfs and multiple filecoin service providers.

Another option is to allow users to pass an ipfs gateway endpoint and just download using http, and fall back to ipfs if no gateway was defined

**Comment by lukemarsden** [comment]
We specifically want to upload as much data to filecoin as possible
