### ISSUE TITLE
Uploading data docs out of date

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#939]
```
https://docs.bacalhau.org/examples/data-ingestion/
```

We talk about things not being pinned by default - they are now though. We should indicate that.

That said, it's nice to detail other pinning services and how to use them.

Also would help with this -> https://github.com/filecoin-project/bacalhau/issues/936

**Comment by fakela** [comment]
https://docs.bacalhau.org/examples/data-ingestion/pinning/
