### ISSUE TITLE
Nodes get disconnected from libp2p mesh (on devstack)

### ISSUE THREAD

**Issue by enricorotundo** [bacalhau-project/bacalhau#950]
## Context
In the **production environment**, we've seen that sometimes nodes disconnect from the libp2p network and therefore miss events such as job creation. This leads to errors like `Job not found` reported in https://github.com/filecoin-project/bacalhau/issues/934. The root cause of such disconnection has yet to be determined. 

To collect more information about the above, https://github.com/filecoin-project/bacalhau/pull/938  added an internal events logger to our libp2p node which logs to a JSON file. 

https://github.com/filecoin-project/bacalhau/pull/938 also activated `WithFloodPublish` which should be pro-actively publishing messages to every node.

Moreover, the production bootstrap connections number has been changed 1 -> 3 in https://github.com/filecoin-project/bacalhau/pull/944. This changed the topology of the production network from a star-shaped net to a fully connected mesh, the aim was to try to keep more routes for events to propagate.

<table class="tg">
<thead>
  <tr>
    <td class="tg-0pky"><img src="https://user-images.githubusercontent.com/4340327/198013972-74b61f46-002a-4255-8c99-e2ded433fbf0.png" data-canonical-src="https://user-images.githubusercontent.com/4340327/198013972-74b61f46-002a-4255-8c99-e2ded433fbf0.png" width="200" /&gt;</td>
    <td class="tg-c3ow"><img src="https://user-images.githubusercontent.com/4340327/198013992-792370a0-312c-43a7-9d47-1477cabdea3e.png" data-canonical-src="https://user-images.githubusercontent.com/4340327/198013992-792370a0-312c-43a7-9d47-1477cabdea3e.png" width="200" /&gt;</td>
  </tr>
</thead>
</table>
 
[Release v0.3.6](https://github.com/filecoin-project/bacalhau/releases/tag/v0.3.6) shipped the changes above, we're now keeping an eye out to see if it happens again in prod.

## Similar/same issue on my localhost
The `Job not found` error appeared with **devstack** running v0.3.6.

```
❯ bacalhau --api-port 20002 docker run ubuntu date
Job successfully submitted. Job ID: e47ceec2-564e-4ca8-ab9b-22831834c1a8
❯ bacalhau describe --api-port 20001 e47ceec2-564e-4ca8-ab9b-22831834c1a8
Job not found. ID: e47ceec2-564e-4ca8-ab9b-22831834c1a8
```

I don't have a repro for this but what happened is:

1. launched `bacalhau devstack` in the afternoon
2. laptop went to sleep overnight (which interrupts network comms?!)
3. resumed the following morning
4. `Job not found` popped up after (3) but **not** immediately after that

### Check network shape
Our network [viz tool](https://github.com/filecoin-project/bacalhau/tree/main/viz) renders a blank page, indicating nodes are disconnected from each other.

### Check libp2p tracer log file

The `bacalhau-libp2p-tracer.json` file (located at `~/.bacalhau`) should help shed a light on what happened. [Here's a link to my file for reference](https://slack-files.com/TEHTVS1L6-F04824GM2SH-cb046fd6ff).
Unfortunately, it seems to be malformed because it contains binary data (see screenshot below).

<img width="1264" alt="Screenshot 2022-10-26 at 13 59 36" src="https://user-images.githubusercontent.com/4340327/198020530-ed8772e6-59c7-4370-b5eb-7cc638805582.png">

On top of that, that file seems incomplete too because the first timestamp from `cat bacalhau-libp2p-tracer.json | jq` (whose [output is available on this gist](https://gist.github.com/enricorotundo/13c9a39aebceb2ed26a5f45c09a3e6b6)) is `1666772852236502000` which is a today's AM time (remember I launched devstack yesterday afternoon). Ok this may be `jq` silently ignoring the first part of the log file (i.e. logs prior to laptop sleep), in any case there's something wrong with the libp2p tracer file...

## Considerations

1. The libp2p tracer is not working properly, this is unexpected because [it's just a simple tracer](https://github.com/filecoin-project/bacalhau/blob/main/pkg/transport/libp2p/libp2p.go#L106)
1. There's a [suspicious score parameter decay in our libp2p package](https://github.com/filecoin-project/bacalhau/blob/5a6e956b841501a5290022139a6e5d32115a748d/pkg/transport/libp2p/libp2p.go#L95) that we don't fully understand but may be related to the disconnections: [its purpose is to kick out malicious nodes from the mesh (see libp2p docs)](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#peer-scoring) and this may be what's happening here
1. It's worth mentioning devstack bootstraps via a single node, as mentioned above production now uses 3 nodes.  
2. (1) and (2) may be unrelated 

Thanks @binocarlos for pairining on this one.

**Comment by aronchick** [comment]
stale?
