### ISSUE TITLE
move get website to somewhere we can track

### ISSUE THREAD

**Issue by binocarlos** [bacalhau-project/bacalhau#957]
It is hard to add the normal Google analytics code to `get.bacalhau.org` mainly because when doing:

`curl -sL https://get.bacalhau.org/install.sh | bash`

We are not loading HTML into a browser and so we would need to do server side tracking for this request.  The issue is `get.bacalhau.org` is hosted on github pages and there is no way of tapping into their server logs to track hits on `/install.sh`

We should move away from github pages so we can add analytics to the webserver and know how many people have downloaded `/install.sh`.

**Comment by aronchick** [comment]
i'm not sure about this - where are we tracking stats? why not just push every time someone accesses GH pages? It's quite convenient for a lot of stupid stuff
