### ISSUE TITLE
Bacalhau Execution of Data Stored in Filecoin

### ISSUE THREAD

**Issue by wesfloyd** [bacalhau-project/bacalhau#96]
ETA: 2023Q2

Purpose: to allow a Bacalhau cluster and job to execute on data stored in Filecoin.

Context: the current Bacalhau design operates on data stored in IPFS (via CID). This enhancement would involve some automation to retrieve data stored in Filecoin to the Bacalhau cluster before execution of the job can begin.

Requirements: Bacalhau will need to be enhanced to manage the retrieval deal flow as described here:
1. Discovery - the client identifies miners who have the data that it needs and requests a retrieval quote from them - price per byte, unseal price, payment interval.
2. Payment channel setup - the client sets up a payment channel between them and the miner (if one doesn’t already exist).
3. Data transfer with payment - miner sends data to client until payment is required. Payment processing is requested when a certain threshold is reached, and data transfer continues after that. Depending on whether the miner has the data in their block-store or not, they might need to first unseal it - a non-trivial and non-instantaneous operation, which is the opposite of sealing described in the section about storage deals.

References:
- [Blog: Storage and Retrieval Deal Flow](https://filecoin.io/blog/posts/how-storage-and-retrieval-deals-work-on-filecoin/#:~:text=The%20Retrieval%20Deal%20Flow&text=Data%20transmission%20is%20metered%2C%20and,interacting%20with%20the%20Filecoin%20blockchain)
- [Docs: Filecoin Retrieve Data](https://docs.filecoin.io/get-started/store-and-retrieve/retrieve-data/)

**Comment by aronchick** [comment]
@binocarlos do we have any state here? just curious where we should slot in
