### ISSUE TITLE
WASM job state is `Cancelled` while actually in progress 

### ISSUE THREAD

**Issue by enricorotundo** [bacalhau-project/bacalhau#963]
Not sure if this occurs only with the wasm executor but I while following [this example](https://docs.bacalhau.org/examples/workload-onboarding/rust-wasm/) I noticed my job state was `Cancelled` while actually being in progress. How come?

<img width="1282" alt="Screenshot 2022-10-27 at 13 11 27" src="https://user-images.githubusercontent.com/4340327/198269434-f6e2a942-4ec2-4a35-bc29-56c56dad897b.png">

**Comment by enricorotundo** [comment]
See the screenshot below. One node is in `Waiting` state and that should be the state displayed by `list`

<img width="1218" alt="Screenshot 2022-10-27 at 15 21 51" src="https://user-images.githubusercontent.com/4340327/198295965-a4783302-d91e-49db-8686-a0825e6b4ea5.png">

**Comment by wdbaruni** [comment]
Is it possible we have an inconsistency in the job state between the nodes depending on whose bid was accepted or rejected? Meaning when a compute node gets its bid rejected, it will show the job state as cancelled in `list` response, while the requester node and the compute node with accepted bid will show something different

**Comment by wdbaruni** [comment]
relates to https://github.com/filecoin-project/bacalhau/issues/992
